import {
    MSH,
    SFT,
    UAC,
    RF1,
    PRD,
    CTD,
    ORC,
    TQ1,
    TQ2,
    OBR,
    RXO,
    ODS,
    PR1,
    OBX,
    PRT,
    CTI,
    PID,
    PD1,
    NK1,
    IN1,
    IN2,
    IN3,
    SCH,
    RGS,
    AIS,
    AIG,
    AIL,
    AIP,
    AL1,
    IAM,
    ACC,
    RMI,
    DB1,
    DG1,
    DRG,
    ROL,
    VAR,
    PV1,
    PV2,
    RXR,
    RXC,
    RXE,
    RXA,
    PRB,
    GOL,
    PTH,
    REL,
} from '@healthcare-interoperability/hl7v2-segments';
import { TriggerEvent } from '@healthcare-interoperability/hl7v2-core';

export class CCR_I18 extends TriggerEvent {
    static TriggerEvent = 'CCR_I18';
    static Structure = {
        versions: {
            2.8: {
                sequences: [
                    {},
                    { identifier: 'MSH', sequence: '1', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: false },
                    { identifier: 'SFT', sequence: '2', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: false },
                    { identifier: 'UAC', sequence: '3', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: false },
                    { identifier: 'RF1', sequence: '4', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 }, isGroup: false },
                    { identifier: 'PRD', sequence: '5', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PROVIDER_CONTACT'] },
                    { identifier: 'CTD', sequence: '6', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PROVIDER_CONTACT'] },
                    { identifier: 'ORC', sequence: '7', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['CLINICAL_ORDER'] },
                    { identifier: 'TQ1', sequence: '8', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['CLINICAL_ORDER', 'CLINICAL_ORDER_TIMING'] },
                    { identifier: 'TQ2', sequence: '9', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['CLINICAL_ORDER', 'CLINICAL_ORDER_TIMING'] },
                    {
                        identifier: 'OBR',
                        sequence: '10',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['CLINICAL_ORDER', 'CLINICAL_ORDER_DETAIL', 'CLINICAL_ORDER_OBJECT'],
                    },
                    {
                        identifier: 'RXO',
                        sequence: '11',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['CLINICAL_ORDER', 'CLINICAL_ORDER_DETAIL', 'CLINICAL_ORDER_OBJECT'],
                    },
                    {
                        identifier: 'ODS',
                        sequence: '12',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['CLINICAL_ORDER', 'CLINICAL_ORDER_DETAIL', 'CLINICAL_ORDER_OBJECT'],
                    },
                    {
                        identifier: 'PR1',
                        sequence: '13',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['CLINICAL_ORDER', 'CLINICAL_ORDER_DETAIL', 'CLINICAL_ORDER_OBJECT'],
                    },
                    {
                        identifier: 'OBX',
                        sequence: '14',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['CLINICAL_ORDER', 'CLINICAL_ORDER_DETAIL', 'CLINICAL_ORDER_OBSERVATION'],
                    },
                    {
                        identifier: 'PRT',
                        sequence: '15',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['CLINICAL_ORDER', 'CLINICAL_ORDER_DETAIL', 'CLINICAL_ORDER_OBSERVATION'],
                    },
                    { identifier: 'CTI', sequence: '16', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['CLINICAL_ORDER'] },
                    { identifier: 'PID', sequence: '17', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT'] },
                    { identifier: 'PD1', sequence: '18', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT'] },
                    { identifier: 'NK1', sequence: '19', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: false },
                    { identifier: 'IN1', sequence: '20', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['INSURANCE'] },
                    { identifier: 'IN2', sequence: '21', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['INSURANCE'] },
                    { identifier: 'IN3', sequence: '22', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['INSURANCE'] },
                    { identifier: 'SCH', sequence: '23', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['APPOINTMENT_HISTORY'] },
                    { identifier: 'RGS', sequence: '24', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['APPOINTMENT_HISTORY', 'RESOURCES'] },
                    {
                        identifier: 'AIS',
                        sequence: '25',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['APPOINTMENT_HISTORY', 'RESOURCES', 'RESOURCE_DETAIL', 'RESOURCE_OBJECT'],
                    },
                    {
                        identifier: 'AIG',
                        sequence: '26',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['APPOINTMENT_HISTORY', 'RESOURCES', 'RESOURCE_DETAIL', 'RESOURCE_OBJECT'],
                    },
                    {
                        identifier: 'AIL',
                        sequence: '27',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['APPOINTMENT_HISTORY', 'RESOURCES', 'RESOURCE_DETAIL', 'RESOURCE_OBJECT'],
                    },
                    {
                        identifier: 'AIP',
                        sequence: '28',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['APPOINTMENT_HISTORY', 'RESOURCES', 'RESOURCE_DETAIL', 'RESOURCE_OBJECT'],
                    },
                    {
                        identifier: 'OBX',
                        sequence: '29',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['APPOINTMENT_HISTORY', 'RESOURCES', 'RESOURCE_DETAIL', 'RESOURCE_OBSERVATION'],
                    },
                    {
                        identifier: 'PRT',
                        sequence: '30',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['APPOINTMENT_HISTORY', 'RESOURCES', 'RESOURCE_DETAIL', 'RESOURCE_OBSERVATION'],
                    },
                    { identifier: 'ORC', sequence: '31', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['CLINICAL_HISTORY'] },
                    {
                        identifier: 'OBR',
                        sequence: '32',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['CLINICAL_HISTORY', 'CLINICAL_HISTORY_DETAIL', 'CLINICAL_HISTORY_OBJECT'],
                    },
                    {
                        identifier: 'ODS',
                        sequence: '33',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['CLINICAL_HISTORY', 'CLINICAL_HISTORY_DETAIL', 'CLINICAL_HISTORY_OBJECT'],
                    },
                    {
                        identifier: 'PR1',
                        sequence: '34',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['CLINICAL_HISTORY', 'CLINICAL_HISTORY_DETAIL', 'CLINICAL_HISTORY_OBJECT'],
                    },
                    {
                        identifier: 'RF1',
                        sequence: '35',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['CLINICAL_HISTORY', 'CLINICAL_HISTORY_DETAIL', 'CLINICAL_HISTORY_OBJECT'],
                    },
                    {
                        identifier: 'AL1',
                        sequence: '36',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['CLINICAL_HISTORY', 'CLINICAL_HISTORY_DETAIL', 'CLINICAL_HISTORY_OBJECT'],
                    },
                    {
                        identifier: 'IAM',
                        sequence: '37',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['CLINICAL_HISTORY', 'CLINICAL_HISTORY_DETAIL', 'CLINICAL_HISTORY_OBJECT'],
                    },
                    {
                        identifier: 'ACC',
                        sequence: '38',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['CLINICAL_HISTORY', 'CLINICAL_HISTORY_DETAIL', 'CLINICAL_HISTORY_OBJECT'],
                    },
                    {
                        identifier: 'RMI',
                        sequence: '39',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['CLINICAL_HISTORY', 'CLINICAL_HISTORY_DETAIL', 'CLINICAL_HISTORY_OBJECT'],
                    },
                    {
                        identifier: 'DB1',
                        sequence: '40',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['CLINICAL_HISTORY', 'CLINICAL_HISTORY_DETAIL', 'CLINICAL_HISTORY_OBJECT'],
                    },
                    {
                        identifier: 'DG1',
                        sequence: '41',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['CLINICAL_HISTORY', 'CLINICAL_HISTORY_DETAIL', 'CLINICAL_HISTORY_OBJECT'],
                    },
                    {
                        identifier: 'DRG',
                        sequence: '42',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['CLINICAL_HISTORY', 'CLINICAL_HISTORY_DETAIL', 'CLINICAL_HISTORY_OBJECT'],
                    },
                    {
                        identifier: 'OBX',
                        sequence: '43',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['CLINICAL_HISTORY', 'CLINICAL_HISTORY_DETAIL', 'CLINICAL_HISTORY_OBSERVATION'],
                    },
                    {
                        identifier: 'PRT',
                        sequence: '44',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['CLINICAL_HISTORY', 'CLINICAL_HISTORY_DETAIL', 'CLINICAL_HISTORY_OBSERVATION'],
                    },
                    {
                        identifier: 'ROL',
                        sequence: '45',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['CLINICAL_HISTORY', 'ROLE_CLINICAL_HISTORY', 'ROLE_CLINICAL_HISTORY_OBJECT'],
                    },
                    {
                        identifier: 'PRD',
                        sequence: '46',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['CLINICAL_HISTORY', 'ROLE_CLINICAL_HISTORY', 'ROLE_CLINICAL_HISTORY_OBJECT'],
                    },
                    { identifier: 'VAR', sequence: '47', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['CLINICAL_HISTORY', 'ROLE_CLINICAL_HISTORY'] },
                    { identifier: 'CTI', sequence: '48', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['CLINICAL_HISTORY'] },
                    { identifier: 'PV1', sequence: '49', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT_VISITS'] },
                    { identifier: 'PV2', sequence: '50', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT_VISITS'] },
                    { identifier: 'ORC', sequence: '51', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['MEDICATION_HISTORY'] },
                    { identifier: 'RXO', sequence: '52', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['MEDICATION_HISTORY', 'MEDICATION_ORDER_DETAIL'] },
                    {
                        identifier: 'RXR',
                        sequence: '53',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['MEDICATION_HISTORY', 'MEDICATION_ORDER_DETAIL'],
                    },
                    { identifier: 'RXC', sequence: '54', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['MEDICATION_HISTORY', 'MEDICATION_ORDER_DETAIL'] },
                    {
                        identifier: 'OBX',
                        sequence: '55',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['MEDICATION_HISTORY', 'MEDICATION_ORDER_DETAIL', 'MEDICATION_ORDER_OBSERVATION'],
                    },
                    {
                        identifier: 'PRT',
                        sequence: '56',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['MEDICATION_HISTORY', 'MEDICATION_ORDER_DETAIL', 'MEDICATION_ORDER_OBSERVATION'],
                    },
                    {
                        identifier: 'RXE',
                        sequence: '57',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['MEDICATION_HISTORY', 'MEDICATION_ENCODING_DETAIL'],
                    },
                    {
                        identifier: 'RXR',
                        sequence: '58',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['MEDICATION_HISTORY', 'MEDICATION_ENCODING_DETAIL'],
                    },
                    {
                        identifier: 'RXC',
                        sequence: '59',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['MEDICATION_HISTORY', 'MEDICATION_ENCODING_DETAIL'],
                    },
                    {
                        identifier: 'OBX',
                        sequence: '60',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['MEDICATION_HISTORY', 'MEDICATION_ENCODING_DETAIL', 'MEDICATION_ENCODING_OBSERVATION'],
                    },
                    {
                        identifier: 'PRT',
                        sequence: '61',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['MEDICATION_HISTORY', 'MEDICATION_ENCODING_DETAIL', 'MEDICATION_ENCODING_OBSERVATION'],
                    },
                    {
                        identifier: 'RXA',
                        sequence: '62',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['MEDICATION_HISTORY', 'MEDICATION_ADMINISTRATION_DETAIL'],
                    },
                    {
                        identifier: 'RXR',
                        sequence: '63',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['MEDICATION_HISTORY', 'MEDICATION_ADMINISTRATION_DETAIL'],
                    },
                    {
                        identifier: 'OBX',
                        sequence: '64',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['MEDICATION_HISTORY', 'MEDICATION_ADMINISTRATION_DETAIL', 'MEDICATION_ADMINISTRATION_OBSERVATION'],
                    },
                    {
                        identifier: 'PRT',
                        sequence: '65',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['MEDICATION_HISTORY', 'MEDICATION_ADMINISTRATION_DETAIL', 'MEDICATION_ADMINISTRATION_OBSERVATION'],
                    },
                    { identifier: 'CTI', sequence: '66', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['MEDICATION_HISTORY'] },
                    { identifier: 'PRB', sequence: '67', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PROBLEM'] },
                    { identifier: 'VAR', sequence: '68', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PROBLEM'] },
                    { identifier: 'ROL', sequence: '69', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['PROBLEM', 'ROLE_PROBLEM', 'ROLE_PROBLEM_OBJECT'] },
                    { identifier: 'PRD', sequence: '70', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['PROBLEM', 'ROLE_PROBLEM', 'ROLE_PROBLEM_OBJECT'] },
                    { identifier: 'VAR', sequence: '71', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PROBLEM', 'ROLE_PROBLEM'] },
                    { identifier: 'OBX', sequence: '72', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PROBLEM', 'PROBLEM_OBSERVATION'] },
                    { identifier: 'PRT', sequence: '73', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PROBLEM', 'PROBLEM_OBSERVATION'] },
                    { identifier: 'GOL', sequence: '74', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['GOAL'] },
                    { identifier: 'VAR', sequence: '75', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['GOAL'] },
                    { identifier: 'ROL', sequence: '76', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['GOAL', 'ROLE_GOAL', 'ROLE_GOAL_OBJECT'] },
                    { identifier: 'PRD', sequence: '77', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['GOAL', 'ROLE_GOAL', 'ROLE_GOAL_OBJECT'] },
                    { identifier: 'VAR', sequence: '78', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['GOAL', 'ROLE_GOAL'] },
                    { identifier: 'OBX', sequence: '79', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['GOAL', 'GOAL_OBSERVATION'] },
                    { identifier: 'PRT', sequence: '80', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['GOAL', 'GOAL_OBSERVATION'] },
                    { identifier: 'PTH', sequence: '81', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PATHWAY'] },
                    { identifier: 'VAR', sequence: '82', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATHWAY'] },
                    { identifier: 'ROL', sequence: '83', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['PATHWAY', 'ROLE_PATHWAY', 'ROLE_PATHWAY_OBJECT'] },
                    { identifier: 'PRD', sequence: '84', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['PATHWAY', 'ROLE_PATHWAY', 'ROLE_PATHWAY_OBJECT'] },
                    { identifier: 'VAR', sequence: '85', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATHWAY', 'ROLE_PATHWAY'] },
                    { identifier: 'OBX', sequence: '86', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATHWAY', 'PATHWAY_OBSERVATION'] },
                    { identifier: 'PRT', sequence: '87', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATHWAY', 'PATHWAY_OBSERVATION'] },
                    { identifier: 'REL', sequence: '88', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: false },
                ],
                groups: {
                    PROVIDER_CONTACT: { sequence: { start: '5', stop: '6' }, restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 }, subgroup: {} },
                    CLINICAL_ORDER: {
                        sequence: { start: '7', stop: '16' },
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        subgroup: {
                            CLINICAL_ORDER_TIMING: { sequence: { start: '8', stop: '9' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                            CLINICAL_ORDER_DETAIL: {
                                sequence: { start: null, stop: null },
                                restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 },
                                subgroup: {
                                    CLINICAL_ORDER_OBJECT: { sequence: { start: '10', stop: '13' }, restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, subgroup: {} },
                                    CLINICAL_ORDER_OBSERVATION: { sequence: { start: '14', stop: '15' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                                },
                            },
                        },
                    },
                    PATIENT: { sequence: { start: '17', stop: '18' }, restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 }, subgroup: {} },
                    INSURANCE: { sequence: { start: '20', stop: '22' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                    APPOINTMENT_HISTORY: {
                        sequence: { start: '23', stop: null },
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        subgroup: {
                            RESOURCES: {
                                sequence: { start: '24', stop: null },
                                restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                                subgroup: {
                                    RESOURCE_DETAIL: {
                                        sequence: { start: null, stop: null },
                                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                                        subgroup: {
                                            RESOURCE_OBJECT: { sequence: { start: '25', stop: '28' }, restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, subgroup: {} },
                                            RESOURCE_OBSERVATION: { sequence: { start: '29', stop: '30' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                                        },
                                    },
                                },
                            },
                        },
                    },
                    CLINICAL_HISTORY: {
                        sequence: { start: '31', stop: '48' },
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        subgroup: {
                            CLINICAL_HISTORY_DETAIL: {
                                sequence: { start: null, stop: null },
                                restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                                subgroup: {
                                    CLINICAL_HISTORY_OBJECT: { sequence: { start: '32', stop: '42' }, restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, subgroup: {} },
                                    CLINICAL_HISTORY_OBSERVATION: { sequence: { start: '43', stop: '44' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                                },
                            },
                            ROLE_CLINICAL_HISTORY: {
                                sequence: { start: null, stop: '47' },
                                restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                                subgroup: { ROLE_CLINICAL_HISTORY_OBJECT: { sequence: { start: '45', stop: '46' }, restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, subgroup: {} } },
                            },
                        },
                    },
                    PATIENT_VISITS: { sequence: { start: '49', stop: '50' }, restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 }, subgroup: {} },
                    MEDICATION_HISTORY: {
                        sequence: { start: '51', stop: '66' },
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        subgroup: {
                            MEDICATION_ORDER_DETAIL: {
                                sequence: { start: '52', stop: null },
                                restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                                subgroup: { MEDICATION_ORDER_OBSERVATION: { sequence: { start: '55', stop: '56' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} } },
                            },
                            MEDICATION_ENCODING_DETAIL: {
                                sequence: { start: '57', stop: null },
                                restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                                subgroup: { MEDICATION_ENCODING_OBSERVATION: { sequence: { start: '60', stop: '61' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} } },
                            },
                            MEDICATION_ADMINISTRATION_DETAIL: {
                                sequence: { start: '62', stop: null },
                                restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                                subgroup: {
                                    MEDICATION_ADMINISTRATION_OBSERVATION: { sequence: { start: '64', stop: '65' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                                },
                            },
                        },
                    },
                    PROBLEM: {
                        sequence: { start: '67', stop: null },
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        subgroup: {
                            ROLE_PROBLEM: {
                                sequence: { start: null, stop: '71' },
                                restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                                subgroup: { ROLE_PROBLEM_OBJECT: { sequence: { start: '69', stop: '70' }, restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, subgroup: {} } },
                            },
                            PROBLEM_OBSERVATION: { sequence: { start: '72', stop: '73' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                        },
                    },
                    GOAL: {
                        sequence: { start: '74', stop: null },
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        subgroup: {
                            ROLE_GOAL: {
                                sequence: { start: null, stop: '78' },
                                restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                                subgroup: { ROLE_GOAL_OBJECT: { sequence: { start: '76', stop: '77' }, restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, subgroup: {} } },
                            },
                            GOAL_OBSERVATION: { sequence: { start: '79', stop: '80' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                        },
                    },
                    PATHWAY: {
                        sequence: { start: '81', stop: null },
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        subgroup: {
                            ROLE_PATHWAY: {
                                sequence: { start: null, stop: '85' },
                                restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                                subgroup: { ROLE_PATHWAY_OBJECT: { sequence: { start: '83', stop: '84' }, restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, subgroup: {} } },
                            },
                            PATHWAY_OBSERVATION: { sequence: { start: '86', stop: '87' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                        },
                    },
                },
            },
            2.7: {
                sequences: [
                    {},
                    { identifier: 'MSH', sequence: '1', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: false },
                    { identifier: 'SFT', sequence: '2', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: false },
                    { identifier: 'UAC', sequence: '3', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: false },
                    { identifier: 'RF1', sequence: '4', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 }, isGroup: false },
                    { identifier: 'PRD', sequence: '5', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PROVIDER_CONTACT'] },
                    { identifier: 'CTD', sequence: '6', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PROVIDER_CONTACT'] },
                    { identifier: 'ORC', sequence: '7', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['CLINICAL_ORDER'] },
                    { identifier: 'TQ1', sequence: '8', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['CLINICAL_ORDER', 'CLINICAL_ORDER_TIMING'] },
                    { identifier: 'TQ2', sequence: '9', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['CLINICAL_ORDER', 'CLINICAL_ORDER_TIMING'] },
                    { identifier: 'OBR', sequence: '10', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['CLINICAL_ORDER', 'CLINICAL_ORDER_DETAIL'] },
                    { identifier: 'OBX', sequence: '11', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['CLINICAL_ORDER', 'CLINICAL_ORDER_DETAIL'] },
                    { identifier: 'CTI', sequence: '12', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['CLINICAL_ORDER'] },
                    { identifier: 'PID', sequence: '13', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT'] },
                    { identifier: 'PD1', sequence: '14', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT'] },
                    { identifier: 'NK1', sequence: '15', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: false },
                    { identifier: 'IN1', sequence: '16', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['INSURANCE'] },
                    { identifier: 'IN2', sequence: '17', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['INSURANCE'] },
                    { identifier: 'IN3', sequence: '18', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['INSURANCE'] },
                    { identifier: 'SCH', sequence: '19', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['APPOINTMENT_HISTORY'] },
                    { identifier: 'RGS', sequence: '20', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['APPOINTMENT_HISTORY', 'RESOURCES'] },
                    {
                        identifier: 'AIS',
                        sequence: '21',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['APPOINTMENT_HISTORY', 'RESOURCES', 'RESOURCE_DETAIL'],
                    },
                    {
                        identifier: 'OBX',
                        sequence: '22',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['APPOINTMENT_HISTORY', 'RESOURCES', 'RESOURCE_DETAIL'],
                    },
                    { identifier: 'ORC', sequence: '23', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['CLINICAL_HISTORY'] },
                    { identifier: 'OBR', sequence: '24', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['CLINICAL_HISTORY', 'CLINICAL_HISTORY_DETAIL'] },
                    { identifier: 'OBX', sequence: '25', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['CLINICAL_HISTORY', 'CLINICAL_HISTORY_DETAIL'] },
                    { identifier: 'ROL', sequence: '26', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['CLINICAL_HISTORY', 'ROLE_CLINICAL_HISTORY'] },
                    { identifier: 'VAR', sequence: '27', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['CLINICAL_HISTORY', 'ROLE_CLINICAL_HISTORY'] },
                    { identifier: 'CTI', sequence: '28', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['CLINICAL_HISTORY'] },
                    { identifier: 'PV1', sequence: '29', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT_VISITS'] },
                    { identifier: 'PV2', sequence: '30', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT_VISITS'] },
                    { identifier: 'ORC', sequence: '31', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['MEDICATION_HISTORY'] },
                    { identifier: 'RXO', sequence: '32', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['MEDICATION_HISTORY', 'MEDICATION_ORDER_DETAIL'] },
                    {
                        identifier: 'RXR',
                        sequence: '33',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['MEDICATION_HISTORY', 'MEDICATION_ORDER_DETAIL'],
                    },
                    { identifier: 'RXC', sequence: '34', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['MEDICATION_HISTORY', 'MEDICATION_ORDER_DETAIL'] },
                    { identifier: 'OBX', sequence: '35', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['MEDICATION_HISTORY', 'MEDICATION_ORDER_DETAIL'] },
                    {
                        identifier: 'RXE',
                        sequence: '36',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['MEDICATION_HISTORY', 'MEDICATION_ENCODING_DETAIL'],
                    },
                    {
                        identifier: 'RXR',
                        sequence: '37',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['MEDICATION_HISTORY', 'MEDICATION_ENCODING_DETAIL'],
                    },
                    {
                        identifier: 'RXC',
                        sequence: '38',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['MEDICATION_HISTORY', 'MEDICATION_ENCODING_DETAIL'],
                    },
                    {
                        identifier: 'OBX',
                        sequence: '39',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['MEDICATION_HISTORY', 'MEDICATION_ENCODING_DETAIL'],
                    },
                    {
                        identifier: 'RXA',
                        sequence: '40',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['MEDICATION_HISTORY', 'MEDICATION_ADMINISTRATION_DETAIL'],
                    },
                    {
                        identifier: 'RXR',
                        sequence: '41',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['MEDICATION_HISTORY', 'MEDICATION_ADMINISTRATION_DETAIL'],
                    },
                    {
                        identifier: 'OBX',
                        sequence: '42',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['MEDICATION_HISTORY', 'MEDICATION_ADMINISTRATION_DETAIL'],
                    },
                    { identifier: 'CTI', sequence: '43', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['MEDICATION_HISTORY'] },
                    { identifier: 'PRB', sequence: '44', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PROBLEM'] },
                    { identifier: 'VAR', sequence: '45', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PROBLEM'] },
                    { identifier: 'ROL', sequence: '46', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PROBLEM', 'ROLE_PROBLEM'] },
                    { identifier: 'VAR', sequence: '47', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PROBLEM', 'ROLE_PROBLEM'] },
                    { identifier: 'OBX', sequence: '48', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PROBLEM'] },
                    { identifier: 'GOL', sequence: '49', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['GOAL'] },
                    { identifier: 'VAR', sequence: '50', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['GOAL'] },
                    { identifier: 'ROL', sequence: '51', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['GOAL', 'ROLE_GOAL'] },
                    { identifier: 'VAR', sequence: '52', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['GOAL', 'ROLE_GOAL'] },
                    { identifier: 'OBX', sequence: '53', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['GOAL'] },
                    { identifier: 'PTH', sequence: '54', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PATHWAY'] },
                    { identifier: 'VAR', sequence: '55', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATHWAY'] },
                    { identifier: 'ROL', sequence: '56', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PATHWAY', 'ROLE_PATHWAY'] },
                    { identifier: 'VAR', sequence: '57', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATHWAY', 'ROLE_PATHWAY'] },
                    { identifier: 'OBX', sequence: '58', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATHWAY'] },
                    { identifier: 'REL', sequence: '59', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: false },
                ],
                groups: {
                    PROVIDER_CONTACT: { sequence: { start: '5', stop: '6' }, restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 }, subgroup: {} },
                    CLINICAL_ORDER: {
                        sequence: { start: '7', stop: '12' },
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        subgroup: {
                            CLINICAL_ORDER_TIMING: { sequence: { start: '8', stop: '9' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                            CLINICAL_ORDER_DETAIL: { sequence: { start: '10', stop: '11' }, restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 }, subgroup: {} },
                        },
                    },
                    PATIENT: { sequence: { start: '13', stop: '14' }, restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 }, subgroup: {} },
                    INSURANCE: { sequence: { start: '16', stop: '18' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                    APPOINTMENT_HISTORY: {
                        sequence: { start: '19', stop: null },
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        subgroup: {
                            RESOURCES: {
                                sequence: { start: '20', stop: null },
                                restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                                subgroup: { RESOURCE_DETAIL: { sequence: { start: '21', stop: '22' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} } },
                            },
                        },
                    },
                    CLINICAL_HISTORY: {
                        sequence: { start: '23', stop: '28' },
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        subgroup: {
                            CLINICAL_HISTORY_DETAIL: { sequence: { start: '24', stop: '25' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                            ROLE_CLINICAL_HISTORY: { sequence: { start: '26', stop: '27' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                        },
                    },
                    PATIENT_VISITS: { sequence: { start: '29', stop: '30' }, restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 }, subgroup: {} },
                    MEDICATION_HISTORY: {
                        sequence: { start: '31', stop: '43' },
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        subgroup: {
                            MEDICATION_ORDER_DETAIL: { sequence: { start: '32', stop: '35' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, subgroup: {} },
                            MEDICATION_ENCODING_DETAIL: { sequence: { start: '36', stop: '39' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, subgroup: {} },
                            MEDICATION_ADMINISTRATION_DETAIL: { sequence: { start: '40', stop: '42' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                        },
                    },
                    PROBLEM: {
                        sequence: { start: '44', stop: '48' },
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        subgroup: { ROLE_PROBLEM: { sequence: { start: '46', stop: '47' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} } },
                    },
                    GOAL: {
                        sequence: { start: '49', stop: '53' },
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        subgroup: { ROLE_GOAL: { sequence: { start: '51', stop: '52' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} } },
                    },
                    PATHWAY: {
                        sequence: { start: '54', stop: '58' },
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        subgroup: { ROLE_PATHWAY: { sequence: { start: '56', stop: '57' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} } },
                    },
                },
            },
            '2.7.1': {
                sequences: { ref: '2.7' },
                groups: { ref: '2.7' },
            },
        },
        segments: {
            MSH: MSH,
            SFT: SFT,
            UAC: UAC,
            RF1: RF1,
            PRD: PRD,
            CTD: CTD,
            ORC: ORC,
            TQ1: TQ1,
            TQ2: TQ2,
            OBR: OBR,
            RXO: RXO,
            ODS: ODS,
            PR1: PR1,
            OBX: OBX,
            PRT: PRT,
            CTI: CTI,
            PID: PID,
            PD1: PD1,
            NK1: NK1,
            IN1: IN1,
            IN2: IN2,
            IN3: IN3,
            SCH: SCH,
            RGS: RGS,
            AIS: AIS,
            AIG: AIG,
            AIL: AIL,
            AIP: AIP,
            AL1: AL1,
            IAM: IAM,
            ACC: ACC,
            RMI: RMI,
            DB1: DB1,
            DG1: DG1,
            DRG: DRG,
            ROL: ROL,
            VAR: VAR,
            PV1: PV1,
            PV2: PV2,
            RXR: RXR,
            RXC: RXC,
            RXE: RXE,
            RXA: RXA,
            PRB: PRB,
            GOL: GOL,
            PTH: PTH,
            REL: REL,
        },
    };

    constructor(message, version = null) {
        super(message, version);
    }
}
