import {
    MSH,
    SFT,
    UAC,
    RF1,
    PRD,
    CTD,
    PID,
    PD1,
    NK1,
    IN1,
    IN2,
    IN3,
    SCH,
    RGS,
    AIS,
    AIG,
    AIL,
    AIP,
    OBX,
    PRT,
    ORC,
    OBR,
    ODS,
    PR1,
    AL1,
    IAM,
    ACC,
    RMI,
    DB1,
    DG1,
    DRG,
    PDA,
    ROL,
    VAR,
    CTI,
    PV1,
    PV2,
    RXO,
    RXR,
    RXC,
    RXE,
    RXA,
    PRB,
    GOL,
    PTH,
    REL,
} from '@healthcare-interoperability/hl7v2-segments';
import { TriggerEvent } from '@healthcare-interoperability/hl7v2-core';

export class CCU_I20 extends TriggerEvent {
    static TriggerEvent = 'CCU_I20';
    static Structure = {
        versions: {
            2.8: {
                sequences: [
                    {},
                    { identifier: 'MSH', sequence: '1', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: false },
                    { identifier: 'SFT', sequence: '2', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: false },
                    { identifier: 'UAC', sequence: '3', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: false },
                    { identifier: 'RF1', sequence: '4', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: false },
                    { identifier: 'PRD', sequence: '5', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PROVIDER_CONTACT'] },
                    { identifier: 'CTD', sequence: '6', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PROVIDER_CONTACT'] },
                    { identifier: 'PID', sequence: '7', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT'] },
                    { identifier: 'PD1', sequence: '8', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT'] },
                    { identifier: 'NK1', sequence: '9', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: false },
                    { identifier: 'IN1', sequence: '10', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['INSURANCE'] },
                    { identifier: 'IN2', sequence: '11', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['INSURANCE'] },
                    { identifier: 'IN3', sequence: '12', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['INSURANCE'] },
                    { identifier: 'SCH', sequence: '13', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['APPOINTMENT_HISTORY'] },
                    { identifier: 'RGS', sequence: '14', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['APPOINTMENT_HISTORY', 'RESOURCES'] },
                    {
                        identifier: 'AIS',
                        sequence: '15',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['APPOINTMENT_HISTORY', 'RESOURCES', 'RESOURCE_DETAIL', 'RESOURCE_OBJECT'],
                    },
                    {
                        identifier: 'AIG',
                        sequence: '16',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['APPOINTMENT_HISTORY', 'RESOURCES', 'RESOURCE_DETAIL', 'RESOURCE_OBJECT'],
                    },
                    {
                        identifier: 'AIL',
                        sequence: '17',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['APPOINTMENT_HISTORY', 'RESOURCES', 'RESOURCE_DETAIL', 'RESOURCE_OBJECT'],
                    },
                    {
                        identifier: 'AIP',
                        sequence: '18',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['APPOINTMENT_HISTORY', 'RESOURCES', 'RESOURCE_DETAIL', 'RESOURCE_OBJECT'],
                    },
                    {
                        identifier: 'OBX',
                        sequence: '19',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['APPOINTMENT_HISTORY', 'RESOURCES', 'RESOURCE_DETAIL', 'RESOURCE_OBSERVATION'],
                    },
                    {
                        identifier: 'PRT',
                        sequence: '20',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['APPOINTMENT_HISTORY', 'RESOURCES', 'RESOURCE_DETAIL', 'RESOURCE_OBSERVATION'],
                    },
                    { identifier: 'ORC', sequence: '21', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['CLINICAL_HISTORY'] },
                    {
                        identifier: 'OBR',
                        sequence: '22',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['CLINICAL_HISTORY', 'CLINICAL_HISTORY_DETAIL', 'CLINICAL_HISTORY_OBJECT'],
                    },
                    {
                        identifier: 'ODS',
                        sequence: '23',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['CLINICAL_HISTORY', 'CLINICAL_HISTORY_DETAIL', 'CLINICAL_HISTORY_OBJECT'],
                    },
                    {
                        identifier: 'PR1',
                        sequence: '24',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['CLINICAL_HISTORY', 'CLINICAL_HISTORY_DETAIL', 'CLINICAL_HISTORY_OBJECT'],
                    },
                    {
                        identifier: 'RF1',
                        sequence: '25',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['CLINICAL_HISTORY', 'CLINICAL_HISTORY_DETAIL', 'CLINICAL_HISTORY_OBJECT'],
                    },
                    {
                        identifier: 'AL1',
                        sequence: '26',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['CLINICAL_HISTORY', 'CLINICAL_HISTORY_DETAIL', 'CLINICAL_HISTORY_OBJECT'],
                    },
                    {
                        identifier: 'IAM',
                        sequence: '27',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['CLINICAL_HISTORY', 'CLINICAL_HISTORY_DETAIL', 'CLINICAL_HISTORY_OBJECT'],
                    },
                    {
                        identifier: 'ACC',
                        sequence: '28',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['CLINICAL_HISTORY', 'CLINICAL_HISTORY_DETAIL', 'CLINICAL_HISTORY_OBJECT'],
                    },
                    {
                        identifier: 'RMI',
                        sequence: '29',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['CLINICAL_HISTORY', 'CLINICAL_HISTORY_DETAIL', 'CLINICAL_HISTORY_OBJECT'],
                    },
                    {
                        identifier: 'DB1',
                        sequence: '30',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['CLINICAL_HISTORY', 'CLINICAL_HISTORY_DETAIL', 'CLINICAL_HISTORY_OBJECT'],
                    },
                    {
                        identifier: 'DG1',
                        sequence: '31',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['CLINICAL_HISTORY', 'CLINICAL_HISTORY_DETAIL', 'CLINICAL_HISTORY_OBJECT'],
                    },
                    {
                        identifier: 'DRG',
                        sequence: '32',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['CLINICAL_HISTORY', 'CLINICAL_HISTORY_DETAIL', 'CLINICAL_HISTORY_OBJECT'],
                    },
                    {
                        identifier: 'PDA',
                        sequence: '33',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['CLINICAL_HISTORY', 'CLINICAL_HISTORY_DETAIL', 'CLINICAL_HISTORY_OBJECT'],
                    },
                    {
                        identifier: 'OBX',
                        sequence: '34',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['CLINICAL_HISTORY', 'CLINICAL_HISTORY_DETAIL', 'CLINICAL_HISTORY_OBSERVATION'],
                    },
                    {
                        identifier: 'PRT',
                        sequence: '35',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['CLINICAL_HISTORY', 'CLINICAL_HISTORY_DETAIL', 'CLINICAL_HISTORY_OBSERVATION'],
                    },
                    {
                        identifier: 'ROL',
                        sequence: '36',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['CLINICAL_HISTORY', 'ROLE_CLINICAL_HISTORY', 'ROLE_CLINICAL_HISTORY_OBJECT'],
                    },
                    {
                        identifier: 'PRD',
                        sequence: '37',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['CLINICAL_HISTORY', 'ROLE_CLINICAL_HISTORY', 'ROLE_CLINICAL_HISTORY_OBJECT'],
                    },
                    { identifier: 'VAR', sequence: '38', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['CLINICAL_HISTORY', 'ROLE_CLINICAL_HISTORY'] },
                    { identifier: 'CTI', sequence: '39', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['CLINICAL_HISTORY'] },
                    { identifier: 'PV1', sequence: '40', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT_VISITS'] },
                    { identifier: 'PV2', sequence: '41', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT_VISITS'] },
                    { identifier: 'ORC', sequence: '42', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['MEDICATION_HISTORY'] },
                    { identifier: 'RXO', sequence: '43', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['MEDICATION_HISTORY', 'MEDICATION_ORDER_DETAIL'] },
                    {
                        identifier: 'RXR',
                        sequence: '44',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['MEDICATION_HISTORY', 'MEDICATION_ORDER_DETAIL'],
                    },
                    { identifier: 'RXC', sequence: '45', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['MEDICATION_HISTORY', 'MEDICATION_ORDER_DETAIL'] },
                    {
                        identifier: 'OBX',
                        sequence: '46',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['MEDICATION_HISTORY', 'MEDICATION_ORDER_DETAIL', 'MEDICATION_ORDER_OBSERVATION'],
                    },
                    {
                        identifier: 'PRT',
                        sequence: '47',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['MEDICATION_HISTORY', 'MEDICATION_ORDER_DETAIL', 'MEDICATION_ORDER_OBSERVATION'],
                    },
                    {
                        identifier: 'RXE',
                        sequence: '48',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['MEDICATION_HISTORY', 'MEDICATION_ENCODING_DETAIL'],
                    },
                    {
                        identifier: 'RXR',
                        sequence: '49',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['MEDICATION_HISTORY', 'MEDICATION_ENCODING_DETAIL'],
                    },
                    {
                        identifier: 'RXC',
                        sequence: '50',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['MEDICATION_HISTORY', 'MEDICATION_ENCODING_DETAIL'],
                    },
                    {
                        identifier: 'OBX',
                        sequence: '51',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['MEDICATION_HISTORY', 'MEDICATION_ENCODING_DETAIL', 'MEDICATION_ENCODING_OBSERVATION'],
                    },
                    {
                        identifier: 'PRT',
                        sequence: '52',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['MEDICATION_HISTORY', 'MEDICATION_ENCODING_DETAIL', 'MEDICATION_ENCODING_OBSERVATION'],
                    },
                    {
                        identifier: 'RXA',
                        sequence: '53',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['MEDICATION_HISTORY', 'MEDICATION_ADMINISTRATION_DETAIL'],
                    },
                    {
                        identifier: 'RXR',
                        sequence: '54',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['MEDICATION_HISTORY', 'MEDICATION_ADMINISTRATION_DETAIL'],
                    },
                    {
                        identifier: 'OBX',
                        sequence: '55',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['MEDICATION_HISTORY', 'MEDICATION_ADMINISTRATION_DETAIL', 'MEDICATION_ADMINISTRATION_OBSERVATION'],
                    },
                    {
                        identifier: 'PRT',
                        sequence: '56',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['MEDICATION_HISTORY', 'MEDICATION_ADMINISTRATION_DETAIL', 'MEDICATION_ADMINISTRATION_OBSERVATION'],
                    },
                    { identifier: 'CTI', sequence: '57', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['MEDICATION_HISTORY'] },
                    { identifier: 'PRB', sequence: '58', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PROBLEM'] },
                    { identifier: 'VAR', sequence: '59', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PROBLEM'] },
                    { identifier: 'ROL', sequence: '60', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['PROBLEM', 'ROLE_PROBLEM', 'ROLE_PROBLEM_OBJECT'] },
                    { identifier: 'PRD', sequence: '61', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['PROBLEM', 'ROLE_PROBLEM', 'ROLE_PROBLEM_OBJECT'] },
                    { identifier: 'VAR', sequence: '62', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PROBLEM', 'ROLE_PROBLEM'] },
                    { identifier: 'OBX', sequence: '63', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PROBLEM', 'PROBLEM_OBSERVATION'] },
                    { identifier: 'PRT', sequence: '64', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PROBLEM', 'PROBLEM_OBSERVATION'] },
                    { identifier: 'GOL', sequence: '65', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['GOAL'] },
                    { identifier: 'VAR', sequence: '66', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['GOAL'] },
                    { identifier: 'ROL', sequence: '67', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['GOAL', 'ROLE_GOAL', 'ROLE_GOAL_OBJECT'] },
                    { identifier: 'PRD', sequence: '68', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['GOAL', 'ROLE_GOAL', 'ROLE_GOAL_OBJECT'] },
                    { identifier: 'VAR', sequence: '69', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['GOAL', 'ROLE_GOAL'] },
                    { identifier: 'OBX', sequence: '70', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['GOAL', 'GOAL_OBSERVATION'] },
                    { identifier: 'PRT', sequence: '71', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['GOAL', 'GOAL_OBSERVATION'] },
                    { identifier: 'PTH', sequence: '72', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PATHWAY'] },
                    { identifier: 'VAR', sequence: '73', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATHWAY'] },
                    { identifier: 'ROL', sequence: '74', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['PATHWAY', 'ROLE_PATHWAY', 'ROLE_PATHWAY_OBJECT'] },
                    { identifier: 'PRD', sequence: '75', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['PATHWAY', 'ROLE_PATHWAY', 'ROLE_PATHWAY_OBJECT'] },
                    { identifier: 'VAR', sequence: '76', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATHWAY', 'ROLE_PATHWAY'] },
                    { identifier: 'OBX', sequence: '77', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATHWAY', 'PATHWAY_OBSERVATION'] },
                    { identifier: 'PRT', sequence: '78', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATHWAY', 'PATHWAY_OBSERVATION'] },
                    { identifier: 'REL', sequence: '79', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: false },
                ],
                groups: {
                    PROVIDER_CONTACT: { sequence: { start: '5', stop: '6' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                    PATIENT: { sequence: { start: '7', stop: '8' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                    INSURANCE: { sequence: { start: '10', stop: '12' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                    APPOINTMENT_HISTORY: {
                        sequence: { start: '13', stop: null },
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        subgroup: {
                            RESOURCES: {
                                sequence: { start: '14', stop: null },
                                restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                                subgroup: {
                                    RESOURCE_DETAIL: {
                                        sequence: { start: null, stop: null },
                                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                                        subgroup: {
                                            RESOURCE_OBJECT: { sequence: { start: '15', stop: '18' }, restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, subgroup: {} },
                                            RESOURCE_OBSERVATION: { sequence: { start: '19', stop: '20' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                                        },
                                    },
                                },
                            },
                        },
                    },
                    CLINICAL_HISTORY: {
                        sequence: { start: '21', stop: '39' },
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        subgroup: {
                            CLINICAL_HISTORY_DETAIL: {
                                sequence: { start: null, stop: null },
                                restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                                subgroup: {
                                    CLINICAL_HISTORY_OBJECT: { sequence: { start: '22', stop: '33' }, restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, subgroup: {} },
                                    CLINICAL_HISTORY_OBSERVATION: { sequence: { start: '34', stop: '35' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                                },
                            },
                            ROLE_CLINICAL_HISTORY: {
                                sequence: { start: null, stop: '38' },
                                restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                                subgroup: { ROLE_CLINICAL_HISTORY_OBJECT: { sequence: { start: '36', stop: '37' }, restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, subgroup: {} } },
                            },
                        },
                    },
                    PATIENT_VISITS: { sequence: { start: '40', stop: '41' }, restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 }, subgroup: {} },
                    MEDICATION_HISTORY: {
                        sequence: { start: '42', stop: '57' },
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        subgroup: {
                            MEDICATION_ORDER_DETAIL: {
                                sequence: { start: '43', stop: null },
                                restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                                subgroup: { MEDICATION_ORDER_OBSERVATION: { sequence: { start: '46', stop: '47' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} } },
                            },
                            MEDICATION_ENCODING_DETAIL: {
                                sequence: { start: '48', stop: null },
                                restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                                subgroup: { MEDICATION_ENCODING_OBSERVATION: { sequence: { start: '51', stop: '52' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} } },
                            },
                            MEDICATION_ADMINISTRATION_DETAIL: {
                                sequence: { start: '53', stop: null },
                                restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                                subgroup: {
                                    MEDICATION_ADMINISTRATION_OBSERVATION: { sequence: { start: '55', stop: '56' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                                },
                            },
                        },
                    },
                    PROBLEM: {
                        sequence: { start: '58', stop: null },
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        subgroup: {
                            ROLE_PROBLEM: {
                                sequence: { start: null, stop: '62' },
                                restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                                subgroup: { ROLE_PROBLEM_OBJECT: { sequence: { start: '60', stop: '61' }, restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, subgroup: {} } },
                            },
                            PROBLEM_OBSERVATION: { sequence: { start: '63', stop: '64' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                        },
                    },
                    GOAL: {
                        sequence: { start: '65', stop: null },
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        subgroup: {
                            ROLE_GOAL: {
                                sequence: { start: null, stop: '69' },
                                restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                                subgroup: { ROLE_GOAL_OBJECT: { sequence: { start: '67', stop: '68' }, restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, subgroup: {} } },
                            },
                            GOAL_OBSERVATION: { sequence: { start: '70', stop: '71' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                        },
                    },
                    PATHWAY: {
                        sequence: { start: '72', stop: null },
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        subgroup: {
                            ROLE_PATHWAY: {
                                sequence: { start: null, stop: '76' },
                                restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                                subgroup: { ROLE_PATHWAY_OBJECT: { sequence: { start: '74', stop: '75' }, restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, subgroup: {} } },
                            },
                            PATHWAY_OBSERVATION: { sequence: { start: '77', stop: '78' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                        },
                    },
                },
            },
            2.7: {
                sequences: [
                    {},
                    { identifier: 'MSH', sequence: '1', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: false },
                    { identifier: 'SFT', sequence: '2', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: false },
                    { identifier: 'UAC', sequence: '3', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: false },
                    { identifier: 'RF1', sequence: '4', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: false },
                    { identifier: 'PRD', sequence: '5', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PROVIDER_CONTACT'] },
                    { identifier: 'CTD', sequence: '6', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PROVIDER_CONTACT'] },
                    { identifier: 'PID', sequence: '7', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT'] },
                    { identifier: 'PD1', sequence: '8', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT'] },
                    { identifier: 'NK1', sequence: '9', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: false },
                    { identifier: 'IN1', sequence: '10', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['INSURANCE'] },
                    { identifier: 'IN2', sequence: '11', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['INSURANCE'] },
                    { identifier: 'IN3', sequence: '12', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['INSURANCE'] },
                    { identifier: 'SCH', sequence: '13', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['APPOINTMENT_HISTORY'] },
                    { identifier: 'RGS', sequence: '14', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['APPOINTMENT_HISTORY', 'RESOURCES'] },
                    {
                        identifier: 'AIS',
                        sequence: '15',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['APPOINTMENT_HISTORY', 'RESOURCES', 'RESOURCE_DETAIL'],
                    },
                    {
                        identifier: 'OBX',
                        sequence: '16',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['APPOINTMENT_HISTORY', 'RESOURCES', 'RESOURCE_DETAIL'],
                    },
                    { identifier: 'ORC', sequence: '17', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['CLINICAL_HISTORY'] },
                    { identifier: 'OBR', sequence: '18', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['CLINICAL_HISTORY', 'CLINICAL_HISTORY_DETAIL'] },
                    { identifier: 'OBX', sequence: '19', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['CLINICAL_HISTORY', 'CLINICAL_HISTORY_DETAIL'] },
                    { identifier: 'ROL', sequence: '20', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['CLINICAL_HISTORY', 'ROLE_CLINICAL_HISTORY'] },
                    { identifier: 'VAR', sequence: '21', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['CLINICAL_HISTORY', 'ROLE_CLINICAL_HISTORY'] },
                    { identifier: 'CTI', sequence: '22', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['CLINICAL_HISTORY'] },
                    { identifier: 'PV1', sequence: '23', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT_VISITS'] },
                    { identifier: 'PV2', sequence: '24', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT_VISITS'] },
                    { identifier: 'ORC', sequence: '25', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['MEDICATION_HISTORY'] },
                    { identifier: 'RXO', sequence: '26', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['MEDICATION_HISTORY', 'MEDICATION_ORDER_DETAIL'] },
                    {
                        identifier: 'RXR',
                        sequence: '27',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['MEDICATION_HISTORY', 'MEDICATION_ORDER_DETAIL'],
                    },
                    { identifier: 'RXC', sequence: '28', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['MEDICATION_HISTORY', 'MEDICATION_ORDER_DETAIL'] },
                    { identifier: 'OBX', sequence: '29', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['MEDICATION_HISTORY', 'MEDICATION_ORDER_DETAIL'] },
                    {
                        identifier: 'RXE',
                        sequence: '30',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['MEDICATION_HISTORY', 'MEDICATION_ENCODING_DETAIL'],
                    },
                    {
                        identifier: 'RXR',
                        sequence: '31',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['MEDICATION_HISTORY', 'MEDICATION_ENCODING_DETAIL'],
                    },
                    {
                        identifier: 'RXC',
                        sequence: '32',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['MEDICATION_HISTORY', 'MEDICATION_ENCODING_DETAIL'],
                    },
                    {
                        identifier: 'OBX',
                        sequence: '33',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['MEDICATION_HISTORY', 'MEDICATION_ENCODING_DETAIL'],
                    },
                    {
                        identifier: 'RXA',
                        sequence: '34',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['MEDICATION_HISTORY', 'MEDICATION_ADMINISTRATION_DETAIL'],
                    },
                    {
                        identifier: 'RXR',
                        sequence: '35',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['MEDICATION_HISTORY', 'MEDICATION_ADMINISTRATION_DETAIL'],
                    },
                    {
                        identifier: 'OBX',
                        sequence: '36',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['MEDICATION_HISTORY', 'MEDICATION_ADMINISTRATION_DETAIL'],
                    },
                    { identifier: 'CTI', sequence: '37', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['MEDICATION_HISTORY'] },
                    { identifier: 'PRB', sequence: '38', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PROBLEM'] },
                    { identifier: 'VAR', sequence: '39', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PROBLEM'] },
                    { identifier: 'ROL', sequence: '40', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PROBLEM', 'ROLE_PROBLEM'] },
                    { identifier: 'VAR', sequence: '41', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PROBLEM', 'ROLE_PROBLEM'] },
                    { identifier: 'OBX', sequence: '42', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PROBLEM'] },
                    { identifier: 'GOL', sequence: '43', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['GOAL'] },
                    { identifier: 'VAR', sequence: '44', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['GOAL'] },
                    { identifier: 'ROL', sequence: '45', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['GOAL', 'ROLE_GOAL'] },
                    { identifier: 'VAR', sequence: '46', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['GOAL', 'ROLE_GOAL'] },
                    { identifier: 'OBX', sequence: '47', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['GOAL'] },
                    { identifier: 'PTH', sequence: '48', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PATHWAY'] },
                    { identifier: 'VAR', sequence: '49', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATHWAY'] },
                    { identifier: 'ROL', sequence: '50', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PATHWAY', 'ROLE_PATHWAY'] },
                    { identifier: 'VAR', sequence: '51', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATHWAY', 'ROLE_PATHWAY'] },
                    { identifier: 'OBX', sequence: '52', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATHWAY'] },
                    { identifier: 'REL', sequence: '53', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: false },
                ],
                groups: {
                    PROVIDER_CONTACT: { sequence: { start: '5', stop: '6' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                    PATIENT: { sequence: { start: '7', stop: '8' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                    INSURANCE: { sequence: { start: '10', stop: '12' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                    APPOINTMENT_HISTORY: {
                        sequence: { start: '13', stop: null },
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        subgroup: {
                            RESOURCES: {
                                sequence: { start: '14', stop: null },
                                restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                                subgroup: { RESOURCE_DETAIL: { sequence: { start: '15', stop: '16' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} } },
                            },
                        },
                    },
                    CLINICAL_HISTORY: {
                        sequence: { start: '17', stop: '22' },
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        subgroup: {
                            CLINICAL_HISTORY_DETAIL: { sequence: { start: '18', stop: '19' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                            ROLE_CLINICAL_HISTORY: { sequence: { start: '20', stop: '21' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                        },
                    },
                    PATIENT_VISITS: { sequence: { start: '23', stop: '24' }, restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 }, subgroup: {} },
                    MEDICATION_HISTORY: {
                        sequence: { start: '25', stop: '37' },
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        subgroup: {
                            MEDICATION_ORDER_DETAIL: { sequence: { start: '26', stop: '29' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, subgroup: {} },
                            MEDICATION_ENCODING_DETAIL: { sequence: { start: '30', stop: '33' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, subgroup: {} },
                            MEDICATION_ADMINISTRATION_DETAIL: { sequence: { start: '34', stop: '36' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                        },
                    },
                    PROBLEM: {
                        sequence: { start: '38', stop: '42' },
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        subgroup: { ROLE_PROBLEM: { sequence: { start: '40', stop: '41' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} } },
                    },
                    GOAL: {
                        sequence: { start: '43', stop: '47' },
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        subgroup: { ROLE_GOAL: { sequence: { start: '45', stop: '46' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} } },
                    },
                    PATHWAY: {
                        sequence: { start: '48', stop: '52' },
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        subgroup: { ROLE_PATHWAY: { sequence: { start: '50', stop: '51' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} } },
                    },
                },
            },
            '2.7.1': {
                sequences: { ref: '2.7' },
                groups: { ref: '2.7' },
            },
        },
        segments: {
            MSH: MSH,
            SFT: SFT,
            UAC: UAC,
            RF1: RF1,
            PRD: PRD,
            CTD: CTD,
            PID: PID,
            PD1: PD1,
            NK1: NK1,
            IN1: IN1,
            IN2: IN2,
            IN3: IN3,
            SCH: SCH,
            RGS: RGS,
            AIS: AIS,
            AIG: AIG,
            AIL: AIL,
            AIP: AIP,
            OBX: OBX,
            PRT: PRT,
            ORC: ORC,
            OBR: OBR,
            ODS: ODS,
            PR1: PR1,
            AL1: AL1,
            IAM: IAM,
            ACC: ACC,
            RMI: RMI,
            DB1: DB1,
            DG1: DG1,
            DRG: DRG,
            PDA: PDA,
            ROL: ROL,
            VAR: VAR,
            CTI: CTI,
            PV1: PV1,
            PV2: PV2,
            RXO: RXO,
            RXR: RXR,
            RXC: RXC,
            RXE: RXE,
            RXA: RXA,
            PRB: PRB,
            GOL: GOL,
            PTH: PTH,
            REL: REL,
        },
    };

    constructor(message, version = null) {
        super(message, version);
    }
}
