import { MSH, SFT, UAC, PID, PD1, PRT, ARV, NTE, PV1, PV2, CSR, CSP, CSS, ORC, OBR, TQ1, TQ2, OBX, RXA, RXR, ROL } from '@healthcare-interoperability/hl7v2-segments';
import { TriggerEvent } from '@healthcare-interoperability/hl7v2-core';

export class CSU_C12 extends TriggerEvent {
    static TriggerEvent = 'CSU_C12';
    static Structure = {
        versions: {
            2.8: {
                sequences: [
                    {},
                    { identifier: 'MSH', sequence: '1', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: false },
                    { identifier: 'SFT', sequence: '2', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: false },
                    { identifier: 'UAC', sequence: '3', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: false },
                    { identifier: 'PID', sequence: '4', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT'] },
                    { identifier: 'PD1', sequence: '5', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT'] },
                    { identifier: 'PRT', sequence: '6', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATIENT'] },
                    { identifier: 'ARV', sequence: '7', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATIENT'] },
                    { identifier: 'NTE', sequence: '8', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATIENT'] },
                    { identifier: 'PV1', sequence: '9', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT', 'VISIT'] },
                    { identifier: 'PV2', sequence: '10', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT', 'VISIT'] },
                    { identifier: 'PRT', sequence: '11', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATIENT', 'VISIT'] },
                    { identifier: 'CSR', sequence: '12', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT'] },
                    { identifier: 'CSP', sequence: '13', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT', 'STUDY_PHASE'] },
                    { identifier: 'CSS', sequence: '14', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT', 'STUDY_PHASE', 'STUDY_SCHEDULE'] },
                    {
                        identifier: 'ORC',
                        sequence: '15',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['PATIENT', 'STUDY_PHASE', 'STUDY_SCHEDULE', 'STUDY_OBSERVATION', 'COMMON_ORDER'],
                    },
                    {
                        identifier: 'PRT',
                        sequence: '16',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['PATIENT', 'STUDY_PHASE', 'STUDY_SCHEDULE', 'STUDY_OBSERVATION', 'COMMON_ORDER'],
                    },
                    {
                        identifier: 'OBR',
                        sequence: '17',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['PATIENT', 'STUDY_PHASE', 'STUDY_SCHEDULE', 'STUDY_OBSERVATION'],
                    },
                    {
                        identifier: 'PRT',
                        sequence: '18',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['PATIENT', 'STUDY_PHASE', 'STUDY_SCHEDULE', 'STUDY_OBSERVATION'],
                    },
                    {
                        identifier: 'TQ1',
                        sequence: '19',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['PATIENT', 'STUDY_PHASE', 'STUDY_SCHEDULE', 'STUDY_OBSERVATION', 'TIMING_QTY'],
                    },
                    {
                        identifier: 'TQ2',
                        sequence: '20',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['PATIENT', 'STUDY_PHASE', 'STUDY_SCHEDULE', 'STUDY_OBSERVATION', 'TIMING_QTY'],
                    },
                    {
                        identifier: 'OBX',
                        sequence: '21',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['PATIENT', 'STUDY_PHASE', 'STUDY_SCHEDULE', 'STUDY_OBSERVATION'],
                    },
                    {
                        identifier: 'PRT',
                        sequence: '22',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['PATIENT', 'STUDY_PHASE', 'STUDY_SCHEDULE', 'STUDY_OBSERVATION'],
                    },
                    {
                        identifier: 'ORC',
                        sequence: '23',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['PATIENT', 'STUDY_PHASE', 'STUDY_SCHEDULE', 'STUDY_PHARM', 'COMMON_ORDER'],
                    },
                    {
                        identifier: 'PRT',
                        sequence: '24',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['PATIENT', 'STUDY_PHASE', 'STUDY_SCHEDULE', 'STUDY_PHARM', 'COMMON_ORDER'],
                    },
                    {
                        identifier: 'RXA',
                        sequence: '25',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['PATIENT', 'STUDY_PHASE', 'STUDY_SCHEDULE', 'STUDY_PHARM', 'RX_ADMIN'],
                    },
                    {
                        identifier: 'RXR',
                        sequence: '26',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['PATIENT', 'STUDY_PHASE', 'STUDY_SCHEDULE', 'STUDY_PHARM', 'RX_ADMIN'],
                    },
                    {
                        identifier: 'PRT',
                        sequence: '27',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['PATIENT', 'STUDY_PHASE', 'STUDY_SCHEDULE', 'STUDY_PHARM', 'RX_ADMIN'],
                    },
                ],
                groups: {
                    PATIENT: {
                        sequence: { start: '4', stop: null },
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 },
                        subgroup: {
                            VISIT: { sequence: { start: '9', stop: '11' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, subgroup: {} },
                            STUDY_PHASE: {
                                sequence: { start: '13', stop: null },
                                restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 },
                                subgroup: {
                                    STUDY_SCHEDULE: {
                                        sequence: { start: '14', stop: null },
                                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 },
                                        subgroup: {
                                            STUDY_OBSERVATION: {
                                                sequence: { start: null, stop: '22' },
                                                restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 },
                                                subgroup: {
                                                    COMMON_ORDER: { sequence: { start: '15', stop: '16' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, subgroup: {} },
                                                    TIMING_QTY: { sequence: { start: '19', stop: '20' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                                                },
                                            },
                                            STUDY_PHARM: {
                                                sequence: { start: null, stop: null },
                                                restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 },
                                                subgroup: {
                                                    COMMON_ORDER: { sequence: { start: '23', stop: '24' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, subgroup: {} },
                                                    RX_ADMIN: { sequence: { start: '25', stop: '27' }, restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 }, subgroup: {} },
                                                },
                                            },
                                        },
                                    },
                                },
                            },
                        },
                    },
                },
            },
            2.3: {
                sequences: [
                    {},
                    { identifier: 'MSH', sequence: '1', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: false },
                    { identifier: 'PID', sequence: '2', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT'] },
                    { identifier: 'PD1', sequence: '3', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT'] },
                    { identifier: 'NTE', sequence: '4', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATIENT'] },
                    { identifier: 'PV1', sequence: '5', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT', 'VISIT'] },
                    { identifier: 'PV2', sequence: '6', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT', 'VISIT'] },
                    { identifier: 'CSR', sequence: '7', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT'] },
                    { identifier: 'CSP', sequence: '8', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT', 'STUDY_PHASE'] },
                    { identifier: 'CSS', sequence: '9', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT', 'STUDY_PHASE', 'STUDY_SCHEDULE'] },
                    {
                        identifier: 'ORC',
                        sequence: '10',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['PATIENT', 'STUDY_PHASE', 'STUDY_SCHEDULE', 'STUDY_OBSERVATION'],
                    },
                    {
                        identifier: 'OBR',
                        sequence: '11',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['PATIENT', 'STUDY_PHASE', 'STUDY_SCHEDULE', 'STUDY_OBSERVATION'],
                    },
                    {
                        identifier: 'OBX',
                        sequence: '12',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['PATIENT', 'STUDY_PHASE', 'STUDY_SCHEDULE', 'STUDY_OBSERVATION'],
                    },
                    {
                        identifier: 'ORC',
                        sequence: '13',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['PATIENT', 'STUDY_PHASE', 'STUDY_SCHEDULE', 'STUDY_PHARM'],
                    },
                    {
                        identifier: 'RXA',
                        sequence: '14',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['PATIENT', 'STUDY_PHASE', 'STUDY_SCHEDULE', 'STUDY_PHARM', 'RX_ADMIN'],
                    },
                    {
                        identifier: 'RXR',
                        sequence: '15',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['PATIENT', 'STUDY_PHASE', 'STUDY_SCHEDULE', 'STUDY_PHARM', 'RX_ADMIN'],
                    },
                ],
                groups: {
                    PATIENT: {
                        sequence: { start: '2', stop: null },
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 },
                        subgroup: {
                            VISIT: { sequence: { start: '5', stop: '6' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, subgroup: {} },
                            STUDY_PHASE: {
                                sequence: { start: '8', stop: null },
                                restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 },
                                subgroup: {
                                    STUDY_SCHEDULE: {
                                        sequence: { start: '9', stop: null },
                                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 },
                                        subgroup: {
                                            STUDY_OBSERVATION: { sequence: { start: '10', stop: '12' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                                            STUDY_PHARM: {
                                                sequence: { start: '13', stop: null },
                                                restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 },
                                                subgroup: { RX_ADMIN: { sequence: { start: '14', stop: '15' }, restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 }, subgroup: {} } },
                                            },
                                        },
                                    },
                                },
                            },
                        },
                    },
                },
            },
            '2.3.1': {
                sequences: { ref: '2.3' },
                groups: {
                    PATIENT: {
                        sequence: { start: '2', stop: null },
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 },
                        subgroup: {
                            VISIT: { sequence: { start: '5', stop: '6' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, subgroup: {} },
                            STUDY_PHASE: {
                                sequence: { start: '8', stop: null },
                                restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 },
                                subgroup: {
                                    STUDY_SCHEDULE: {
                                        sequence: { start: '9', stop: null },
                                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 },
                                        subgroup: {
                                            STUDY_OBSERVATION: { sequence: { start: '10', stop: '12' }, restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 }, subgroup: {} },
                                            STUDY_PHARM: {
                                                sequence: { start: '13', stop: null },
                                                restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 },
                                                subgroup: { RX_ADMIN: { sequence: { start: '14', stop: '15' }, restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 }, subgroup: {} } },
                                            },
                                        },
                                    },
                                },
                            },
                        },
                    },
                },
            },
            2.4: {
                sequences: [
                    {},
                    { identifier: 'MSH', sequence: '1', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: false },
                    { identifier: 'PID', sequence: '2', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT'] },
                    { identifier: 'PD1', sequence: '3', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT'] },
                    { identifier: 'NTE', sequence: '4', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATIENT'] },
                    { identifier: 'PV1', sequence: '5', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT', 'VISIT'] },
                    { identifier: 'PV2', sequence: '6', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT', 'VISIT'] },
                    { identifier: 'CSR', sequence: '7', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT'] },
                    { identifier: 'CSP', sequence: '8', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATIENT', 'STUDY_PHASE'] },
                    { identifier: 'CSS', sequence: '9', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT', 'STUDY_PHASE', 'STUDY_SCHEDULE'] },
                    {
                        identifier: 'ORC',
                        sequence: '10',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['PATIENT', 'STUDY_PHASE', 'STUDY_SCHEDULE', 'STUDY_OBSERVATION'],
                    },
                    {
                        identifier: 'OBR',
                        sequence: '11',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['PATIENT', 'STUDY_PHASE', 'STUDY_SCHEDULE', 'STUDY_OBSERVATION'],
                    },
                    {
                        identifier: 'OBX',
                        sequence: '12',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['PATIENT', 'STUDY_PHASE', 'STUDY_SCHEDULE', 'STUDY_OBSERVATION'],
                    },
                    {
                        identifier: 'ORC',
                        sequence: '13',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['PATIENT', 'STUDY_PHASE', 'STUDY_SCHEDULE', 'STUDY_PHARM'],
                    },
                    {
                        identifier: 'RXA',
                        sequence: '14',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['PATIENT', 'STUDY_PHASE', 'STUDY_SCHEDULE', 'STUDY_PHARM', 'RX_ADMIN'],
                    },
                    {
                        identifier: 'RXR',
                        sequence: '15',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['PATIENT', 'STUDY_PHASE', 'STUDY_SCHEDULE', 'STUDY_PHARM', 'RX_ADMIN'],
                    },
                ],
                groups: { ref: '2.3.1' },
            },
            2.5: {
                sequences: [
                    {},
                    { identifier: 'MSH', sequence: '1', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: false },
                    { identifier: 'SFT', sequence: '2', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: false },
                    { identifier: 'PID', sequence: '3', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT'] },
                    { identifier: 'PD1', sequence: '4', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT'] },
                    { identifier: 'NTE', sequence: '5', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATIENT'] },
                    { identifier: 'PV1', sequence: '6', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT', 'VISIT'] },
                    { identifier: 'PV2', sequence: '7', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT', 'VISIT'] },
                    { identifier: 'CSR', sequence: '8', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT'] },
                    { identifier: 'CSP', sequence: '9', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT', 'STUDY_PHASE'] },
                    { identifier: 'CSS', sequence: '10', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT', 'STUDY_PHASE', 'STUDY_SCHEDULE'] },
                    {
                        identifier: 'ORC',
                        sequence: '11',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['PATIENT', 'STUDY_PHASE', 'STUDY_SCHEDULE', 'STUDY_OBSERVATION'],
                    },
                    {
                        identifier: 'OBR',
                        sequence: '12',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['PATIENT', 'STUDY_PHASE', 'STUDY_SCHEDULE', 'STUDY_OBSERVATION'],
                    },
                    {
                        identifier: 'TQ1',
                        sequence: '13',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['PATIENT', 'STUDY_PHASE', 'STUDY_SCHEDULE', 'STUDY_OBSERVATION', 'TIMING_QTY'],
                    },
                    {
                        identifier: 'TQ2',
                        sequence: '14',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['PATIENT', 'STUDY_PHASE', 'STUDY_SCHEDULE', 'STUDY_OBSERVATION', 'TIMING_QTY'],
                    },
                    {
                        identifier: 'OBX',
                        sequence: '15',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['PATIENT', 'STUDY_PHASE', 'STUDY_SCHEDULE', 'STUDY_OBSERVATION'],
                    },
                    {
                        identifier: 'ORC',
                        sequence: '16',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['PATIENT', 'STUDY_PHASE', 'STUDY_SCHEDULE', 'STUDY_PHARM'],
                    },
                    {
                        identifier: 'RXA',
                        sequence: '17',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['PATIENT', 'STUDY_PHASE', 'STUDY_SCHEDULE', 'STUDY_PHARM', 'RX_ADMIN'],
                    },
                    {
                        identifier: 'RXR',
                        sequence: '18',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['PATIENT', 'STUDY_PHASE', 'STUDY_SCHEDULE', 'STUDY_PHARM', 'RX_ADMIN'],
                    },
                ],
                groups: {
                    PATIENT: {
                        sequence: { start: '3', stop: null },
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 },
                        subgroup: {
                            VISIT: { sequence: { start: '6', stop: '7' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, subgroup: {} },
                            STUDY_PHASE: {
                                sequence: { start: '9', stop: null },
                                restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 },
                                subgroup: {
                                    STUDY_SCHEDULE: {
                                        sequence: { start: '10', stop: null },
                                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 },
                                        subgroup: {
                                            STUDY_OBSERVATION: {
                                                sequence: { start: '11', stop: '15' },
                                                restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 },
                                                subgroup: { TIMING_QTY: { sequence: { start: '13', stop: '14' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} } },
                                            },
                                            STUDY_PHARM: {
                                                sequence: { start: '16', stop: null },
                                                restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 },
                                                subgroup: { RX_ADMIN: { sequence: { start: '17', stop: '18' }, restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 }, subgroup: {} } },
                                            },
                                        },
                                    },
                                },
                            },
                        },
                    },
                },
            },
            '2.5.1': {
                sequences: { ref: '2.5' },
                groups: { ref: '2.5' },
            },
            2.6: {
                sequences: [
                    {},
                    { identifier: 'MSH', sequence: '1', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: false },
                    { identifier: 'SFT', sequence: '2', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: false },
                    { identifier: 'UAC', sequence: '3', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: false },
                    { identifier: 'PID', sequence: '4', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT'] },
                    { identifier: 'PD1', sequence: '5', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT'] },
                    { identifier: 'NTE', sequence: '6', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATIENT'] },
                    { identifier: 'PV1', sequence: '7', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT', 'VISIT'] },
                    { identifier: 'PV2', sequence: '8', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT', 'VISIT'] },
                    { identifier: 'CSR', sequence: '9', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT'] },
                    { identifier: 'CSP', sequence: '10', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT', 'STUDY_PHASE'] },
                    { identifier: 'CSS', sequence: '11', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT', 'STUDY_PHASE', 'STUDY_SCHEDULE'] },
                    {
                        identifier: 'ORC',
                        sequence: '12',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['PATIENT', 'STUDY_PHASE', 'STUDY_SCHEDULE', 'STUDY_OBSERVATION'],
                    },
                    {
                        identifier: 'OBR',
                        sequence: '13',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['PATIENT', 'STUDY_PHASE', 'STUDY_SCHEDULE', 'STUDY_OBSERVATION'],
                    },
                    {
                        identifier: 'ROL',
                        sequence: '14',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['PATIENT', 'STUDY_PHASE', 'STUDY_SCHEDULE', 'STUDY_OBSERVATION'],
                    },
                    {
                        identifier: 'TQ1',
                        sequence: '15',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['PATIENT', 'STUDY_PHASE', 'STUDY_SCHEDULE', 'STUDY_OBSERVATION', 'TIMING_QTY'],
                    },
                    {
                        identifier: 'TQ2',
                        sequence: '16',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['PATIENT', 'STUDY_PHASE', 'STUDY_SCHEDULE', 'STUDY_OBSERVATION', 'TIMING_QTY'],
                    },
                    {
                        identifier: 'OBX',
                        sequence: '17',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['PATIENT', 'STUDY_PHASE', 'STUDY_SCHEDULE', 'STUDY_OBSERVATION'],
                    },
                    {
                        identifier: 'ORC',
                        sequence: '18',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['PATIENT', 'STUDY_PHASE', 'STUDY_SCHEDULE', 'STUDY_PHARM'],
                    },
                    {
                        identifier: 'RXA',
                        sequence: '19',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['PATIENT', 'STUDY_PHASE', 'STUDY_SCHEDULE', 'STUDY_PHARM', 'RX_ADMIN'],
                    },
                    {
                        identifier: 'RXR',
                        sequence: '20',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['PATIENT', 'STUDY_PHASE', 'STUDY_SCHEDULE', 'STUDY_PHARM', 'RX_ADMIN'],
                    },
                ],
                groups: {
                    PATIENT: {
                        sequence: { start: '4', stop: null },
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 },
                        subgroup: {
                            VISIT: { sequence: { start: '7', stop: '8' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, subgroup: {} },
                            STUDY_PHASE: {
                                sequence: { start: '10', stop: null },
                                restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 },
                                subgroup: {
                                    STUDY_SCHEDULE: {
                                        sequence: { start: '11', stop: null },
                                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 },
                                        subgroup: {
                                            STUDY_OBSERVATION: {
                                                sequence: { start: '12', stop: '17' },
                                                restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 },
                                                subgroup: { TIMING_QTY: { sequence: { start: '15', stop: '16' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} } },
                                            },
                                            STUDY_PHARM: {
                                                sequence: { start: '18', stop: null },
                                                restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 },
                                                subgroup: { RX_ADMIN: { sequence: { start: '19', stop: '20' }, restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 }, subgroup: {} } },
                                            },
                                        },
                                    },
                                },
                            },
                        },
                    },
                },
            },
            2.7: {
                sequences: [
                    {},
                    { identifier: 'MSH', sequence: '1', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: false },
                    { identifier: 'SFT', sequence: '2', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: false },
                    { identifier: 'UAC', sequence: '3', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: false },
                    { identifier: 'PID', sequence: '4', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT'] },
                    { identifier: 'PD1', sequence: '5', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT'] },
                    { identifier: 'PRT', sequence: '6', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATIENT'] },
                    { identifier: 'NTE', sequence: '7', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATIENT'] },
                    { identifier: 'PV1', sequence: '8', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT', 'VISIT'] },
                    { identifier: 'PV2', sequence: '9', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT', 'VISIT'] },
                    { identifier: 'PRT', sequence: '10', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATIENT', 'VISIT'] },
                    { identifier: 'CSR', sequence: '11', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT'] },
                    { identifier: 'CSP', sequence: '12', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT', 'STUDY_PHASE'] },
                    { identifier: 'CSS', sequence: '13', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT', 'STUDY_PHASE', 'STUDY_SCHEDULE'] },
                    {
                        identifier: 'ORC',
                        sequence: '14',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['PATIENT', 'STUDY_PHASE', 'STUDY_SCHEDULE', 'STUDY_OBSERVATION'],
                    },
                    {
                        identifier: 'OBR',
                        sequence: '15',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['PATIENT', 'STUDY_PHASE', 'STUDY_SCHEDULE', 'STUDY_OBSERVATION'],
                    },
                    {
                        identifier: 'PRT',
                        sequence: '16',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['PATIENT', 'STUDY_PHASE', 'STUDY_SCHEDULE', 'STUDY_OBSERVATION'],
                    },
                    {
                        identifier: 'TQ1',
                        sequence: '17',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['PATIENT', 'STUDY_PHASE', 'STUDY_SCHEDULE', 'STUDY_OBSERVATION', 'TIMING_QTY'],
                    },
                    {
                        identifier: 'TQ2',
                        sequence: '18',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['PATIENT', 'STUDY_PHASE', 'STUDY_SCHEDULE', 'STUDY_OBSERVATION', 'TIMING_QTY'],
                    },
                    {
                        identifier: 'OBX',
                        sequence: '19',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['PATIENT', 'STUDY_PHASE', 'STUDY_SCHEDULE', 'STUDY_OBSERVATION'],
                    },
                    {
                        identifier: 'PRT',
                        sequence: '20',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['PATIENT', 'STUDY_PHASE', 'STUDY_SCHEDULE', 'STUDY_OBSERVATION'],
                    },
                    {
                        identifier: 'ORC',
                        sequence: '21',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['PATIENT', 'STUDY_PHASE', 'STUDY_SCHEDULE', 'STUDY_PHARM', 'COMMON_ORDER'],
                    },
                    {
                        identifier: 'PRT',
                        sequence: '22',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['PATIENT', 'STUDY_PHASE', 'STUDY_SCHEDULE', 'STUDY_PHARM', 'COMMON_ORDER'],
                    },
                    {
                        identifier: 'RXA',
                        sequence: '23',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['PATIENT', 'STUDY_PHASE', 'STUDY_SCHEDULE', 'STUDY_PHARM', 'RX_ADMIN'],
                    },
                    {
                        identifier: 'RXR',
                        sequence: '24',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['PATIENT', 'STUDY_PHASE', 'STUDY_SCHEDULE', 'STUDY_PHARM', 'RX_ADMIN'],
                    },
                    {
                        identifier: 'PRT',
                        sequence: '25',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['PATIENT', 'STUDY_PHASE', 'STUDY_SCHEDULE', 'STUDY_PHARM', 'RX_ADMIN'],
                    },
                ],
                groups: {
                    PATIENT: {
                        sequence: { start: '4', stop: null },
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 },
                        subgroup: {
                            VISIT: { sequence: { start: '8', stop: '10' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, subgroup: {} },
                            STUDY_PHASE: {
                                sequence: { start: '12', stop: null },
                                restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 },
                                subgroup: {
                                    STUDY_SCHEDULE: {
                                        sequence: { start: '13', stop: null },
                                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 },
                                        subgroup: {
                                            STUDY_OBSERVATION: {
                                                sequence: { start: '14', stop: '20' },
                                                restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 },
                                                subgroup: { TIMING_QTY: { sequence: { start: '17', stop: '18' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} } },
                                            },
                                            STUDY_PHARM: {
                                                sequence: { start: null, stop: null },
                                                restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 },
                                                subgroup: {
                                                    COMMON_ORDER: { sequence: { start: '21', stop: '22' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, subgroup: {} },
                                                    RX_ADMIN: { sequence: { start: '23', stop: '25' }, restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 }, subgroup: {} },
                                                },
                                            },
                                        },
                                    },
                                },
                            },
                        },
                    },
                },
            },
            '2.7.1': {
                sequences: { ref: '2.7' },
                groups: { ref: '2.7' },
            },
        },
        segments: {
            MSH: MSH,
            SFT: SFT,
            UAC: UAC,
            PID: PID,
            PD1: PD1,
            PRT: PRT,
            ARV: ARV,
            NTE: NTE,
            PV1: PV1,
            PV2: PV2,
            CSR: CSR,
            CSP: CSP,
            CSS: CSS,
            ORC: ORC,
            OBR: OBR,
            TQ1: TQ1,
            TQ2: TQ2,
            OBX: OBX,
            RXA: RXA,
            RXR: RXR,
            ROL: ROL,
        },
    };

    constructor(message, version = null) {
        super(message, version);
    }
}
