import { MSH, SFT, UAC, IVC, PYE, CTD, AUT, LOC, PRT, ROL, PSS, PSG, PID, PV1, PV2, ACC, IN1, IN2, DG1, NTE, OBX, PSL, ADJ, PR1, IPR } from '@healthcare-interoperability/hl7v2-segments';
import { TriggerEvent } from '@healthcare-interoperability/hl7v2-core';

export class EHC_E01 extends TriggerEvent {
    static TriggerEvent = 'EHC_E01';
    static Structure = {
        versions: {
            2.8: {
                sequences: [
                    {},
                    { identifier: 'MSH', sequence: '1', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: false },
                    { identifier: 'SFT', sequence: '2', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: false },
                    { identifier: 'UAC', sequence: '3', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: false },
                    { identifier: 'IVC', sequence: '4', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['INVOICE_INFORMATION_SUBMIT'] },
                    { identifier: 'PYE', sequence: '5', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['INVOICE_INFORMATION_SUBMIT'] },
                    { identifier: 'CTD', sequence: '6', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['INVOICE_INFORMATION_SUBMIT'] },
                    { identifier: 'AUT', sequence: '7', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['INVOICE_INFORMATION_SUBMIT'] },
                    { identifier: 'LOC', sequence: '8', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['INVOICE_INFORMATION_SUBMIT'] },
                    { identifier: 'PRT', sequence: '9', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['INVOICE_INFORMATION_SUBMIT'] },
                    { identifier: 'ROL', sequence: '10', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['INVOICE_INFORMATION_SUBMIT'] },
                    {
                        identifier: 'PSS',
                        sequence: '11',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['INVOICE_INFORMATION_SUBMIT', 'PRODUCT_SERVICE_SECTION'],
                    },
                    {
                        identifier: 'PSG',
                        sequence: '12',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['INVOICE_INFORMATION_SUBMIT', 'PRODUCT_SERVICE_SECTION', 'PRODUCT_SERVICE_GROUP'],
                    },
                    {
                        identifier: 'LOC',
                        sequence: '13',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['INVOICE_INFORMATION_SUBMIT', 'PRODUCT_SERVICE_SECTION', 'PRODUCT_SERVICE_GROUP'],
                    },
                    {
                        identifier: 'PRT',
                        sequence: '14',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['INVOICE_INFORMATION_SUBMIT', 'PRODUCT_SERVICE_SECTION', 'PRODUCT_SERVICE_GROUP'],
                    },
                    {
                        identifier: 'ROL',
                        sequence: '15',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['INVOICE_INFORMATION_SUBMIT', 'PRODUCT_SERVICE_SECTION', 'PRODUCT_SERVICE_GROUP'],
                    },
                    {
                        identifier: 'PID',
                        sequence: '16',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['INVOICE_INFORMATION_SUBMIT', 'PRODUCT_SERVICE_SECTION', 'PRODUCT_SERVICE_GROUP', 'PATIENT_INFO'],
                    },
                    {
                        identifier: 'PV1',
                        sequence: '17',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['INVOICE_INFORMATION_SUBMIT', 'PRODUCT_SERVICE_SECTION', 'PRODUCT_SERVICE_GROUP', 'PATIENT_INFO'],
                    },
                    {
                        identifier: 'PV2',
                        sequence: '18',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['INVOICE_INFORMATION_SUBMIT', 'PRODUCT_SERVICE_SECTION', 'PRODUCT_SERVICE_GROUP', 'PATIENT_INFO'],
                    },
                    {
                        identifier: 'ACC',
                        sequence: '19',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['INVOICE_INFORMATION_SUBMIT', 'PRODUCT_SERVICE_SECTION', 'PRODUCT_SERVICE_GROUP', 'PATIENT_INFO'],
                    },
                    {
                        identifier: 'IN1',
                        sequence: '20',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['INVOICE_INFORMATION_SUBMIT', 'PRODUCT_SERVICE_SECTION', 'PRODUCT_SERVICE_GROUP', 'PATIENT_INFO', 'INSURANCE'],
                    },
                    {
                        identifier: 'IN2',
                        sequence: '21',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['INVOICE_INFORMATION_SUBMIT', 'PRODUCT_SERVICE_SECTION', 'PRODUCT_SERVICE_GROUP', 'PATIENT_INFO', 'INSURANCE'],
                    },
                    {
                        identifier: 'DG1',
                        sequence: '22',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['INVOICE_INFORMATION_SUBMIT', 'PRODUCT_SERVICE_SECTION', 'PRODUCT_SERVICE_GROUP', 'PATIENT_INFO', 'DIAGNOSIS'],
                    },
                    {
                        identifier: 'NTE',
                        sequence: '23',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['INVOICE_INFORMATION_SUBMIT', 'PRODUCT_SERVICE_SECTION', 'PRODUCT_SERVICE_GROUP', 'PATIENT_INFO', 'DIAGNOSIS'],
                    },
                    {
                        identifier: 'OBX',
                        sequence: '24',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['INVOICE_INFORMATION_SUBMIT', 'PRODUCT_SERVICE_SECTION', 'PRODUCT_SERVICE_GROUP', 'PATIENT_INFO'],
                    },
                    {
                        identifier: 'PSL',
                        sequence: '25',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['INVOICE_INFORMATION_SUBMIT', 'PRODUCT_SERVICE_SECTION', 'PRODUCT_SERVICE_GROUP', 'PRODUCT_SERVICE_LINE_ITEM'],
                    },
                    {
                        identifier: 'NTE',
                        sequence: '26',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['INVOICE_INFORMATION_SUBMIT', 'PRODUCT_SERVICE_SECTION', 'PRODUCT_SERVICE_GROUP', 'PRODUCT_SERVICE_LINE_ITEM'],
                    },
                    {
                        identifier: 'ADJ',
                        sequence: '27',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['INVOICE_INFORMATION_SUBMIT', 'PRODUCT_SERVICE_SECTION', 'PRODUCT_SERVICE_GROUP', 'PRODUCT_SERVICE_LINE_ITEM'],
                    },
                    {
                        identifier: 'AUT',
                        sequence: '28',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['INVOICE_INFORMATION_SUBMIT', 'PRODUCT_SERVICE_SECTION', 'PRODUCT_SERVICE_GROUP', 'PRODUCT_SERVICE_LINE_ITEM'],
                    },
                    {
                        identifier: 'LOC',
                        sequence: '29',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['INVOICE_INFORMATION_SUBMIT', 'PRODUCT_SERVICE_SECTION', 'PRODUCT_SERVICE_GROUP', 'PRODUCT_SERVICE_LINE_ITEM'],
                    },
                    {
                        identifier: 'PRT',
                        sequence: '30',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['INVOICE_INFORMATION_SUBMIT', 'PRODUCT_SERVICE_SECTION', 'PRODUCT_SERVICE_GROUP', 'PRODUCT_SERVICE_LINE_ITEM'],
                    },
                    {
                        identifier: 'ROL',
                        sequence: '31',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['INVOICE_INFORMATION_SUBMIT', 'PRODUCT_SERVICE_SECTION', 'PRODUCT_SERVICE_GROUP', 'PRODUCT_SERVICE_LINE_ITEM'],
                    },
                    {
                        identifier: 'PR1',
                        sequence: '32',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['INVOICE_INFORMATION_SUBMIT', 'PRODUCT_SERVICE_SECTION', 'PRODUCT_SERVICE_GROUP', 'PROCEDURE'],
                    },
                    {
                        identifier: 'NTE',
                        sequence: '33',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['INVOICE_INFORMATION_SUBMIT', 'PRODUCT_SERVICE_SECTION', 'PRODUCT_SERVICE_GROUP', 'PROCEDURE'],
                    },
                    {
                        identifier: 'PRT',
                        sequence: '34',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['INVOICE_INFORMATION_SUBMIT', 'PRODUCT_SERVICE_SECTION', 'PRODUCT_SERVICE_GROUP', 'PROCEDURE'],
                    },
                    {
                        identifier: 'ROL',
                        sequence: '35',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['INVOICE_INFORMATION_SUBMIT', 'PRODUCT_SERVICE_SECTION', 'PRODUCT_SERVICE_GROUP', 'PROCEDURE'],
                    },
                    {
                        identifier: 'IPR',
                        sequence: '36',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['INVOICE_INFORMATION_SUBMIT', 'PRODUCT_SERVICE_SECTION', 'PRODUCT_SERVICE_GROUP'],
                    },
                ],
                groups: {
                    INVOICE_INFORMATION_SUBMIT: {
                        sequence: { start: '4', stop: null },
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        subgroup: {
                            PRODUCT_SERVICE_SECTION: {
                                sequence: { start: '11', stop: null },
                                restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 },
                                subgroup: {
                                    PRODUCT_SERVICE_GROUP: {
                                        sequence: { start: '12', stop: '36' },
                                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 },
                                        subgroup: {
                                            PATIENT_INFO: {
                                                sequence: { start: '16', stop: '24' },
                                                restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                                                subgroup: {
                                                    INSURANCE: { sequence: { start: '20', stop: '21' }, restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 }, subgroup: {} },
                                                    DIAGNOSIS: { sequence: { start: '22', stop: '23' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                                                },
                                            },
                                            PRODUCT_SERVICE_LINE_ITEM: { sequence: { start: '25', stop: '31' }, restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 }, subgroup: {} },
                                            PROCEDURE: { sequence: { start: '32', stop: '35' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                                        },
                                    },
                                },
                            },
                        },
                    },
                },
            },
            2.6: {
                sequences: [
                    {},
                    { identifier: 'MSH', sequence: '1', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: false },
                    { identifier: 'SFT', sequence: '2', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: false },
                    { identifier: 'UAC', sequence: '3', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: false },
                    { identifier: 'IVC', sequence: '4', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['INVOICE_INFORMATION'] },
                    { identifier: 'PYE', sequence: '5', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['INVOICE_INFORMATION'] },
                    { identifier: 'CTD', sequence: '6', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['INVOICE_INFORMATION'] },
                    { identifier: 'AUT', sequence: '7', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['INVOICE_INFORMATION'] },
                    { identifier: 'LOC', sequence: '8', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['INVOICE_INFORMATION'] },
                    { identifier: 'ROL', sequence: '9', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['INVOICE_INFORMATION'] },
                    { identifier: 'PSS', sequence: '10', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['INVOICE_INFORMATION', 'PRODUCT_SERVICE_SECTION'] },
                    {
                        identifier: 'PSG',
                        sequence: '11',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['INVOICE_INFORMATION', 'PRODUCT_SERVICE_SECTION', 'PRODUCT_SERVICE_GROUP'],
                    },
                    {
                        identifier: 'LOC',
                        sequence: '12',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['INVOICE_INFORMATION', 'PRODUCT_SERVICE_SECTION', 'PRODUCT_SERVICE_GROUP'],
                    },
                    {
                        identifier: 'ROL',
                        sequence: '13',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['INVOICE_INFORMATION', 'PRODUCT_SERVICE_SECTION', 'PRODUCT_SERVICE_GROUP'],
                    },
                    {
                        identifier: 'PID',
                        sequence: '14',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['INVOICE_INFORMATION', 'PRODUCT_SERVICE_SECTION', 'PRODUCT_SERVICE_GROUP', 'PATIENT_INFO'],
                    },
                    {
                        identifier: 'PV1',
                        sequence: '15',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['INVOICE_INFORMATION', 'PRODUCT_SERVICE_SECTION', 'PRODUCT_SERVICE_GROUP', 'PATIENT_INFO'],
                    },
                    {
                        identifier: 'PV2',
                        sequence: '16',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['INVOICE_INFORMATION', 'PRODUCT_SERVICE_SECTION', 'PRODUCT_SERVICE_GROUP', 'PATIENT_INFO'],
                    },
                    {
                        identifier: 'ACC',
                        sequence: '17',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['INVOICE_INFORMATION', 'PRODUCT_SERVICE_SECTION', 'PRODUCT_SERVICE_GROUP', 'PATIENT_INFO'],
                    },
                    {
                        identifier: 'IN1',
                        sequence: '18',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['INVOICE_INFORMATION', 'PRODUCT_SERVICE_SECTION', 'PRODUCT_SERVICE_GROUP', 'PATIENT_INFO', 'INSURANCE'],
                    },
                    {
                        identifier: 'IN2',
                        sequence: '19',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['INVOICE_INFORMATION', 'PRODUCT_SERVICE_SECTION', 'PRODUCT_SERVICE_GROUP', 'PATIENT_INFO', 'INSURANCE'],
                    },
                    {
                        identifier: 'DG1',
                        sequence: '20',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['INVOICE_INFORMATION', 'PRODUCT_SERVICE_SECTION', 'PRODUCT_SERVICE_GROUP', 'PATIENT_INFO', 'DIAGNOSIS'],
                    },
                    {
                        identifier: 'NTE',
                        sequence: '21',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['INVOICE_INFORMATION', 'PRODUCT_SERVICE_SECTION', 'PRODUCT_SERVICE_GROUP', 'PATIENT_INFO', 'DIAGNOSIS'],
                    },
                    {
                        identifier: 'OBX',
                        sequence: '22',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['INVOICE_INFORMATION', 'PRODUCT_SERVICE_SECTION', 'PRODUCT_SERVICE_GROUP', 'PATIENT_INFO'],
                    },
                    {
                        identifier: 'PSL',
                        sequence: '23',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['INVOICE_INFORMATION', 'PRODUCT_SERVICE_SECTION', 'PRODUCT_SERVICE_GROUP', 'PRODUCT_SERVICE_LINE_ITEM'],
                    },
                    {
                        identifier: 'NTE',
                        sequence: '24',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['INVOICE_INFORMATION', 'PRODUCT_SERVICE_SECTION', 'PRODUCT_SERVICE_GROUP', 'PRODUCT_SERVICE_LINE_ITEM'],
                    },
                    {
                        identifier: 'ADJ',
                        sequence: '25',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['INVOICE_INFORMATION', 'PRODUCT_SERVICE_SECTION', 'PRODUCT_SERVICE_GROUP', 'PRODUCT_SERVICE_LINE_ITEM'],
                    },
                    {
                        identifier: 'AUT',
                        sequence: '26',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['INVOICE_INFORMATION', 'PRODUCT_SERVICE_SECTION', 'PRODUCT_SERVICE_GROUP', 'PRODUCT_SERVICE_LINE_ITEM'],
                    },
                    {
                        identifier: 'LOC',
                        sequence: '27',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['INVOICE_INFORMATION', 'PRODUCT_SERVICE_SECTION', 'PRODUCT_SERVICE_GROUP', 'PRODUCT_SERVICE_LINE_ITEM'],
                    },
                    {
                        identifier: 'ROL',
                        sequence: '28',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['INVOICE_INFORMATION', 'PRODUCT_SERVICE_SECTION', 'PRODUCT_SERVICE_GROUP', 'PRODUCT_SERVICE_LINE_ITEM'],
                    },
                    {
                        identifier: 'PR1',
                        sequence: '29',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['INVOICE_INFORMATION', 'PRODUCT_SERVICE_SECTION', 'PRODUCT_SERVICE_GROUP', 'PROCEDURE'],
                    },
                    {
                        identifier: 'NTE',
                        sequence: '30',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['INVOICE_INFORMATION', 'PRODUCT_SERVICE_SECTION', 'PRODUCT_SERVICE_GROUP', 'PROCEDURE'],
                    },
                    {
                        identifier: 'ROL',
                        sequence: '31',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['INVOICE_INFORMATION', 'PRODUCT_SERVICE_SECTION', 'PRODUCT_SERVICE_GROUP', 'PROCEDURE'],
                    },
                    {
                        identifier: 'IPR',
                        sequence: '32',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['INVOICE_INFORMATION', 'PRODUCT_SERVICE_SECTION', 'PRODUCT_SERVICE_GROUP', 'INVOICE_PROCESSING'],
                    },
                ],
                groups: {
                    INVOICE_INFORMATION: {
                        sequence: { start: '4', stop: null },
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        subgroup: {
                            PRODUCT_SERVICE_SECTION: {
                                sequence: { start: '10', stop: null },
                                restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 },
                                subgroup: {
                                    PRODUCT_SERVICE_GROUP: {
                                        sequence: { start: '11', stop: null },
                                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 },
                                        subgroup: {
                                            PATIENT_INFO: {
                                                sequence: { start: '14', stop: '22' },
                                                restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                                                subgroup: {
                                                    INSURANCE: { sequence: { start: '18', stop: '19' }, restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 }, subgroup: {} },
                                                    DIAGNOSIS: { sequence: { start: '20', stop: '21' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                                                },
                                            },
                                            PRODUCT_SERVICE_LINE_ITEM: { sequence: { start: '23', stop: '28' }, restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 }, subgroup: {} },
                                            PROCEDURE: { sequence: { start: '29', stop: '31' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                                            INVOICE_PROCESSING: { sequence: { start: '32', stop: '32' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                                        },
                                    },
                                },
                            },
                        },
                    },
                },
            },
            2.7: {
                sequences: { ref: '2.6' },
                groups: { ref: '2.6' },
            },
            '2.7.1': {
                sequences: { ref: '2.6' },
                groups: { ref: '2.6' },
            },
        },
        segments: {
            MSH: MSH,
            SFT: SFT,
            UAC: UAC,
            IVC: IVC,
            PYE: PYE,
            CTD: CTD,
            AUT: AUT,
            LOC: LOC,
            PRT: PRT,
            ROL: ROL,
            PSS: PSS,
            PSG: PSG,
            PID: PID,
            PV1: PV1,
            PV2: PV2,
            ACC: ACC,
            IN1: IN1,
            IN2: IN2,
            DG1: DG1,
            NTE: NTE,
            OBX: OBX,
            PSL: PSL,
            ADJ: ADJ,
            PR1: PR1,
            IPR: IPR,
        },
    };

    constructor(message, version = null) {
        super(message, version);
    }
}
