import {
    MSH,
    SFT,
    UAC,
    NTE,
    PID,
    PD1,
    PRT,
    NK1,
    ARV,
    PV1,
    PV2,
    IN1,
    IN2,
    IN3,
    GT1,
    AL1,
    ORC,
    TQ1,
    TQ2,
    OBR,
    TCD,
    CTD,
    DG1,
    OBX,
    SHP,
    PAC,
    SPM,
    SAC,
    FT1,
    CTI,
    BLG,
} from '@healthcare-interoperability/hl7v2-segments';
import { TriggerEvent } from '@healthcare-interoperability/hl7v2-core';

export class OML_O39 extends TriggerEvent {
    static TriggerEvent = 'OML_O39';
    static Structure = {
        versions: {
            2.8: {
                sequences: [
                    {},
                    { identifier: 'MSH', sequence: '1', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: false },
                    { identifier: 'SFT', sequence: '2', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: false },
                    { identifier: 'UAC', sequence: '3', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: false },
                    { identifier: 'NTE', sequence: '4', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: false },
                    { identifier: 'PID', sequence: '5', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT'] },
                    { identifier: 'PD1', sequence: '6', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT'] },
                    { identifier: 'PRT', sequence: '7', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATIENT'] },
                    { identifier: 'NTE', sequence: '8', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATIENT'] },
                    { identifier: 'NK1', sequence: '9', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATIENT'] },
                    { identifier: 'ARV', sequence: '10', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATIENT'] },
                    { identifier: 'PV1', sequence: '11', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT', 'PATIENT_VISIT'] },
                    { identifier: 'PV2', sequence: '12', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT', 'PATIENT_VISIT'] },
                    { identifier: 'PRT', sequence: '13', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATIENT', 'PATIENT_VISIT'] },
                    { identifier: 'IN1', sequence: '14', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT', 'INSURANCE'] },
                    { identifier: 'IN2', sequence: '15', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT', 'INSURANCE'] },
                    { identifier: 'IN3', sequence: '16', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT', 'INSURANCE'] },
                    { identifier: 'GT1', sequence: '17', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT'] },
                    { identifier: 'AL1', sequence: '18', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATIENT'] },
                    { identifier: 'ORC', sequence: '19', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['ORDER'] },
                    { identifier: 'PRT', sequence: '20', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['ORDER'] },
                    { identifier: 'TQ1', sequence: '21', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['ORDER', 'TIMING'] },
                    { identifier: 'TQ2', sequence: '22', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['ORDER', 'TIMING'] },
                    { identifier: 'OBR', sequence: '23', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['ORDER', 'OBSERVATION_REQUEST'] },
                    { identifier: 'TCD', sequence: '24', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['ORDER', 'OBSERVATION_REQUEST'] },
                    { identifier: 'NTE', sequence: '25', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['ORDER', 'OBSERVATION_REQUEST'] },
                    { identifier: 'PRT', sequence: '26', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['ORDER', 'OBSERVATION_REQUEST'] },
                    { identifier: 'CTD', sequence: '27', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['ORDER', 'OBSERVATION_REQUEST'] },
                    { identifier: 'DG1', sequence: '28', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['ORDER', 'OBSERVATION_REQUEST'] },
                    { identifier: 'OBX', sequence: '29', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['ORDER', 'OBSERVATION_REQUEST', 'OBSERVATION'] },
                    { identifier: 'PRT', sequence: '30', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['ORDER', 'OBSERVATION_REQUEST', 'OBSERVATION'] },
                    { identifier: 'TCD', sequence: '31', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['ORDER', 'OBSERVATION_REQUEST', 'OBSERVATION'] },
                    { identifier: 'NTE', sequence: '32', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['ORDER', 'OBSERVATION_REQUEST', 'OBSERVATION'] },
                    {
                        identifier: 'SHP',
                        sequence: '33',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['ORDER', 'OBSERVATION_REQUEST', 'SPECIMEN_SHIPMENT'],
                    },
                    {
                        identifier: 'OBX',
                        sequence: '34',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['ORDER', 'OBSERVATION_REQUEST', 'SPECIMEN_SHIPMENT', 'SHIPMENT_OBSERVATION'],
                    },
                    {
                        identifier: 'PRT',
                        sequence: '35',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['ORDER', 'OBSERVATION_REQUEST', 'SPECIMEN_SHIPMENT', 'SHIPMENT_OBSERVATION'],
                    },
                    {
                        identifier: 'PAC',
                        sequence: '36',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['ORDER', 'OBSERVATION_REQUEST', 'SPECIMEN_SHIPMENT', 'PACKAGE'],
                    },
                    {
                        identifier: 'SPM',
                        sequence: '37',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['ORDER', 'OBSERVATION_REQUEST', 'SPECIMEN_SHIPMENT', 'PACKAGE', 'SPECIMEN_IN_PACKAGE'],
                    },
                    {
                        identifier: 'OBX',
                        sequence: '38',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['ORDER', 'OBSERVATION_REQUEST', 'SPECIMEN_SHIPMENT', 'PACKAGE', 'SPECIMEN_IN_PACKAGE', 'SPECIMEN_OBSERVATION'],
                    },
                    {
                        identifier: 'PRT',
                        sequence: '39',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['ORDER', 'OBSERVATION_REQUEST', 'SPECIMEN_SHIPMENT', 'PACKAGE', 'SPECIMEN_IN_PACKAGE', 'SPECIMEN_OBSERVATION'],
                    },
                    {
                        identifier: 'SAC',
                        sequence: '40',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['ORDER', 'OBSERVATION_REQUEST', 'SPECIMEN_SHIPMENT', 'PACKAGE', 'SPECIMEN_IN_PACKAGE', 'SPECIMEN_CONTAINER_IN_PACKAGE'],
                    },
                    {
                        identifier: 'OBX',
                        sequence: '41',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['ORDER', 'OBSERVATION_REQUEST', 'SPECIMEN_SHIPMENT', 'PACKAGE', 'SPECIMEN_IN_PACKAGE', 'SPECIMEN_CONTAINER_IN_PACKAGE', 'CONTAINER_OBSERVATION'],
                    },
                    {
                        identifier: 'PRT',
                        sequence: '42',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['ORDER', 'OBSERVATION_REQUEST', 'SPECIMEN_SHIPMENT', 'PACKAGE', 'SPECIMEN_IN_PACKAGE', 'SPECIMEN_CONTAINER_IN_PACKAGE', 'CONTAINER_OBSERVATION'],
                    },
                    { identifier: 'FT1', sequence: '43', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['ORDER'] },
                    { identifier: 'CTI', sequence: '44', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['ORDER'] },
                    { identifier: 'BLG', sequence: '45', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['ORDER'] },
                ],
                groups: {
                    PATIENT: {
                        sequence: { start: '5', stop: '18' },
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                        subgroup: {
                            PATIENT_VISIT: { sequence: { start: '11', stop: '13' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, subgroup: {} },
                            INSURANCE: { sequence: { start: '14', stop: '16' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                        },
                    },
                    ORDER: {
                        sequence: { start: '19', stop: '45' },
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 },
                        subgroup: {
                            TIMING: { sequence: { start: '21', stop: '22' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                            OBSERVATION_REQUEST: {
                                sequence: { start: '23', stop: null },
                                restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                                subgroup: {
                                    OBSERVATION: { sequence: { start: '29', stop: '32' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                                    SPECIMEN_SHIPMENT: {
                                        sequence: { start: '33', stop: null },
                                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                                        subgroup: {
                                            SHIPMENT_OBSERVATION: { sequence: { start: '34', stop: '35' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                                            PACKAGE: {
                                                sequence: { start: '36', stop: null },
                                                restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 },
                                                subgroup: {
                                                    SPECIMEN_IN_PACKAGE: {
                                                        sequence: { start: '37', stop: null },
                                                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                                                        subgroup: {
                                                            SPECIMEN_OBSERVATION: {
                                                                sequence: { start: '38', stop: '39' },
                                                                restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                                                                subgroup: {},
                                                            },
                                                            SPECIMEN_CONTAINER_IN_PACKAGE: {
                                                                sequence: { start: '40', stop: null },
                                                                restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                                                                subgroup: {
                                                                    CONTAINER_OBSERVATION: {
                                                                        sequence: { start: '41', stop: '42' },
                                                                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                                                                        subgroup: {},
                                                                    },
                                                                },
                                                            },
                                                        },
                                                    },
                                                },
                                            },
                                        },
                                    },
                                },
                            },
                        },
                    },
                },
            },
            2.7: {
                sequences: [
                    {},
                    { identifier: 'MSH', sequence: '1', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: false },
                    { identifier: 'SFT', sequence: '2', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: false },
                    { identifier: 'UAC', sequence: '3', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: false },
                    { identifier: 'NTE', sequence: '4', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: false },
                    { identifier: 'PID', sequence: '5', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT'] },
                    { identifier: 'PD1', sequence: '6', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT'] },
                    { identifier: 'PRT', sequence: '7', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATIENT'] },
                    { identifier: 'NTE', sequence: '8', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATIENT'] },
                    { identifier: 'NK1', sequence: '9', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATIENT'] },
                    { identifier: 'PV1', sequence: '10', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT', 'PATIENT_VISIT'] },
                    { identifier: 'PV2', sequence: '11', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT', 'PATIENT_VISIT'] },
                    { identifier: 'PRT', sequence: '12', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATIENT', 'PATIENT_VISIT'] },
                    { identifier: 'IN1', sequence: '13', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT', 'INSURANCE'] },
                    { identifier: 'IN2', sequence: '14', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT', 'INSURANCE'] },
                    { identifier: 'IN3', sequence: '15', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT', 'INSURANCE'] },
                    { identifier: 'GT1', sequence: '16', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT'] },
                    { identifier: 'AL1', sequence: '17', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATIENT'] },
                    { identifier: 'ORC', sequence: '18', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['ORDER'] },
                    { identifier: 'PRT', sequence: '19', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['ORDER'] },
                    { identifier: 'TQ1', sequence: '20', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['ORDER', 'TIMING'] },
                    { identifier: 'TQ2', sequence: '21', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['ORDER', 'TIMING'] },
                    { identifier: 'OBR', sequence: '22', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['ORDER', 'OBSERVATION_REQUEST'] },
                    { identifier: 'TCD', sequence: '23', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['ORDER', 'OBSERVATION_REQUEST'] },
                    { identifier: 'NTE', sequence: '24', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['ORDER', 'OBSERVATION_REQUEST'] },
                    { identifier: 'PRT', sequence: '25', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['ORDER', 'OBSERVATION_REQUEST'] },
                    { identifier: 'CTD', sequence: '26', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['ORDER', 'OBSERVATION_REQUEST'] },
                    { identifier: 'DG1', sequence: '27', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['ORDER', 'OBSERVATION_REQUEST'] },
                    { identifier: 'OBX', sequence: '28', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['ORDER', 'OBSERVATION_REQUEST', 'OBSERVATION'] },
                    { identifier: 'PRT', sequence: '29', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['ORDER', 'OBSERVATION_REQUEST', 'OBSERVATION'] },
                    { identifier: 'TCD', sequence: '30', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['ORDER', 'OBSERVATION_REQUEST', 'OBSERVATION'] },
                    { identifier: 'NTE', sequence: '31', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['ORDER', 'OBSERVATION_REQUEST', 'OBSERVATION'] },
                    {
                        identifier: 'SHP',
                        sequence: '32',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['ORDER', 'OBSERVATION_REQUEST', 'SPECIMEN_SHIPMENT'],
                    },
                    {
                        identifier: 'OBX',
                        sequence: '33',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['ORDER', 'OBSERVATION_REQUEST', 'SPECIMEN_SHIPMENT', 'SHIPMENT_OBSERVATION'],
                    },
                    {
                        identifier: 'PRT',
                        sequence: '34',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['ORDER', 'OBSERVATION_REQUEST', 'SPECIMEN_SHIPMENT', 'SHIPMENT_OBSERVATION'],
                    },
                    {
                        identifier: 'PAC',
                        sequence: '35',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['ORDER', 'OBSERVATION_REQUEST', 'SPECIMEN_SHIPMENT', 'PACKAGE'],
                    },
                    {
                        identifier: 'SPM',
                        sequence: '36',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['ORDER', 'OBSERVATION_REQUEST', 'SPECIMEN_SHIPMENT', 'PACKAGE', 'SPECIMEN_IN_PACKAGE'],
                    },
                    {
                        identifier: 'OBX',
                        sequence: '37',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['ORDER', 'OBSERVATION_REQUEST', 'SPECIMEN_SHIPMENT', 'PACKAGE', 'SPECIMEN_IN_PACKAGE', 'SPECIMEN_OBSERVATION'],
                    },
                    {
                        identifier: 'PRT',
                        sequence: '38',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['ORDER', 'OBSERVATION_REQUEST', 'SPECIMEN_SHIPMENT', 'PACKAGE', 'SPECIMEN_IN_PACKAGE', 'SPECIMEN_OBSERVATION'],
                    },
                    {
                        identifier: 'SAC',
                        sequence: '39',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['ORDER', 'OBSERVATION_REQUEST', 'SPECIMEN_SHIPMENT', 'PACKAGE', 'SPECIMEN_IN_PACKAGE', 'SPECIMEN_CONTAINER_IN_PACKAGE'],
                    },
                    {
                        identifier: 'OBX',
                        sequence: '40',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['ORDER', 'OBSERVATION_REQUEST', 'SPECIMEN_SHIPMENT', 'PACKAGE', 'SPECIMEN_IN_PACKAGE', 'SPECIMEN_CONTAINER_IN_PACKAGE', 'CONTAINER_OBSERVATION'],
                    },
                    {
                        identifier: 'PRT',
                        sequence: '41',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['ORDER', 'OBSERVATION_REQUEST', 'SPECIMEN_SHIPMENT', 'PACKAGE', 'SPECIMEN_IN_PACKAGE', 'SPECIMEN_CONTAINER_IN_PACKAGE', 'CONTAINER_OBSERVATION'],
                    },
                    { identifier: 'FT1', sequence: '42', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['ORDER'] },
                    { identifier: 'CTI', sequence: '43', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['ORDER'] },
                    { identifier: 'BLG', sequence: '44', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['ORDER'] },
                ],
                groups: {
                    PATIENT: {
                        sequence: { start: '5', stop: '17' },
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                        subgroup: {
                            PATIENT_VISIT: { sequence: { start: '10', stop: '12' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, subgroup: {} },
                            INSURANCE: { sequence: { start: '13', stop: '15' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                        },
                    },
                    ORDER: {
                        sequence: { start: '18', stop: '44' },
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 },
                        subgroup: {
                            TIMING: { sequence: { start: '20', stop: '21' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                            OBSERVATION_REQUEST: {
                                sequence: { start: '22', stop: null },
                                restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                                subgroup: {
                                    OBSERVATION: { sequence: { start: '28', stop: '31' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                                    SPECIMEN_SHIPMENT: {
                                        sequence: { start: '32', stop: null },
                                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                                        subgroup: {
                                            SHIPMENT_OBSERVATION: { sequence: { start: '33', stop: '34' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                                            PACKAGE: {
                                                sequence: { start: '35', stop: null },
                                                restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 },
                                                subgroup: {
                                                    SPECIMEN_IN_PACKAGE: {
                                                        sequence: { start: '36', stop: null },
                                                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                                                        subgroup: {
                                                            SPECIMEN_OBSERVATION: {
                                                                sequence: { start: '37', stop: '38' },
                                                                restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                                                                subgroup: {},
                                                            },
                                                            SPECIMEN_CONTAINER_IN_PACKAGE: {
                                                                sequence: { start: '39', stop: null },
                                                                restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                                                                subgroup: {
                                                                    CONTAINER_OBSERVATION: {
                                                                        sequence: { start: '40', stop: '41' },
                                                                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                                                                        subgroup: {},
                                                                    },
                                                                },
                                                            },
                                                        },
                                                    },
                                                },
                                            },
                                        },
                                    },
                                },
                            },
                        },
                    },
                },
            },
            '2.7.1': {
                sequences: { ref: '2.7' },
                groups: { ref: '2.7' },
            },
        },
        segments: {
            MSH: MSH,
            SFT: SFT,
            UAC: UAC,
            NTE: NTE,
            PID: PID,
            PD1: PD1,
            PRT: PRT,
            NK1: NK1,
            ARV: ARV,
            PV1: PV1,
            PV2: PV2,
            IN1: IN1,
            IN2: IN2,
            IN3: IN3,
            GT1: GT1,
            AL1: AL1,
            ORC: ORC,
            TQ1: TQ1,
            TQ2: TQ2,
            OBR: OBR,
            TCD: TCD,
            CTD: CTD,
            DG1: DG1,
            OBX: OBX,
            SHP: SHP,
            PAC: PAC,
            SPM: SPM,
            SAC: SAC,
            FT1: FT1,
            CTI: CTI,
            BLG: BLG,
        },
    };

    constructor(message, version = null) {
        super(message, version);
    }
}
