import {
    MSH,
    SFT,
    UAC,
    NTE,
    PID,
    PD1,
    PRT,
    NK1,
    ARV,
    PV1,
    PV2,
    IN1,
    IN2,
    IN3,
    GT1,
    AL1,
    SPM,
    OBX,
    SAC,
    ORC,
    TQ1,
    TQ2,
    OBR,
    TCD,
    DG1,
    FT1,
    CTI,
    BLG,
    ROL,
} from '@healthcare-interoperability/hl7v2-segments';
import { TriggerEvent } from '@healthcare-interoperability/hl7v2-core';

export class OML_O33 extends TriggerEvent {
    static TriggerEvent = 'OML_O33';
    static Structure = {
        versions: {
            2.8: {
                sequences: [
                    {},
                    { identifier: 'MSH', sequence: '1', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: false },
                    { identifier: 'SFT', sequence: '2', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: false },
                    { identifier: 'UAC', sequence: '3', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: false },
                    { identifier: 'NTE', sequence: '4', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: false },
                    { identifier: 'PID', sequence: '5', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT'] },
                    { identifier: 'PD1', sequence: '6', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT'] },
                    { identifier: 'PRT', sequence: '7', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATIENT'] },
                    { identifier: 'NTE', sequence: '8', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATIENT'] },
                    { identifier: 'NK1', sequence: '9', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATIENT'] },
                    { identifier: 'ARV', sequence: '10', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATIENT'] },
                    { identifier: 'PV1', sequence: '11', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT', 'PATIENT_VISIT'] },
                    { identifier: 'PV2', sequence: '12', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT', 'PATIENT_VISIT'] },
                    { identifier: 'PRT', sequence: '13', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATIENT', 'PATIENT_VISIT'] },
                    { identifier: 'IN1', sequence: '14', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT', 'INSURANCE'] },
                    { identifier: 'IN2', sequence: '15', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT', 'INSURANCE'] },
                    { identifier: 'IN3', sequence: '16', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT', 'INSURANCE'] },
                    { identifier: 'GT1', sequence: '17', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT'] },
                    { identifier: 'AL1', sequence: '18', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATIENT'] },
                    { identifier: 'SPM', sequence: '19', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['SPECIMEN'] },
                    { identifier: 'OBX', sequence: '20', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['SPECIMEN', 'SPECIMEN_OBSERVATION'] },
                    { identifier: 'PRT', sequence: '21', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['SPECIMEN', 'SPECIMEN_OBSERVATION'] },
                    { identifier: 'SAC', sequence: '22', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['SPECIMEN'] },
                    { identifier: 'ORC', sequence: '23', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['SPECIMEN', 'ORDER'] },
                    { identifier: 'PRT', sequence: '24', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['SPECIMEN', 'ORDER'] },
                    { identifier: 'TQ1', sequence: '25', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['SPECIMEN', 'ORDER', 'TIMING'] },
                    { identifier: 'TQ2', sequence: '26', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['SPECIMEN', 'ORDER', 'TIMING'] },
                    { identifier: 'OBR', sequence: '27', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['SPECIMEN', 'ORDER', 'OBSERVATION_REQUEST'] },
                    { identifier: 'TCD', sequence: '28', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['SPECIMEN', 'ORDER', 'OBSERVATION_REQUEST'] },
                    { identifier: 'NTE', sequence: '29', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['SPECIMEN', 'ORDER', 'OBSERVATION_REQUEST'] },
                    { identifier: 'PRT', sequence: '30', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['SPECIMEN', 'ORDER', 'OBSERVATION_REQUEST'] },
                    { identifier: 'DG1', sequence: '31', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['SPECIMEN', 'ORDER', 'OBSERVATION_REQUEST'] },
                    {
                        identifier: 'OBX',
                        sequence: '32',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['SPECIMEN', 'ORDER', 'OBSERVATION_REQUEST', 'OBSERVATION'],
                    },
                    {
                        identifier: 'PRT',
                        sequence: '33',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['SPECIMEN', 'ORDER', 'OBSERVATION_REQUEST', 'OBSERVATION'],
                    },
                    {
                        identifier: 'TCD',
                        sequence: '34',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['SPECIMEN', 'ORDER', 'OBSERVATION_REQUEST', 'OBSERVATION'],
                    },
                    {
                        identifier: 'NTE',
                        sequence: '35',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['SPECIMEN', 'ORDER', 'OBSERVATION_REQUEST', 'OBSERVATION'],
                    },
                    {
                        identifier: 'PID',
                        sequence: '36',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['SPECIMEN', 'ORDER', 'OBSERVATION_REQUEST', 'PRIOR_RESULT', 'PATIENT_PRIOR'],
                    },
                    {
                        identifier: 'PD1',
                        sequence: '37',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['SPECIMEN', 'ORDER', 'OBSERVATION_REQUEST', 'PRIOR_RESULT', 'PATIENT_PRIOR'],
                    },
                    {
                        identifier: 'PRT',
                        sequence: '38',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['SPECIMEN', 'ORDER', 'OBSERVATION_REQUEST', 'PRIOR_RESULT', 'PATIENT_PRIOR'],
                    },
                    {
                        identifier: 'ARV',
                        sequence: '39',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['SPECIMEN', 'ORDER', 'OBSERVATION_REQUEST', 'PRIOR_RESULT', 'PATIENT_PRIOR'],
                    },
                    {
                        identifier: 'PV1',
                        sequence: '40',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['SPECIMEN', 'ORDER', 'OBSERVATION_REQUEST', 'PRIOR_RESULT', 'PATIENT_VISIT_PRIOR'],
                    },
                    {
                        identifier: 'PV2',
                        sequence: '41',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['SPECIMEN', 'ORDER', 'OBSERVATION_REQUEST', 'PRIOR_RESULT', 'PATIENT_VISIT_PRIOR'],
                    },
                    {
                        identifier: 'PRT',
                        sequence: '42',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['SPECIMEN', 'ORDER', 'OBSERVATION_REQUEST', 'PRIOR_RESULT', 'PATIENT_VISIT_PRIOR'],
                    },
                    {
                        identifier: 'AL1',
                        sequence: '43',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['SPECIMEN', 'ORDER', 'OBSERVATION_REQUEST', 'PRIOR_RESULT'],
                    },
                    {
                        identifier: 'ORC',
                        sequence: '44',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['SPECIMEN', 'ORDER', 'OBSERVATION_REQUEST', 'PRIOR_RESULT', 'ORDER_PRIOR'],
                    },
                    {
                        identifier: 'OBR',
                        sequence: '45',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['SPECIMEN', 'ORDER', 'OBSERVATION_REQUEST', 'PRIOR_RESULT', 'ORDER_PRIOR'],
                    },
                    {
                        identifier: 'NTE',
                        sequence: '46',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['SPECIMEN', 'ORDER', 'OBSERVATION_REQUEST', 'PRIOR_RESULT', 'ORDER_PRIOR'],
                    },
                    {
                        identifier: 'PRT',
                        sequence: '47',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['SPECIMEN', 'ORDER', 'OBSERVATION_REQUEST', 'PRIOR_RESULT', 'ORDER_PRIOR'],
                    },
                    {
                        identifier: 'TQ1',
                        sequence: '48',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['SPECIMEN', 'ORDER', 'OBSERVATION_REQUEST', 'PRIOR_RESULT', 'ORDER_PRIOR', 'TIMING_PRIOR'],
                    },
                    {
                        identifier: 'TQ2',
                        sequence: '49',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['SPECIMEN', 'ORDER', 'OBSERVATION_REQUEST', 'PRIOR_RESULT', 'ORDER_PRIOR', 'TIMING_PRIOR'],
                    },
                    {
                        identifier: 'OBX',
                        sequence: '50',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['SPECIMEN', 'ORDER', 'OBSERVATION_REQUEST', 'PRIOR_RESULT', 'ORDER_PRIOR', 'OBSERVATION_PRIOR'],
                    },
                    {
                        identifier: 'PRT',
                        sequence: '51',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['SPECIMEN', 'ORDER', 'OBSERVATION_REQUEST', 'PRIOR_RESULT', 'ORDER_PRIOR', 'OBSERVATION_PRIOR'],
                    },
                    {
                        identifier: 'NTE',
                        sequence: '52',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['SPECIMEN', 'ORDER', 'OBSERVATION_REQUEST', 'PRIOR_RESULT', 'ORDER_PRIOR', 'OBSERVATION_PRIOR'],
                    },
                    { identifier: 'FT1', sequence: '53', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['SPECIMEN', 'ORDER'] },
                    { identifier: 'CTI', sequence: '54', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['SPECIMEN', 'ORDER'] },
                    { identifier: 'BLG', sequence: '55', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['SPECIMEN', 'ORDER'] },
                ],
                groups: {
                    PATIENT: {
                        sequence: { start: '5', stop: '18' },
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                        subgroup: {
                            PATIENT_VISIT: { sequence: { start: '11', stop: '13' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, subgroup: {} },
                            INSURANCE: { sequence: { start: '14', stop: '16' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                        },
                    },
                    SPECIMEN: {
                        sequence: { start: '19', stop: null },
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 },
                        subgroup: {
                            SPECIMEN_OBSERVATION: { sequence: { start: '20', stop: '21' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                            ORDER: {
                                sequence: { start: '23', stop: '55' },
                                restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 },
                                subgroup: {
                                    TIMING: { sequence: { start: '25', stop: '26' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                                    OBSERVATION_REQUEST: {
                                        sequence: { start: '27', stop: null },
                                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                                        subgroup: {
                                            OBSERVATION: { sequence: { start: '32', stop: '35' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                                            PRIOR_RESULT: {
                                                sequence: { start: null, stop: null },
                                                restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                                                subgroup: {
                                                    PATIENT_PRIOR: { sequence: { start: '36', stop: '39' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, subgroup: {} },
                                                    PATIENT_VISIT_PRIOR: { sequence: { start: '40', stop: '42' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, subgroup: {} },
                                                    ORDER_PRIOR: {
                                                        sequence: { start: '44', stop: null },
                                                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 },
                                                        subgroup: {
                                                            TIMING_PRIOR: { sequence: { start: '48', stop: '49' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                                                            OBSERVATION_PRIOR: {
                                                                sequence: { start: '50', stop: '52' },
                                                                restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 },
                                                                subgroup: {},
                                                            },
                                                        },
                                                    },
                                                },
                                            },
                                        },
                                    },
                                },
                            },
                        },
                    },
                },
            },
            2.5: {
                sequences: [
                    {},
                    { identifier: 'MSH', sequence: '1', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: false },
                    { identifier: 'SFT', sequence: '2', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: false },
                    { identifier: 'NTE', sequence: '3', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: false },
                    { identifier: 'PID', sequence: '4', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT'] },
                    { identifier: 'PD1', sequence: '5', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT'] },
                    { identifier: 'NTE', sequence: '6', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATIENT'] },
                    { identifier: 'NK1', sequence: '7', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATIENT'] },
                    { identifier: 'PV1', sequence: '8', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT', 'PATIENT_VISIT'] },
                    { identifier: 'PV2', sequence: '9', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT', 'PATIENT_VISIT'] },
                    { identifier: 'IN1', sequence: '10', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT', 'INSURANCE'] },
                    { identifier: 'IN2', sequence: '11', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT', 'INSURANCE'] },
                    { identifier: 'IN3', sequence: '12', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT', 'INSURANCE'] },
                    { identifier: 'GT1', sequence: '13', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT'] },
                    { identifier: 'AL1', sequence: '14', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATIENT'] },
                    { identifier: 'SPM', sequence: '15', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['SPECIMEN'] },
                    { identifier: 'OBX', sequence: '16', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['SPECIMEN'] },
                    { identifier: 'SAC', sequence: '17', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['SPECIMEN'] },
                    { identifier: 'ORC', sequence: '18', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['SPECIMEN', 'ORDER'] },
                    { identifier: 'TQ1', sequence: '19', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['SPECIMEN', 'ORDER', 'TIIMING'] },
                    { identifier: 'TQ2', sequence: '20', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['SPECIMEN', 'ORDER', 'TIIMING'] },
                    { identifier: 'OBR', sequence: '21', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['SPECIMEN', 'ORDER', 'OBSERVATION_REQUEST'] },
                    { identifier: 'TCD', sequence: '22', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['SPECIMEN', 'ORDER', 'OBSERVATION_REQUEST'] },
                    { identifier: 'NTE', sequence: '23', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['SPECIMEN', 'ORDER', 'OBSERVATION_REQUEST'] },
                    { identifier: 'DG1', sequence: '24', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['SPECIMEN', 'ORDER', 'OBSERVATION_REQUEST'] },
                    {
                        identifier: 'OBX',
                        sequence: '25',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['SPECIMEN', 'ORDER', 'OBSERVATION_REQUEST', 'OBSERVATION'],
                    },
                    {
                        identifier: 'TCD',
                        sequence: '26',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['SPECIMEN', 'ORDER', 'OBSERVATION_REQUEST', 'OBSERVATION'],
                    },
                    {
                        identifier: 'NTE',
                        sequence: '27',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['SPECIMEN', 'ORDER', 'OBSERVATION_REQUEST', 'OBSERVATION'],
                    },
                    {
                        identifier: 'PID',
                        sequence: '28',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['SPECIMEN', 'ORDER', 'OBSERVATION_REQUEST', 'PRIOR_RESULT', 'PATIENT_PRIOR'],
                    },
                    {
                        identifier: 'PD1',
                        sequence: '29',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['SPECIMEN', 'ORDER', 'OBSERVATION_REQUEST', 'PRIOR_RESULT', 'PATIENT_PRIOR'],
                    },
                    {
                        identifier: 'PV1',
                        sequence: '30',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['SPECIMEN', 'ORDER', 'OBSERVATION_REQUEST', 'PRIOR_RESULT', 'PATIENT_VISIT_PRIOR'],
                    },
                    {
                        identifier: 'PV2',
                        sequence: '31',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['SPECIMEN', 'ORDER', 'OBSERVATION_REQUEST', 'PRIOR_RESULT', 'PATIENT_VISIT_PRIOR'],
                    },
                    {
                        identifier: 'AL1',
                        sequence: '32',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['SPECIMEN', 'ORDER', 'OBSERVATION_REQUEST', 'PRIOR_RESULT'],
                    },
                    {
                        identifier: 'ORC',
                        sequence: '33',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['SPECIMEN', 'ORDER', 'OBSERVATION_REQUEST', 'PRIOR_RESULT', 'ORDER_PRIOR'],
                    },
                    {
                        identifier: 'OBR',
                        sequence: '34',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['SPECIMEN', 'ORDER', 'OBSERVATION_REQUEST', 'PRIOR_RESULT', 'ORDER_PRIOR'],
                    },
                    {
                        identifier: 'NTE',
                        sequence: '35',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['SPECIMEN', 'ORDER', 'OBSERVATION_REQUEST', 'PRIOR_RESULT', 'ORDER_PRIOR'],
                    },
                    {
                        identifier: 'TQ1',
                        sequence: '36',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['SPECIMEN', 'ORDER', 'OBSERVATION_REQUEST', 'PRIOR_RESULT', 'ORDER_PRIOR', 'TIMING_PRIOR'],
                    },
                    {
                        identifier: 'TQ2',
                        sequence: '37',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['SPECIMEN', 'ORDER', 'OBSERVATION_REQUEST', 'PRIOR_RESULT', 'ORDER_PRIOR', 'TIMING_PRIOR'],
                    },
                    {
                        identifier: 'OBX',
                        sequence: '38',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['SPECIMEN', 'ORDER', 'OBSERVATION_REQUEST', 'PRIOR_RESULT', 'ORDER_PRIOR', 'OBSERVATION_PRIOR'],
                    },
                    {
                        identifier: 'NTE',
                        sequence: '39',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['SPECIMEN', 'ORDER', 'OBSERVATION_REQUEST', 'PRIOR_RESULT', 'ORDER_PRIOR', 'OBSERVATION_PRIOR'],
                    },
                    { identifier: 'FT1', sequence: '40', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['SPECIMEN', 'ORDER'] },
                    { identifier: 'CTI', sequence: '41', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['SPECIMEN', 'ORDER'] },
                    { identifier: 'BLG', sequence: '42', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['SPECIMEN', 'ORDER'] },
                ],
                groups: {
                    PATIENT: {
                        sequence: { start: '4', stop: '14' },
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                        subgroup: {
                            PATIENT_VISIT: { sequence: { start: '8', stop: '9' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, subgroup: {} },
                            INSURANCE: { sequence: { start: '10', stop: '12' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                        },
                    },
                    SPECIMEN: {
                        sequence: { start: '15', stop: null },
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 },
                        subgroup: {
                            ORDER: {
                                sequence: { start: '18', stop: '42' },
                                restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 },
                                subgroup: {
                                    TIIMING: { sequence: { start: '19', stop: '20' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                                    OBSERVATION_REQUEST: {
                                        sequence: { start: '21', stop: null },
                                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                                        subgroup: {
                                            OBSERVATION: { sequence: { start: '25', stop: '27' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                                            PRIOR_RESULT: {
                                                sequence: { start: null, stop: null },
                                                restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                                                subgroup: {
                                                    PATIENT_PRIOR: { sequence: { start: '28', stop: '29' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, subgroup: {} },
                                                    PATIENT_VISIT_PRIOR: { sequence: { start: '30', stop: '31' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, subgroup: {} },
                                                    ORDER_PRIOR: {
                                                        sequence: { start: '33', stop: null },
                                                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 },
                                                        subgroup: {
                                                            TIMING_PRIOR: { sequence: { start: '36', stop: '37' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                                                            OBSERVATION_PRIOR: {
                                                                sequence: { start: '38', stop: '39' },
                                                                restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 },
                                                                subgroup: {},
                                                            },
                                                        },
                                                    },
                                                },
                                            },
                                        },
                                    },
                                },
                            },
                        },
                    },
                },
            },
            '2.5.1': {
                sequences: { ref: '2.5' },
                groups: { ref: '2.5' },
            },
            2.6: {
                sequences: [
                    {},
                    { identifier: 'MSH', sequence: '1', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: false },
                    { identifier: 'SFT', sequence: '2', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: false },
                    { identifier: 'UAC', sequence: '3', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: false },
                    { identifier: 'NTE', sequence: '4', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: false },
                    { identifier: 'PID', sequence: '5', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT'] },
                    { identifier: 'PD1', sequence: '6', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT'] },
                    { identifier: 'NTE', sequence: '7', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATIENT'] },
                    { identifier: 'NK1', sequence: '8', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATIENT'] },
                    { identifier: 'PV1', sequence: '9', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT', 'PATIENT_VISIT'] },
                    { identifier: 'PV2', sequence: '10', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT', 'PATIENT_VISIT'] },
                    { identifier: 'IN1', sequence: '11', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT', 'INSURANCE'] },
                    { identifier: 'IN2', sequence: '12', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT', 'INSURANCE'] },
                    { identifier: 'IN3', sequence: '13', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT', 'INSURANCE'] },
                    { identifier: 'GT1', sequence: '14', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT'] },
                    { identifier: 'AL1', sequence: '15', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATIENT'] },
                    { identifier: 'SPM', sequence: '16', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['SPECIMEN'] },
                    { identifier: 'OBX', sequence: '17', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['SPECIMEN'] },
                    { identifier: 'SAC', sequence: '18', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['SPECIMEN'] },
                    { identifier: 'ORC', sequence: '19', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['SPECIMEN', 'ORDER'] },
                    { identifier: 'TQ1', sequence: '20', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['SPECIMEN', 'ORDER', 'TIMING'] },
                    { identifier: 'TQ2', sequence: '21', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['SPECIMEN', 'ORDER', 'TIMING'] },
                    { identifier: 'OBR', sequence: '22', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['SPECIMEN', 'ORDER', 'OBSERVATION_REQUEST'] },
                    { identifier: 'TCD', sequence: '23', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['SPECIMEN', 'ORDER', 'OBSERVATION_REQUEST'] },
                    { identifier: 'NTE', sequence: '24', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['SPECIMEN', 'ORDER', 'OBSERVATION_REQUEST'] },
                    { identifier: 'ROL', sequence: '25', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['SPECIMEN', 'ORDER', 'OBSERVATION_REQUEST'] },
                    { identifier: 'DG1', sequence: '26', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['SPECIMEN', 'ORDER', 'OBSERVATION_REQUEST'] },
                    {
                        identifier: 'OBX',
                        sequence: '27',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['SPECIMEN', 'ORDER', 'OBSERVATION_REQUEST', 'OBSERVATION'],
                    },
                    {
                        identifier: 'TCD',
                        sequence: '28',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['SPECIMEN', 'ORDER', 'OBSERVATION_REQUEST', 'OBSERVATION'],
                    },
                    {
                        identifier: 'NTE',
                        sequence: '29',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['SPECIMEN', 'ORDER', 'OBSERVATION_REQUEST', 'OBSERVATION'],
                    },
                    {
                        identifier: 'PID',
                        sequence: '30',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['SPECIMEN', 'ORDER', 'OBSERVATION_REQUEST', 'PRIOR_RESULT', 'PATIENT_PRIOR'],
                    },
                    {
                        identifier: 'PD1',
                        sequence: '31',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['SPECIMEN', 'ORDER', 'OBSERVATION_REQUEST', 'PRIOR_RESULT', 'PATIENT_PRIOR'],
                    },
                    {
                        identifier: 'PV1',
                        sequence: '32',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['SPECIMEN', 'ORDER', 'OBSERVATION_REQUEST', 'PRIOR_RESULT', 'PATIENT_VISIT_PRIOR'],
                    },
                    {
                        identifier: 'PV2',
                        sequence: '33',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['SPECIMEN', 'ORDER', 'OBSERVATION_REQUEST', 'PRIOR_RESULT', 'PATIENT_VISIT_PRIOR'],
                    },
                    {
                        identifier: 'AL1',
                        sequence: '34',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['SPECIMEN', 'ORDER', 'OBSERVATION_REQUEST', 'PRIOR_RESULT'],
                    },
                    {
                        identifier: 'ORC',
                        sequence: '35',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['SPECIMEN', 'ORDER', 'OBSERVATION_REQUEST', 'PRIOR_RESULT', 'ORDER_PRIOR'],
                    },
                    {
                        identifier: 'OBR',
                        sequence: '36',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['SPECIMEN', 'ORDER', 'OBSERVATION_REQUEST', 'PRIOR_RESULT', 'ORDER_PRIOR'],
                    },
                    {
                        identifier: 'NTE',
                        sequence: '37',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['SPECIMEN', 'ORDER', 'OBSERVATION_REQUEST', 'PRIOR_RESULT', 'ORDER_PRIOR'],
                    },
                    {
                        identifier: 'ROL',
                        sequence: '38',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['SPECIMEN', 'ORDER', 'OBSERVATION_REQUEST', 'PRIOR_RESULT', 'ORDER_PRIOR'],
                    },
                    {
                        identifier: 'TQ1',
                        sequence: '39',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['SPECIMEN', 'ORDER', 'OBSERVATION_REQUEST', 'PRIOR_RESULT', 'ORDER_PRIOR', 'TIMING_PRIOR'],
                    },
                    {
                        identifier: 'TQ2',
                        sequence: '40',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['SPECIMEN', 'ORDER', 'OBSERVATION_REQUEST', 'PRIOR_RESULT', 'ORDER_PRIOR', 'TIMING_PRIOR'],
                    },
                    {
                        identifier: 'OBX',
                        sequence: '41',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['SPECIMEN', 'ORDER', 'OBSERVATION_REQUEST', 'PRIOR_RESULT', 'ORDER_PRIOR', 'OBSERVATION_PRIOR'],
                    },
                    {
                        identifier: 'NTE',
                        sequence: '42',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['SPECIMEN', 'ORDER', 'OBSERVATION_REQUEST', 'PRIOR_RESULT', 'ORDER_PRIOR', 'OBSERVATION_PRIOR'],
                    },
                    { identifier: 'FT1', sequence: '43', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['SPECIMEN', 'ORDER'] },
                    { identifier: 'CTI', sequence: '44', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['SPECIMEN', 'ORDER'] },
                    { identifier: 'BLG', sequence: '45', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['SPECIMEN', 'ORDER'] },
                ],
                groups: {
                    PATIENT: {
                        sequence: { start: '5', stop: '15' },
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                        subgroup: {
                            PATIENT_VISIT: { sequence: { start: '9', stop: '10' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, subgroup: {} },
                            INSURANCE: { sequence: { start: '11', stop: '13' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                        },
                    },
                    SPECIMEN: {
                        sequence: { start: '16', stop: null },
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 },
                        subgroup: {
                            ORDER: {
                                sequence: { start: '19', stop: '45' },
                                restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 },
                                subgroup: {
                                    TIMING: { sequence: { start: '20', stop: '21' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                                    OBSERVATION_REQUEST: {
                                        sequence: { start: '22', stop: null },
                                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                                        subgroup: {
                                            OBSERVATION: { sequence: { start: '27', stop: '29' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                                            PRIOR_RESULT: {
                                                sequence: { start: null, stop: null },
                                                restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                                                subgroup: {
                                                    PATIENT_PRIOR: { sequence: { start: '30', stop: '31' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, subgroup: {} },
                                                    PATIENT_VISIT_PRIOR: { sequence: { start: '32', stop: '33' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, subgroup: {} },
                                                    ORDER_PRIOR: {
                                                        sequence: { start: '35', stop: null },
                                                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 },
                                                        subgroup: {
                                                            TIMING_PRIOR: { sequence: { start: '39', stop: '40' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                                                            OBSERVATION_PRIOR: {
                                                                sequence: { start: '41', stop: '42' },
                                                                restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 },
                                                                subgroup: {},
                                                            },
                                                        },
                                                    },
                                                },
                                            },
                                        },
                                    },
                                },
                            },
                        },
                    },
                },
            },
            2.7: {
                sequences: [
                    {},
                    { identifier: 'MSH', sequence: '1', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: false },
                    { identifier: 'SFT', sequence: '2', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: false },
                    { identifier: 'UAC', sequence: '3', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: false },
                    { identifier: 'NTE', sequence: '4', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: false },
                    { identifier: 'PID', sequence: '5', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT'] },
                    { identifier: 'PD1', sequence: '6', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT'] },
                    { identifier: 'PRT', sequence: '7', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATIENT'] },
                    { identifier: 'NTE', sequence: '8', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATIENT'] },
                    { identifier: 'NK1', sequence: '9', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATIENT'] },
                    { identifier: 'PV1', sequence: '10', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT', 'PATIENT_VISIT'] },
                    { identifier: 'PV2', sequence: '11', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT', 'PATIENT_VISIT'] },
                    { identifier: 'PRT', sequence: '12', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATIENT', 'PATIENT_VISIT'] },
                    { identifier: 'IN1', sequence: '13', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT', 'INSURANCE'] },
                    { identifier: 'IN2', sequence: '14', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT', 'INSURANCE'] },
                    { identifier: 'IN3', sequence: '15', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT', 'INSURANCE'] },
                    { identifier: 'GT1', sequence: '16', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT'] },
                    { identifier: 'AL1', sequence: '17', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATIENT'] },
                    { identifier: 'SPM', sequence: '18', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['SPECIMEN'] },
                    { identifier: 'OBX', sequence: '19', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['SPECIMEN', 'SPECIMEN_OBSERVATION'] },
                    { identifier: 'PRT', sequence: '20', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['SPECIMEN', 'SPECIMEN_OBSERVATION'] },
                    { identifier: 'SAC', sequence: '21', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['SPECIMEN'] },
                    { identifier: 'ORC', sequence: '22', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['SPECIMEN', 'ORDER'] },
                    { identifier: 'PRT', sequence: '23', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['SPECIMEN', 'ORDER'] },
                    { identifier: 'TQ1', sequence: '24', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['SPECIMEN', 'ORDER', 'TIMING'] },
                    { identifier: 'TQ2', sequence: '25', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['SPECIMEN', 'ORDER', 'TIMING'] },
                    { identifier: 'OBR', sequence: '26', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['SPECIMEN', 'ORDER', 'OBSERVATION_REQUEST'] },
                    { identifier: 'TCD', sequence: '27', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['SPECIMEN', 'ORDER', 'OBSERVATION_REQUEST'] },
                    { identifier: 'NTE', sequence: '28', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['SPECIMEN', 'ORDER', 'OBSERVATION_REQUEST'] },
                    { identifier: 'PRT', sequence: '29', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['SPECIMEN', 'ORDER', 'OBSERVATION_REQUEST'] },
                    { identifier: 'DG1', sequence: '30', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['SPECIMEN', 'ORDER', 'OBSERVATION_REQUEST'] },
                    {
                        identifier: 'OBX',
                        sequence: '31',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['SPECIMEN', 'ORDER', 'OBSERVATION_REQUEST', 'OBSERVATION'],
                    },
                    {
                        identifier: 'PRT',
                        sequence: '32',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['SPECIMEN', 'ORDER', 'OBSERVATION_REQUEST', 'OBSERVATION'],
                    },
                    {
                        identifier: 'TCD',
                        sequence: '33',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['SPECIMEN', 'ORDER', 'OBSERVATION_REQUEST', 'OBSERVATION'],
                    },
                    {
                        identifier: 'NTE',
                        sequence: '34',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['SPECIMEN', 'ORDER', 'OBSERVATION_REQUEST', 'OBSERVATION'],
                    },
                    {
                        identifier: 'PID',
                        sequence: '35',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['SPECIMEN', 'ORDER', 'OBSERVATION_REQUEST', 'PRIOR_RESULT', 'PATIENT_PRIOR'],
                    },
                    {
                        identifier: 'PD1',
                        sequence: '36',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['SPECIMEN', 'ORDER', 'OBSERVATION_REQUEST', 'PRIOR_RESULT', 'PATIENT_PRIOR'],
                    },
                    {
                        identifier: 'PRT',
                        sequence: '37',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['SPECIMEN', 'ORDER', 'OBSERVATION_REQUEST', 'PRIOR_RESULT', 'PATIENT_PRIOR'],
                    },
                    {
                        identifier: 'PV1',
                        sequence: '38',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['SPECIMEN', 'ORDER', 'OBSERVATION_REQUEST', 'PRIOR_RESULT', 'PATIENT_VISIT_PRIOR'],
                    },
                    {
                        identifier: 'PV2',
                        sequence: '39',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['SPECIMEN', 'ORDER', 'OBSERVATION_REQUEST', 'PRIOR_RESULT', 'PATIENT_VISIT_PRIOR'],
                    },
                    {
                        identifier: 'PRT',
                        sequence: '40',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['SPECIMEN', 'ORDER', 'OBSERVATION_REQUEST', 'PRIOR_RESULT', 'PATIENT_VISIT_PRIOR'],
                    },
                    {
                        identifier: 'AL1',
                        sequence: '41',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['SPECIMEN', 'ORDER', 'OBSERVATION_REQUEST', 'PRIOR_RESULT'],
                    },
                    {
                        identifier: 'ORC',
                        sequence: '42',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['SPECIMEN', 'ORDER', 'OBSERVATION_REQUEST', 'PRIOR_RESULT', 'ORDER_PRIOR'],
                    },
                    {
                        identifier: 'OBR',
                        sequence: '43',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['SPECIMEN', 'ORDER', 'OBSERVATION_REQUEST', 'PRIOR_RESULT', 'ORDER_PRIOR'],
                    },
                    {
                        identifier: 'NTE',
                        sequence: '44',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['SPECIMEN', 'ORDER', 'OBSERVATION_REQUEST', 'PRIOR_RESULT', 'ORDER_PRIOR'],
                    },
                    {
                        identifier: 'PRT',
                        sequence: '45',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['SPECIMEN', 'ORDER', 'OBSERVATION_REQUEST', 'PRIOR_RESULT', 'ORDER_PRIOR'],
                    },
                    {
                        identifier: 'TQ1',
                        sequence: '46',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['SPECIMEN', 'ORDER', 'OBSERVATION_REQUEST', 'PRIOR_RESULT', 'ORDER_PRIOR', 'TIMING_PRIOR'],
                    },
                    {
                        identifier: 'TQ2',
                        sequence: '47',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['SPECIMEN', 'ORDER', 'OBSERVATION_REQUEST', 'PRIOR_RESULT', 'ORDER_PRIOR', 'TIMING_PRIOR'],
                    },
                    {
                        identifier: 'OBX',
                        sequence: '48',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['SPECIMEN', 'ORDER', 'OBSERVATION_REQUEST', 'PRIOR_RESULT', 'ORDER_PRIOR', 'OBSERVATION_PRIOR'],
                    },
                    {
                        identifier: 'PRT',
                        sequence: '49',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['SPECIMEN', 'ORDER', 'OBSERVATION_REQUEST', 'PRIOR_RESULT', 'ORDER_PRIOR', 'OBSERVATION_PRIOR'],
                    },
                    {
                        identifier: 'NTE',
                        sequence: '50',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['SPECIMEN', 'ORDER', 'OBSERVATION_REQUEST', 'PRIOR_RESULT', 'ORDER_PRIOR', 'OBSERVATION_PRIOR'],
                    },
                    { identifier: 'FT1', sequence: '51', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['SPECIMEN', 'ORDER'] },
                    { identifier: 'CTI', sequence: '52', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['SPECIMEN', 'ORDER'] },
                    { identifier: 'BLG', sequence: '53', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['SPECIMEN', 'ORDER'] },
                ],
                groups: {
                    PATIENT: {
                        sequence: { start: '5', stop: '17' },
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                        subgroup: {
                            PATIENT_VISIT: { sequence: { start: '10', stop: '12' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, subgroup: {} },
                            INSURANCE: { sequence: { start: '13', stop: '15' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                        },
                    },
                    SPECIMEN: {
                        sequence: { start: '18', stop: null },
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 },
                        subgroup: {
                            SPECIMEN_OBSERVATION: { sequence: { start: '19', stop: '20' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                            ORDER: {
                                sequence: { start: '22', stop: '53' },
                                restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 },
                                subgroup: {
                                    TIMING: { sequence: { start: '24', stop: '25' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                                    OBSERVATION_REQUEST: {
                                        sequence: { start: '26', stop: null },
                                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                                        subgroup: {
                                            OBSERVATION: { sequence: { start: '31', stop: '34' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                                            PRIOR_RESULT: {
                                                sequence: { start: null, stop: null },
                                                restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                                                subgroup: {
                                                    PATIENT_PRIOR: { sequence: { start: '35', stop: '37' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, subgroup: {} },
                                                    PATIENT_VISIT_PRIOR: { sequence: { start: '38', stop: '40' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, subgroup: {} },
                                                    ORDER_PRIOR: {
                                                        sequence: { start: '42', stop: null },
                                                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 },
                                                        subgroup: {
                                                            TIMING_PRIOR: { sequence: { start: '46', stop: '47' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                                                            OBSERVATION_PRIOR: {
                                                                sequence: { start: '48', stop: '50' },
                                                                restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 },
                                                                subgroup: {},
                                                            },
                                                        },
                                                    },
                                                },
                                            },
                                        },
                                    },
                                },
                            },
                        },
                    },
                },
            },
            '2.7.1': {
                sequences: { ref: '2.7' },
                groups: { ref: '2.7' },
            },
        },
        segments: {
            MSH: MSH,
            SFT: SFT,
            UAC: UAC,
            NTE: NTE,
            PID: PID,
            PD1: PD1,
            PRT: PRT,
            NK1: NK1,
            ARV: ARV,
            PV1: PV1,
            PV2: PV2,
            IN1: IN1,
            IN2: IN2,
            IN3: IN3,
            GT1: GT1,
            AL1: AL1,
            SPM: SPM,
            OBX: OBX,
            SAC: SAC,
            ORC: ORC,
            TQ1: TQ1,
            TQ2: TQ2,
            OBR: OBR,
            TCD: TCD,
            DG1: DG1,
            FT1: FT1,
            CTI: CTI,
            BLG: BLG,
            ROL: ROL,
        },
    };

    constructor(message, version = null) {
        super(message, version);
    }
}
