import {
    MSH,
    SFT,
    UAC,
    NTE,
    PRT,
    GT1,
    NK1,
    PID,
    PD1,
    ARV,
    OBX,
    IN1,
    IN2,
    IN3,
    AL1,
    SPM,
    SAC,
    ORC,
    OBR,
    TQ1,
    TQ2,
    TCD,
    DG1,
    PV1,
    PV2,
    FT1,
    CTI,
    BLG,
    ROL,
} from '@healthcare-interoperability/hl7v2-segments';
import { TriggerEvent } from '@healthcare-interoperability/hl7v2-core';

export class OPL_O37 extends TriggerEvent {
    static TriggerEvent = 'OPL_O37';
    static Structure = {
        versions: {
            2.8: {
                sequences: [
                    {},
                    { identifier: 'MSH', sequence: '1', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: false },
                    { identifier: 'SFT', sequence: '2', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: false },
                    { identifier: 'UAC', sequence: '3', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: false },
                    { identifier: 'NTE', sequence: '4', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: false },
                    { identifier: 'PRT', sequence: '5', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 }, isGroup: false },
                    { identifier: 'GT1', sequence: '6', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['GUARANTOR'] },
                    { identifier: 'NTE', sequence: '7', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['GUARANTOR'] },
                    { identifier: 'NK1', sequence: '8', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 }, isGroup: true, groupPath: ['ORDER'] },
                    { identifier: 'PID', sequence: '9', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['ORDER', 'PATIENT'] },
                    { identifier: 'PD1', sequence: '10', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['ORDER', 'PATIENT'] },
                    { identifier: 'PRT', sequence: '11', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['ORDER', 'PATIENT'] },
                    { identifier: 'ARV', sequence: '12', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['ORDER', 'PATIENT'] },
                    { identifier: 'OBX', sequence: '13', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['ORDER', 'PATIENT', 'OBSERVATIONS_ON_PATIENT'] },
                    { identifier: 'PRT', sequence: '14', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['ORDER', 'PATIENT', 'OBSERVATIONS_ON_PATIENT'] },
                    { identifier: 'IN1', sequence: '15', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['ORDER', 'PATIENT', 'INSURANCE'] },
                    { identifier: 'IN2', sequence: '16', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['ORDER', 'PATIENT', 'INSURANCE'] },
                    { identifier: 'IN3', sequence: '17', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['ORDER', 'PATIENT', 'INSURANCE'] },
                    { identifier: 'AL1', sequence: '18', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['ORDER', 'PATIENT'] },
                    { identifier: 'SPM', sequence: '19', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['ORDER', 'SPECIMEN'] },
                    { identifier: 'OBX', sequence: '20', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['ORDER', 'SPECIMEN', 'SPECIMEN_OBSERVATION'] },
                    { identifier: 'PRT', sequence: '21', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['ORDER', 'SPECIMEN', 'SPECIMEN_OBSERVATION'] },
                    { identifier: 'SAC', sequence: '22', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['ORDER', 'SPECIMEN', 'CONTAINER'] },
                    {
                        identifier: 'OBX',
                        sequence: '23',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['ORDER', 'SPECIMEN', 'CONTAINER', 'CONTAINER_OBSERVATION'],
                    },
                    {
                        identifier: 'PRT',
                        sequence: '24',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['ORDER', 'SPECIMEN', 'CONTAINER', 'CONTAINER_OBSERVATION'],
                    },
                    { identifier: 'ORC', sequence: '25', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['ORDER', 'SPECIMEN', 'OBSERVATION_REQUEST'] },
                    { identifier: 'PRT', sequence: '26', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['ORDER', 'SPECIMEN', 'OBSERVATION_REQUEST'] },
                    { identifier: 'OBR', sequence: '27', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['ORDER', 'SPECIMEN', 'OBSERVATION_REQUEST'] },
                    { identifier: 'PRT', sequence: '28', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['ORDER', 'SPECIMEN', 'OBSERVATION_REQUEST'] },
                    {
                        identifier: 'TQ1',
                        sequence: '29',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['ORDER', 'SPECIMEN', 'OBSERVATION_REQUEST', 'TIMING'],
                    },
                    {
                        identifier: 'TQ2',
                        sequence: '30',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['ORDER', 'SPECIMEN', 'OBSERVATION_REQUEST', 'TIMING'],
                    },
                    { identifier: 'TCD', sequence: '31', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['ORDER', 'SPECIMEN', 'OBSERVATION_REQUEST'] },
                    { identifier: 'DG1', sequence: '32', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['ORDER', 'SPECIMEN', 'OBSERVATION_REQUEST'] },
                    {
                        identifier: 'OBX',
                        sequence: '33',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['ORDER', 'SPECIMEN', 'OBSERVATION_REQUEST', 'ORDER_RELATED_OBSERVATION'],
                    },
                    {
                        identifier: 'PRT',
                        sequence: '34',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['ORDER', 'SPECIMEN', 'OBSERVATION_REQUEST', 'ORDER_RELATED_OBSERVATION'],
                    },
                    { identifier: 'NK1', sequence: '35', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 }, isGroup: true, groupPath: ['ORDER', 'PRIOR_RESULT'] },
                    { identifier: 'PID', sequence: '36', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['ORDER', 'PRIOR_RESULT', 'PATIENT_PRIOR'] },
                    { identifier: 'PD1', sequence: '37', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['ORDER', 'PRIOR_RESULT', 'PATIENT_PRIOR'] },
                    { identifier: 'PRT', sequence: '38', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['ORDER', 'PRIOR_RESULT', 'PATIENT_PRIOR'] },
                    { identifier: 'ARV', sequence: '39', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['ORDER', 'PRIOR_RESULT', 'PATIENT_PRIOR'] },
                    { identifier: 'PV1', sequence: '40', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['ORDER', 'PRIOR_RESULT', 'PATIENT_VISIT_PRIOR'] },
                    { identifier: 'PV2', sequence: '41', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['ORDER', 'PRIOR_RESULT', 'PATIENT_VISIT_PRIOR'] },
                    { identifier: 'PRT', sequence: '42', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['ORDER', 'PRIOR_RESULT', 'PATIENT_VISIT_PRIOR'] },
                    { identifier: 'AL1', sequence: '43', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['ORDER', 'PRIOR_RESULT'] },
                    { identifier: 'OBR', sequence: '44', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['ORDER', 'PRIOR_RESULT', 'ORDER_PRIOR'] },
                    { identifier: 'ORC', sequence: '45', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['ORDER', 'PRIOR_RESULT', 'ORDER_PRIOR'] },
                    { identifier: 'PRT', sequence: '46', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['ORDER', 'PRIOR_RESULT', 'ORDER_PRIOR'] },
                    { identifier: 'TQ1', sequence: '47', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['ORDER', 'PRIOR_RESULT', 'ORDER_PRIOR', 'TIMING2'] },
                    {
                        identifier: 'TQ2',
                        sequence: '48',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['ORDER', 'PRIOR_RESULT', 'ORDER_PRIOR', 'TIMING2'],
                    },
                    {
                        identifier: 'OBX',
                        sequence: '49',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['ORDER', 'PRIOR_RESULT', 'ORDER_PRIOR', 'OBSERVATION_RESULT_GROUP'],
                    },
                    {
                        identifier: 'PRT',
                        sequence: '50',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['ORDER', 'PRIOR_RESULT', 'ORDER_PRIOR', 'OBSERVATION_RESULT_GROUP'],
                    },
                    { identifier: 'FT1', sequence: '51', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['ORDER'] },
                    { identifier: 'CTI', sequence: '52', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['ORDER'] },
                    { identifier: 'BLG', sequence: '53', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['ORDER'] },
                ],
                groups: {
                    GUARANTOR: { sequence: { start: '6', stop: '7' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, subgroup: {} },
                    ORDER: {
                        sequence: { start: '8', stop: '53' },
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 },
                        subgroup: {
                            PATIENT: {
                                sequence: { start: '9', stop: '18' },
                                restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                                subgroup: {
                                    OBSERVATIONS_ON_PATIENT: { sequence: { start: '13', stop: '14' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                                    INSURANCE: { sequence: { start: '15', stop: '17' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                                },
                            },
                            SPECIMEN: {
                                sequence: { start: '19', stop: null },
                                restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 },
                                subgroup: {
                                    SPECIMEN_OBSERVATION: { sequence: { start: '20', stop: '21' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                                    CONTAINER: {
                                        sequence: { start: '22', stop: null },
                                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                                        subgroup: { CONTAINER_OBSERVATION: { sequence: { start: '23', stop: '24' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} } },
                                    },
                                    OBSERVATION_REQUEST: {
                                        sequence: { start: '25', stop: null },
                                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 },
                                        subgroup: {
                                            TIMING: { sequence: { start: '29', stop: '30' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                                            ORDER_RELATED_OBSERVATION: { sequence: { start: '33', stop: '34' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                                        },
                                    },
                                },
                            },
                            PRIOR_RESULT: {
                                sequence: { start: '35', stop: null },
                                restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                                subgroup: {
                                    PATIENT_PRIOR: { sequence: { start: '36', stop: '39' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, subgroup: {} },
                                    PATIENT_VISIT_PRIOR: { sequence: { start: '40', stop: '42' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, subgroup: {} },
                                    ORDER_PRIOR: {
                                        sequence: { start: '44', stop: null },
                                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 },
                                        subgroup: {
                                            TIMING2: { sequence: { start: '47', stop: '48' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, subgroup: {} },
                                            OBSERVATION_RESULT_GROUP: { sequence: { start: '49', stop: '50' }, restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 }, subgroup: {} },
                                        },
                                    },
                                },
                            },
                        },
                    },
                },
            },
            2.6: {
                sequences: [
                    {},
                    { identifier: 'MSH', sequence: '1', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: false },
                    { identifier: 'SFT', sequence: '2', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: false },
                    { identifier: 'UAC', sequence: '3', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: false },
                    { identifier: 'NTE', sequence: '4', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: false },
                    { identifier: 'ROL', sequence: '5', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 }, isGroup: false },
                    { identifier: 'GT1', sequence: '6', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['GUARANTOR'] },
                    { identifier: 'NTE', sequence: '7', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['GUARANTOR'] },
                    { identifier: 'NK1', sequence: '8', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 }, isGroup: true, groupPath: ['ORDER'] },
                    { identifier: 'PID', sequence: '9', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['ORDER', 'PATIENT'] },
                    { identifier: 'PD1', sequence: '10', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['ORDER', 'PATIENT'] },
                    { identifier: 'OBX', sequence: '11', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['ORDER', 'PATIENT'] },
                    { identifier: 'IN1', sequence: '12', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['ORDER', 'PATIENT', 'INSURANCE'] },
                    { identifier: 'IN2', sequence: '13', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['ORDER', 'PATIENT', 'INSURANCE'] },
                    { identifier: 'IN3', sequence: '14', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['ORDER', 'PATIENT', 'INSURANCE'] },
                    { identifier: 'AL1', sequence: '15', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['ORDER', 'PATIENT'] },
                    { identifier: 'SPM', sequence: '16', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['ORDER', 'SPECIMEN'] },
                    { identifier: 'OBX', sequence: '17', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['ORDER', 'SPECIMEN'] },
                    { identifier: 'SAC', sequence: '18', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['ORDER', 'SPECIMEN', 'CONTAINER'] },
                    { identifier: 'OBX', sequence: '19', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['ORDER', 'SPECIMEN', 'CONTAINER'] },
                    { identifier: 'ORC', sequence: '20', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['ORDER', 'SPECIMEN', 'OBSERVATION_REQUEST'] },
                    { identifier: 'OBR', sequence: '21', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['ORDER', 'SPECIMEN', 'OBSERVATION_REQUEST'] },
                    { identifier: 'ROL', sequence: '22', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['ORDER', 'SPECIMEN', 'OBSERVATION_REQUEST'] },
                    {
                        identifier: 'TQ1',
                        sequence: '23',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['ORDER', 'SPECIMEN', 'OBSERVATION_REQUEST', 'TIMING'],
                    },
                    {
                        identifier: 'TQ2',
                        sequence: '24',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['ORDER', 'SPECIMEN', 'OBSERVATION_REQUEST', 'TIMING'],
                    },
                    { identifier: 'TCD', sequence: '25', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['ORDER', 'SPECIMEN', 'OBSERVATION_REQUEST'] },
                    { identifier: 'DG1', sequence: '26', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['ORDER', 'SPECIMEN', 'OBSERVATION_REQUEST'] },
                    { identifier: 'OBX', sequence: '27', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['ORDER', 'SPECIMEN', 'OBSERVATION_REQUEST'] },
                    { identifier: 'NK1', sequence: '28', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 }, isGroup: true, groupPath: ['ORDER', 'PRIOR_RESULT'] },
                    { identifier: 'PID', sequence: '29', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['ORDER', 'PRIOR_RESULT', 'PATIENT_PRIOR'] },
                    { identifier: 'PD1', sequence: '30', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['ORDER', 'PRIOR_RESULT', 'PATIENT_PRIOR'] },
                    { identifier: 'PV1', sequence: '31', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['ORDER', 'PRIOR_RESULT', 'PATIENT_VISIT_PRIOR'] },
                    { identifier: 'PV2', sequence: '32', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['ORDER', 'PRIOR_RESULT', 'PATIENT_VISIT_PRIOR'] },
                    { identifier: 'AL1', sequence: '33', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['ORDER', 'PRIOR_RESULT'] },
                    { identifier: 'OBR', sequence: '34', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['ORDER', 'PRIOR_RESULT', 'ORDER_PRIOR'] },
                    { identifier: 'ORC', sequence: '35', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['ORDER', 'PRIOR_RESULT', 'ORDER_PRIOR'] },
                    { identifier: 'ROL', sequence: '36', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['ORDER', 'PRIOR_RESULT', 'ORDER_PRIOR'] },
                    { identifier: 'TQ1', sequence: '37', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['ORDER', 'PRIOR_RESULT', 'ORDER_PRIOR', 'TIMING'] },
                    {
                        identifier: 'TQ2',
                        sequence: '38',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['ORDER', 'PRIOR_RESULT', 'ORDER_PRIOR', 'TIMING'],
                    },
                    { identifier: 'OBX', sequence: '39', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 }, isGroup: true, groupPath: ['ORDER', 'PRIOR_RESULT', 'ORDER_PRIOR'] },
                    { identifier: 'FT1', sequence: '40', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['ORDER'] },
                    { identifier: 'CTI', sequence: '41', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['ORDER'] },
                    { identifier: 'BLG', sequence: '42', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['ORDER'] },
                ],
                groups: {
                    GUARANTOR: { sequence: { start: '6', stop: '7' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, subgroup: {} },
                    ORDER: {
                        sequence: { start: '8', stop: '42' },
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 },
                        subgroup: {
                            PATIENT: {
                                sequence: { start: '9', stop: '15' },
                                restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                                subgroup: { INSURANCE: { sequence: { start: '12', stop: '14' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} } },
                            },
                            SPECIMEN: {
                                sequence: { start: '16', stop: null },
                                restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 },
                                subgroup: {
                                    CONTAINER: { sequence: { start: '18', stop: '19' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                                    OBSERVATION_REQUEST: {
                                        sequence: { start: '20', stop: '27' },
                                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 },
                                        subgroup: { TIMING: { sequence: { start: '23', stop: '24' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} } },
                                    },
                                },
                            },
                            PRIOR_RESULT: {
                                sequence: { start: '28', stop: null },
                                restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                                subgroup: {
                                    PATIENT_PRIOR: { sequence: { start: '29', stop: '30' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, subgroup: {} },
                                    PATIENT_VISIT_PRIOR: { sequence: { start: '31', stop: '32' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, subgroup: {} },
                                    ORDER_PRIOR: {
                                        sequence: { start: '34', stop: '39' },
                                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 },
                                        subgroup: { TIMING: { sequence: { start: '37', stop: '38' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, subgroup: {} } },
                                    },
                                },
                            },
                        },
                    },
                },
            },
            2.7: {
                sequences: [
                    {},
                    { identifier: 'MSH', sequence: '1', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: false },
                    { identifier: 'SFT', sequence: '2', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: false },
                    { identifier: 'UAC', sequence: '3', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: false },
                    { identifier: 'NTE', sequence: '4', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: false },
                    { identifier: 'PRT', sequence: '5', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 }, isGroup: false },
                    { identifier: 'GT1', sequence: '6', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['GUARANTOR'] },
                    { identifier: 'NTE', sequence: '7', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['GUARANTOR'] },
                    { identifier: 'NK1', sequence: '8', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 }, isGroup: true, groupPath: ['ORDER'] },
                    { identifier: 'PID', sequence: '9', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['ORDER', 'PATIENT'] },
                    { identifier: 'PD1', sequence: '10', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['ORDER', 'PATIENT'] },
                    { identifier: 'PRT', sequence: '11', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['ORDER', 'PATIENT'] },
                    { identifier: 'OBX', sequence: '12', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['ORDER', 'PATIENT', 'OBSERVATIONS_ON_PATIENT'] },
                    { identifier: 'PRT', sequence: '13', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['ORDER', 'PATIENT', 'OBSERVATIONS_ON_PATIENT'] },
                    { identifier: 'IN1', sequence: '14', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['ORDER', 'PATIENT', 'INSURANCE'] },
                    { identifier: 'IN2', sequence: '15', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['ORDER', 'PATIENT', 'INSURANCE'] },
                    { identifier: 'IN3', sequence: '16', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['ORDER', 'PATIENT', 'INSURANCE'] },
                    { identifier: 'AL1', sequence: '17', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['ORDER', 'PATIENT'] },
                    { identifier: 'SPM', sequence: '18', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['ORDER', 'SPECIMEN'] },
                    { identifier: 'OBX', sequence: '19', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['ORDER', 'SPECIMEN', 'SPECIMEN_OBSERVATION'] },
                    { identifier: 'PRT', sequence: '20', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['ORDER', 'SPECIMEN', 'SPECIMEN_OBSERVATION'] },
                    { identifier: 'SAC', sequence: '21', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['ORDER', 'SPECIMEN', 'CONTAINER'] },
                    {
                        identifier: 'OBX',
                        sequence: '22',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['ORDER', 'SPECIMEN', 'CONTAINER', 'CONTAINER_OBSERVATION'],
                    },
                    {
                        identifier: 'PRT',
                        sequence: '23',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['ORDER', 'SPECIMEN', 'CONTAINER', 'CONTAINER_OBSERVATION'],
                    },
                    { identifier: 'ORC', sequence: '24', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['ORDER', 'SPECIMEN', 'OBSERVATION_REQUEST'] },
                    { identifier: 'OBR', sequence: '25', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['ORDER', 'SPECIMEN', 'OBSERVATION_REQUEST'] },
                    { identifier: 'PRT', sequence: '26', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['ORDER', 'SPECIMEN', 'OBSERVATION_REQUEST'] },
                    {
                        identifier: 'TQ1',
                        sequence: '27',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['ORDER', 'SPECIMEN', 'OBSERVATION_REQUEST', 'TIMING'],
                    },
                    {
                        identifier: 'TQ2',
                        sequence: '28',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['ORDER', 'SPECIMEN', 'OBSERVATION_REQUEST', 'TIMING'],
                    },
                    { identifier: 'TCD', sequence: '29', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['ORDER', 'SPECIMEN', 'OBSERVATION_REQUEST'] },
                    { identifier: 'DG1', sequence: '30', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['ORDER', 'SPECIMEN', 'OBSERVATION_REQUEST'] },
                    {
                        identifier: 'OBX',
                        sequence: '31',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['ORDER', 'SPECIMEN', 'OBSERVATION_REQUEST', 'ORDER_RELATED_OBSERVATION'],
                    },
                    {
                        identifier: 'PRT',
                        sequence: '32',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['ORDER', 'SPECIMEN', 'OBSERVATION_REQUEST', 'ORDER_RELATED_OBSERVATION'],
                    },
                    { identifier: 'NK1', sequence: '33', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 }, isGroup: true, groupPath: ['ORDER', 'PRIOR_RESULT'] },
                    { identifier: 'PID', sequence: '34', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['ORDER', 'PRIOR_RESULT', 'PATIENT_PRIOR'] },
                    { identifier: 'PD1', sequence: '35', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['ORDER', 'PRIOR_RESULT', 'PATIENT_PRIOR'] },
                    { identifier: 'PRT', sequence: '36', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['ORDER', 'PRIOR_RESULT', 'PATIENT_PRIOR'] },
                    { identifier: 'PV1', sequence: '37', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['ORDER', 'PRIOR_RESULT', 'PATIENT_VISIT_PRIOR'] },
                    { identifier: 'PV2', sequence: '38', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['ORDER', 'PRIOR_RESULT', 'PATIENT_VISIT_PRIOR'] },
                    { identifier: 'PRT', sequence: '39', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['ORDER', 'PRIOR_RESULT', 'PATIENT_VISIT_PRIOR'] },
                    { identifier: 'AL1', sequence: '40', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['ORDER', 'PRIOR_RESULT'] },
                    { identifier: 'OBR', sequence: '41', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['ORDER', 'PRIOR_RESULT', 'ORDER_PRIOR'] },
                    { identifier: 'ORC', sequence: '42', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['ORDER', 'PRIOR_RESULT', 'ORDER_PRIOR'] },
                    { identifier: 'PRT', sequence: '43', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['ORDER', 'PRIOR_RESULT', 'ORDER_PRIOR'] },
                    { identifier: 'TQ1', sequence: '44', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['ORDER', 'PRIOR_RESULT', 'ORDER_PRIOR', 'TIMING2'] },
                    {
                        identifier: 'TQ2',
                        sequence: '45',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['ORDER', 'PRIOR_RESULT', 'ORDER_PRIOR', 'TIMING2'],
                    },
                    {
                        identifier: 'OBX',
                        sequence: '46',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['ORDER', 'PRIOR_RESULT', 'ORDER_PRIOR', 'OBSERVATION_RESULT_GROUP'],
                    },
                    {
                        identifier: 'PRT',
                        sequence: '47',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['ORDER', 'PRIOR_RESULT', 'ORDER_PRIOR', 'OBSERVATION_RESULT_GROUP'],
                    },
                    { identifier: 'FT1', sequence: '48', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['ORDER'] },
                    { identifier: 'CTI', sequence: '49', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['ORDER'] },
                    { identifier: 'BLG', sequence: '50', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['ORDER'] },
                ],
                groups: {
                    GUARANTOR: { sequence: { start: '6', stop: '7' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, subgroup: {} },
                    ORDER: {
                        sequence: { start: '8', stop: '50' },
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 },
                        subgroup: {
                            PATIENT: {
                                sequence: { start: '9', stop: '17' },
                                restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                                subgroup: {
                                    OBSERVATIONS_ON_PATIENT: { sequence: { start: '12', stop: '13' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                                    INSURANCE: { sequence: { start: '14', stop: '16' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                                },
                            },
                            SPECIMEN: {
                                sequence: { start: '18', stop: null },
                                restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 },
                                subgroup: {
                                    SPECIMEN_OBSERVATION: { sequence: { start: '19', stop: '20' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                                    CONTAINER: {
                                        sequence: { start: '21', stop: null },
                                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                                        subgroup: { CONTAINER_OBSERVATION: { sequence: { start: '22', stop: '23' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} } },
                                    },
                                    OBSERVATION_REQUEST: {
                                        sequence: { start: '24', stop: null },
                                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 },
                                        subgroup: {
                                            TIMING: { sequence: { start: '27', stop: '28' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                                            ORDER_RELATED_OBSERVATION: { sequence: { start: '31', stop: '32' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                                        },
                                    },
                                },
                            },
                            PRIOR_RESULT: {
                                sequence: { start: '33', stop: null },
                                restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                                subgroup: {
                                    PATIENT_PRIOR: { sequence: { start: '34', stop: '36' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, subgroup: {} },
                                    PATIENT_VISIT_PRIOR: { sequence: { start: '37', stop: '39' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, subgroup: {} },
                                    ORDER_PRIOR: {
                                        sequence: { start: '41', stop: null },
                                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 },
                                        subgroup: {
                                            TIMING2: { sequence: { start: '44', stop: '45' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, subgroup: {} },
                                            OBSERVATION_RESULT_GROUP: { sequence: { start: '46', stop: '47' }, restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 }, subgroup: {} },
                                        },
                                    },
                                },
                            },
                        },
                    },
                },
            },
            '2.7.1': {
                sequences: { ref: '2.7' },
                groups: { ref: '2.7' },
            },
        },
        segments: {
            MSH: MSH,
            SFT: SFT,
            UAC: UAC,
            NTE: NTE,
            PRT: PRT,
            GT1: GT1,
            NK1: NK1,
            PID: PID,
            PD1: PD1,
            ARV: ARV,
            OBX: OBX,
            IN1: IN1,
            IN2: IN2,
            IN3: IN3,
            AL1: AL1,
            SPM: SPM,
            SAC: SAC,
            ORC: ORC,
            OBR: OBR,
            TQ1: TQ1,
            TQ2: TQ2,
            TCD: TCD,
            DG1: DG1,
            PV1: PV1,
            PV2: PV2,
            FT1: FT1,
            CTI: CTI,
            BLG: BLG,
            ROL: ROL,
        },
    };

    constructor(message, version = null) {
        super(message, version);
    }
}
