import { MSH, SFT, UAC, NTE, PV1, PV2, PRT, OBX, NK1, PID, PD1, ARV, SPM, SAC, INV, OBR, ORC, TQ1, TQ2, ROL } from '@healthcare-interoperability/hl7v2-segments';
import { TriggerEvent } from '@healthcare-interoperability/hl7v2-core';

export class OPU_R25 extends TriggerEvent {
    static TriggerEvent = 'OPU_R25';
    static Structure = {
        versions: {
            2.8: {
                sequences: [
                    {},
                    { identifier: 'MSH', sequence: '1', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: false },
                    { identifier: 'SFT', sequence: '2', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: false },
                    { identifier: 'UAC', sequence: '3', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: false },
                    { identifier: 'NTE', sequence: '4', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: false },
                    { identifier: 'PV1', sequence: '5', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: false },
                    { identifier: 'PV2', sequence: '6', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: false },
                    { identifier: 'PRT', sequence: '7', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: false },
                    { identifier: 'OBX', sequence: '8', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT_VISIT_OBSERVATION'] },
                    { identifier: 'NTE', sequence: '9', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATIENT_VISIT_OBSERVATION'] },
                    { identifier: 'PRT', sequence: '10', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATIENT_VISIT_OBSERVATION'] },
                    { identifier: 'NK1', sequence: '11', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 }, isGroup: true, groupPath: ['ACCESSION_DETAIL'] },
                    { identifier: 'PID', sequence: '12', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['ACCESSION_DETAIL', 'PATIENT'] },
                    { identifier: 'PD1', sequence: '13', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['ACCESSION_DETAIL', 'PATIENT'] },
                    { identifier: 'PRT', sequence: '14', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['ACCESSION_DETAIL', 'PATIENT'] },
                    { identifier: 'ARV', sequence: '15', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['ACCESSION_DETAIL', 'PATIENT'] },
                    {
                        identifier: 'OBX',
                        sequence: '16',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['ACCESSION_DETAIL', 'PATIENT', 'PATIENT_OBSERVATION'],
                    },
                    {
                        identifier: 'PRT',
                        sequence: '17',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['ACCESSION_DETAIL', 'PATIENT', 'PATIENT_OBSERVATION'],
                    },
                    {
                        identifier: 'NTE',
                        sequence: '18',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['ACCESSION_DETAIL', 'PATIENT', 'PATIENT_OBSERVATION'],
                    },
                    { identifier: 'SPM', sequence: '19', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['ACCESSION_DETAIL', 'SPECIMEN'] },
                    {
                        identifier: 'OBX',
                        sequence: '20',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['ACCESSION_DETAIL', 'SPECIMEN', 'SPECIMEN_OBSERVATION'],
                    },
                    {
                        identifier: 'PRT',
                        sequence: '21',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['ACCESSION_DETAIL', 'SPECIMEN', 'SPECIMEN_OBSERVATION'],
                    },
                    {
                        identifier: 'NTE',
                        sequence: '22',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['ACCESSION_DETAIL', 'SPECIMEN', 'SPECIMEN_OBSERVATION'],
                    },
                    { identifier: 'SAC', sequence: '23', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['ACCESSION_DETAIL', 'SPECIMEN', 'CONTAINER'] },
                    { identifier: 'INV', sequence: '24', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['ACCESSION_DETAIL', 'SPECIMEN', 'CONTAINER'] },
                    { identifier: 'OBR', sequence: '25', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['ACCESSION_DETAIL', 'SPECIMEN', 'ORDER'] },
                    { identifier: 'PRT', sequence: '26', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['ACCESSION_DETAIL', 'SPECIMEN', 'ORDER'] },
                    {
                        identifier: 'ORC',
                        sequence: '27',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['ACCESSION_DETAIL', 'SPECIMEN', 'ORDER', 'COMMON_ORDER'],
                    },
                    {
                        identifier: 'PRT',
                        sequence: '28',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['ACCESSION_DETAIL', 'SPECIMEN', 'ORDER', 'COMMON_ORDER'],
                    },
                    { identifier: 'NTE', sequence: '29', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['ACCESSION_DETAIL', 'SPECIMEN', 'ORDER'] },
                    { identifier: 'PRT', sequence: '30', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['ACCESSION_DETAIL', 'SPECIMEN', 'ORDER'] },
                    {
                        identifier: 'TQ1',
                        sequence: '31',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['ACCESSION_DETAIL', 'SPECIMEN', 'ORDER', 'TIMING_QTY'],
                    },
                    {
                        identifier: 'TQ2',
                        sequence: '32',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['ACCESSION_DETAIL', 'SPECIMEN', 'ORDER', 'TIMING_QTY'],
                    },
                    { identifier: 'OBX', sequence: '33', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['ACCESSION_DETAIL', 'SPECIMEN', 'ORDER', 'RESULT'] },
                    {
                        identifier: 'PRT',
                        sequence: '34',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['ACCESSION_DETAIL', 'SPECIMEN', 'ORDER', 'RESULT'],
                    },
                    {
                        identifier: 'NTE',
                        sequence: '35',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['ACCESSION_DETAIL', 'SPECIMEN', 'ORDER', 'RESULT'],
                    },
                ],
                groups: {
                    PATIENT_VISIT_OBSERVATION: { sequence: { start: '8', stop: '10' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                    ACCESSION_DETAIL: {
                        sequence: { start: '11', stop: null },
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 },
                        subgroup: {
                            PATIENT: {
                                sequence: { start: '12', stop: null },
                                restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                                subgroup: { PATIENT_OBSERVATION: { sequence: { start: '16', stop: '18' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} } },
                            },
                            SPECIMEN: {
                                sequence: { start: '19', stop: null },
                                restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 },
                                subgroup: {
                                    SPECIMEN_OBSERVATION: { sequence: { start: '20', stop: '22' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                                    CONTAINER: { sequence: { start: '23', stop: '24' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                                    ORDER: {
                                        sequence: { start: '25', stop: null },
                                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 },
                                        subgroup: {
                                            COMMON_ORDER: { sequence: { start: '27', stop: '28' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, subgroup: {} },
                                            TIMING_QTY: { sequence: { start: '31', stop: '32' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                                            RESULT: { sequence: { start: '33', stop: '35' }, restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 }, subgroup: {} },
                                        },
                                    },
                                },
                            },
                        },
                    },
                },
            },
            2.6: {
                sequences: [
                    {},
                    { identifier: 'MSH', sequence: '1', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: false },
                    { identifier: 'SFT', sequence: '2', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: false },
                    { identifier: 'UAC', sequence: '3', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: false },
                    { identifier: 'NTE', sequence: '4', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: false },
                    { identifier: 'PV1', sequence: '5', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: false },
                    { identifier: 'PV2', sequence: '6', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: false },
                    { identifier: 'OBX', sequence: '7', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: false },
                    { identifier: 'NTE', sequence: '8', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: false },
                    { identifier: 'ROL', sequence: '9', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 }, isGroup: false },
                    { identifier: 'NK1', sequence: '10', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 }, isGroup: true, groupPath: ['ACCESSION_DETAIL'] },
                    { identifier: 'PID', sequence: '11', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['ACCESSION_DETAIL', 'PATIENT'] },
                    { identifier: 'PD1', sequence: '12', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['ACCESSION_DETAIL', 'PATIENT'] },
                    {
                        identifier: 'OBX',
                        sequence: '13',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['ACCESSION_DETAIL', 'PATIENT', 'PATIENT_OBSERVATION'],
                    },
                    {
                        identifier: 'NTE',
                        sequence: '14',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['ACCESSION_DETAIL', 'PATIENT', 'PATIENT_OBSERVATION'],
                    },
                    { identifier: 'SPM', sequence: '15', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['ACCESSION_DETAIL', 'SPECIMEN'] },
                    {
                        identifier: 'OBX',
                        sequence: '16',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['ACCESSION_DETAIL', 'SPECIMEN', 'SPECIMEN_OBSERVATION'],
                    },
                    {
                        identifier: 'NTE',
                        sequence: '17',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['ACCESSION_DETAIL', 'SPECIMEN', 'SPECIMEN_OBSERVATION'],
                    },
                    { identifier: 'SAC', sequence: '18', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['ACCESSION_DETAIL', 'SPECIMEN', 'CONTAINER'] },
                    { identifier: 'INV', sequence: '19', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['ACCESSION_DETAIL', 'SPECIMEN', 'CONTAINER'] },
                    { identifier: 'OBR', sequence: '20', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['ACCESSION_DETAIL', 'SPECIMEN', 'ORDER'] },
                    { identifier: 'ORC', sequence: '21', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['ACCESSION_DETAIL', 'SPECIMEN', 'ORDER'] },
                    { identifier: 'NTE', sequence: '22', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['ACCESSION_DETAIL', 'SPECIMEN', 'ORDER'] },
                    { identifier: 'ROL', sequence: '23', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['ACCESSION_DETAIL', 'SPECIMEN', 'ORDER'] },
                    {
                        identifier: 'TQ1',
                        sequence: '24',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['ACCESSION_DETAIL', 'SPECIMEN', 'ORDER', 'TIMING_QTY'],
                    },
                    {
                        identifier: 'TQ2',
                        sequence: '25',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['ACCESSION_DETAIL', 'SPECIMEN', 'ORDER', 'TIMING_QTY'],
                    },
                    { identifier: 'OBX', sequence: '26', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['ACCESSION_DETAIL', 'SPECIMEN', 'ORDER', 'RESULT'] },
                    {
                        identifier: 'NTE',
                        sequence: '27',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['ACCESSION_DETAIL', 'SPECIMEN', 'ORDER', 'RESULT'],
                    },
                ],
                groups: {
                    ACCESSION_DETAIL: {
                        sequence: { start: '10', stop: null },
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 },
                        subgroup: {
                            PATIENT: {
                                sequence: { start: '11', stop: null },
                                restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                                subgroup: { PATIENT_OBSERVATION: { sequence: { start: '13', stop: '14' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} } },
                            },
                            SPECIMEN: {
                                sequence: { start: '15', stop: null },
                                restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 },
                                subgroup: {
                                    SPECIMEN_OBSERVATION: { sequence: { start: '16', stop: '17' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                                    CONTAINER: { sequence: { start: '18', stop: '19' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                                    ORDER: {
                                        sequence: { start: '20', stop: null },
                                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 },
                                        subgroup: {
                                            TIMING_QTY: { sequence: { start: '24', stop: '25' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                                            RESULT: { sequence: { start: '26', stop: '27' }, restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 }, subgroup: {} },
                                        },
                                    },
                                },
                            },
                        },
                    },
                },
            },
            2.7: {
                sequences: [
                    {},
                    { identifier: 'MSH', sequence: '1', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: false },
                    { identifier: 'SFT', sequence: '2', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: false },
                    { identifier: 'UAC', sequence: '3', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: false },
                    { identifier: 'NTE', sequence: '4', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: false },
                    { identifier: 'PV1', sequence: '5', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: false },
                    { identifier: 'PV2', sequence: '6', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: false },
                    { identifier: 'PRT', sequence: '7', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: false },
                    { identifier: 'OBX', sequence: '8', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT_VISIT_OBSERVATION'] },
                    { identifier: 'NTE', sequence: '9', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATIENT_VISIT_OBSERVATION'] },
                    { identifier: 'PRT', sequence: '10', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATIENT_VISIT_OBSERVATION'] },
                    { identifier: 'NK1', sequence: '11', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 }, isGroup: true, groupPath: ['ACCESSION_DETAIL'] },
                    { identifier: 'PID', sequence: '12', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['ACCESSION_DETAIL', 'PATIENT'] },
                    { identifier: 'PD1', sequence: '13', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['ACCESSION_DETAIL', 'PATIENT'] },
                    { identifier: 'PRT', sequence: '14', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['ACCESSION_DETAIL', 'PATIENT'] },
                    {
                        identifier: 'OBX',
                        sequence: '15',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['ACCESSION_DETAIL', 'PATIENT', 'PATIENT_OBSERVATION'],
                    },
                    {
                        identifier: 'PRT',
                        sequence: '16',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['ACCESSION_DETAIL', 'PATIENT', 'PATIENT_OBSERVATION'],
                    },
                    {
                        identifier: 'NTE',
                        sequence: '17',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['ACCESSION_DETAIL', 'PATIENT', 'PATIENT_OBSERVATION'],
                    },
                    { identifier: 'SPM', sequence: '18', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['ACCESSION_DETAIL', 'SPECIMEN'] },
                    {
                        identifier: 'OBX',
                        sequence: '19',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['ACCESSION_DETAIL', 'SPECIMEN', 'SPECIMEN_OBSERVATION'],
                    },
                    {
                        identifier: 'PRT',
                        sequence: '20',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['ACCESSION_DETAIL', 'SPECIMEN', 'SPECIMEN_OBSERVATION'],
                    },
                    {
                        identifier: 'NTE',
                        sequence: '21',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['ACCESSION_DETAIL', 'SPECIMEN', 'SPECIMEN_OBSERVATION'],
                    },
                    { identifier: 'SAC', sequence: '22', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['ACCESSION_DETAIL', 'SPECIMEN', 'CONTAINER'] },
                    { identifier: 'INV', sequence: '23', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['ACCESSION_DETAIL', 'SPECIMEN', 'CONTAINER'] },
                    { identifier: 'OBR', sequence: '24', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['ACCESSION_DETAIL', 'SPECIMEN', 'ORDER'] },
                    { identifier: 'ORC', sequence: '25', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['ACCESSION_DETAIL', 'SPECIMEN', 'ORDER'] },
                    { identifier: 'NTE', sequence: '26', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['ACCESSION_DETAIL', 'SPECIMEN', 'ORDER'] },
                    { identifier: 'PRT', sequence: '27', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['ACCESSION_DETAIL', 'SPECIMEN', 'ORDER'] },
                    {
                        identifier: 'TQ1',
                        sequence: '28',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['ACCESSION_DETAIL', 'SPECIMEN', 'ORDER', 'TIMING_QTY'],
                    },
                    {
                        identifier: 'TQ2',
                        sequence: '29',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['ACCESSION_DETAIL', 'SPECIMEN', 'ORDER', 'TIMING_QTY'],
                    },
                    { identifier: 'OBX', sequence: '30', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['ACCESSION_DETAIL', 'SPECIMEN', 'ORDER', 'RESULT'] },
                    {
                        identifier: 'PRT',
                        sequence: '31',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['ACCESSION_DETAIL', 'SPECIMEN', 'ORDER', 'RESULT'],
                    },
                    {
                        identifier: 'NTE',
                        sequence: '32',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['ACCESSION_DETAIL', 'SPECIMEN', 'ORDER', 'RESULT'],
                    },
                ],
                groups: {
                    PATIENT_VISIT_OBSERVATION: { sequence: { start: '8', stop: '10' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                    ACCESSION_DETAIL: {
                        sequence: { start: '11', stop: null },
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 },
                        subgroup: {
                            PATIENT: {
                                sequence: { start: '12', stop: null },
                                restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                                subgroup: { PATIENT_OBSERVATION: { sequence: { start: '15', stop: '17' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} } },
                            },
                            SPECIMEN: {
                                sequence: { start: '18', stop: null },
                                restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 },
                                subgroup: {
                                    SPECIMEN_OBSERVATION: { sequence: { start: '19', stop: '21' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                                    CONTAINER: { sequence: { start: '22', stop: '23' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                                    ORDER: {
                                        sequence: { start: '24', stop: null },
                                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 },
                                        subgroup: {
                                            TIMING_QTY: { sequence: { start: '28', stop: '29' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                                            RESULT: { sequence: { start: '30', stop: '32' }, restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 }, subgroup: {} },
                                        },
                                    },
                                },
                            },
                        },
                    },
                },
            },
            '2.7.1': {
                sequences: { ref: '2.7' },
                groups: { ref: '2.7' },
            },
        },
        segments: {
            MSH: MSH,
            SFT: SFT,
            UAC: UAC,
            NTE: NTE,
            PV1: PV1,
            PV2: PV2,
            PRT: PRT,
            OBX: OBX,
            NK1: NK1,
            PID: PID,
            PD1: PD1,
            ARV: ARV,
            SPM: SPM,
            SAC: SAC,
            INV: INV,
            OBR: OBR,
            ORC: ORC,
            TQ1: TQ1,
            TQ2: TQ2,
            ROL: ROL,
        },
    };

    constructor(message, version = null) {
        super(message, version);
    }
}
