import { MSH, SFT, UAC, EVN, PID, PD1, PRT, ARV, NTE, PV1, PV2, PES, PEO, PCR, RXE, TQ1, TQ2, RXR, RXA, PRB, OBX, NK1, CSR, CSP } from '@healthcare-interoperability/hl7v2-segments';
import { TriggerEvent } from '@healthcare-interoperability/hl7v2-core';

export class PEX_P08 extends TriggerEvent {
    static TriggerEvent = 'PEX_P08';
    static Structure = {
        versions: {
            2.8: {
                sequences: [
                    {},
                    { identifier: 'MSH', sequence: '1', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: false },
                    { identifier: 'SFT', sequence: '2', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: false },
                    { identifier: 'UAC', sequence: '3', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: false },
                    { identifier: 'EVN', sequence: '4', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: false },
                    { identifier: 'PID', sequence: '5', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: false },
                    { identifier: 'PD1', sequence: '6', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: false },
                    { identifier: 'PRT', sequence: '7', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: false },
                    { identifier: 'ARV', sequence: '8', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: false },
                    { identifier: 'NTE', sequence: '9', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: false },
                    { identifier: 'PV1', sequence: '10', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['VISIT'] },
                    { identifier: 'PV2', sequence: '11', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['VISIT'] },
                    { identifier: 'PRT', sequence: '12', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['VISIT'] },
                    { identifier: 'PES', sequence: '13', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['EXPERIENCE'] },
                    { identifier: 'PEO', sequence: '14', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['EXPERIENCE', 'PEX_OBSERVATION'] },
                    { identifier: 'PCR', sequence: '15', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['EXPERIENCE', 'PEX_OBSERVATION', 'PEX_CAUSE'] },
                    {
                        identifier: 'RXE',
                        sequence: '16',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['EXPERIENCE', 'PEX_OBSERVATION', 'PEX_CAUSE', 'RX_ORDER'],
                    },
                    {
                        identifier: 'PRT',
                        sequence: '17',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['EXPERIENCE', 'PEX_OBSERVATION', 'PEX_CAUSE', 'RX_ORDER'],
                    },
                    {
                        identifier: 'TQ1',
                        sequence: '18',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['EXPERIENCE', 'PEX_OBSERVATION', 'PEX_CAUSE', 'RX_ORDER', 'TIMING_QTY'],
                    },
                    {
                        identifier: 'TQ2',
                        sequence: '19',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['EXPERIENCE', 'PEX_OBSERVATION', 'PEX_CAUSE', 'RX_ORDER', 'TIMING_QTY'],
                    },
                    {
                        identifier: 'RXR',
                        sequence: '20',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['EXPERIENCE', 'PEX_OBSERVATION', 'PEX_CAUSE', 'RX_ORDER'],
                    },
                    {
                        identifier: 'RXA',
                        sequence: '21',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['EXPERIENCE', 'PEX_OBSERVATION', 'PEX_CAUSE', 'RX_ADMINISTRATION'],
                    },
                    {
                        identifier: 'RXR',
                        sequence: '22',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['EXPERIENCE', 'PEX_OBSERVATION', 'PEX_CAUSE', 'RX_ADMINISTRATION'],
                    },
                    {
                        identifier: 'PRT',
                        sequence: '23',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['EXPERIENCE', 'PEX_OBSERVATION', 'PEX_CAUSE', 'RX_ADMINISTRATION'],
                    },
                    { identifier: 'PRB', sequence: '24', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['EXPERIENCE', 'PEX_OBSERVATION', 'PEX_CAUSE'] },
                    {
                        identifier: 'OBX',
                        sequence: '25',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['EXPERIENCE', 'PEX_OBSERVATION', 'PEX_CAUSE', 'OBSERVATION'],
                    },
                    {
                        identifier: 'PRT',
                        sequence: '26',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['EXPERIENCE', 'PEX_OBSERVATION', 'PEX_CAUSE', 'OBSERVATION'],
                    },
                    { identifier: 'NTE', sequence: '27', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['EXPERIENCE', 'PEX_OBSERVATION', 'PEX_CAUSE'] },
                    {
                        identifier: 'NK1',
                        sequence: '28',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['EXPERIENCE', 'PEX_OBSERVATION', 'PEX_CAUSE', 'ASSOCIATED_PERSON'],
                    },
                    {
                        identifier: 'RXE',
                        sequence: '29',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['EXPERIENCE', 'PEX_OBSERVATION', 'PEX_CAUSE', 'ASSOCIATED_PERSON', 'ASSOCIATED_RX_ORDER'],
                    },
                    {
                        identifier: 'PRT',
                        sequence: '30',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['EXPERIENCE', 'PEX_OBSERVATION', 'PEX_CAUSE', 'ASSOCIATED_PERSON', 'ASSOCIATED_RX_ORDER'],
                    },
                    {
                        identifier: 'TQ1',
                        sequence: '31',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['EXPERIENCE', 'PEX_OBSERVATION', 'PEX_CAUSE', 'ASSOCIATED_PERSON', 'ASSOCIATED_RX_ORDER', 'NK1_TIMING_QTY'],
                    },
                    {
                        identifier: 'TQ2',
                        sequence: '32',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['EXPERIENCE', 'PEX_OBSERVATION', 'PEX_CAUSE', 'ASSOCIATED_PERSON', 'ASSOCIATED_RX_ORDER', 'NK1_TIMING_QTY'],
                    },
                    {
                        identifier: 'RXR',
                        sequence: '33',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['EXPERIENCE', 'PEX_OBSERVATION', 'PEX_CAUSE', 'ASSOCIATED_PERSON', 'ASSOCIATED_RX_ORDER'],
                    },
                    {
                        identifier: 'RXA',
                        sequence: '34',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['EXPERIENCE', 'PEX_OBSERVATION', 'PEX_CAUSE', 'ASSOCIATED_PERSON', 'ASSOCIATED_RX_ADMIN'],
                    },
                    {
                        identifier: 'RXR',
                        sequence: '35',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['EXPERIENCE', 'PEX_OBSERVATION', 'PEX_CAUSE', 'ASSOCIATED_PERSON', 'ASSOCIATED_RX_ADMIN'],
                    },
                    {
                        identifier: 'PRT',
                        sequence: '36',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['EXPERIENCE', 'PEX_OBSERVATION', 'PEX_CAUSE', 'ASSOCIATED_PERSON', 'ASSOCIATED_RX_ADMIN'],
                    },
                    {
                        identifier: 'PRB',
                        sequence: '37',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['EXPERIENCE', 'PEX_OBSERVATION', 'PEX_CAUSE', 'ASSOCIATED_PERSON'],
                    },
                    {
                        identifier: 'OBX',
                        sequence: '38',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['EXPERIENCE', 'PEX_OBSERVATION', 'PEX_CAUSE', 'ASSOCIATED_PERSON', 'ASSOCIATED_OBSERVATION'],
                    },
                    {
                        identifier: 'PRT',
                        sequence: '39',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['EXPERIENCE', 'PEX_OBSERVATION', 'PEX_CAUSE', 'ASSOCIATED_PERSON', 'ASSOCIATED_OBSERVATION'],
                    },
                    {
                        identifier: 'CSR',
                        sequence: '40',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['EXPERIENCE', 'PEX_OBSERVATION', 'PEX_CAUSE', 'STUDY'],
                    },
                    {
                        identifier: 'CSP',
                        sequence: '41',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['EXPERIENCE', 'PEX_OBSERVATION', 'PEX_CAUSE', 'STUDY'],
                    },
                ],
                groups: {
                    VISIT: { sequence: { start: '10', stop: '12' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, subgroup: {} },
                    EXPERIENCE: {
                        sequence: { start: '13', stop: null },
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 },
                        subgroup: {
                            PEX_OBSERVATION: {
                                sequence: { start: '14', stop: null },
                                restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 },
                                subgroup: {
                                    PEX_CAUSE: {
                                        sequence: { start: '15', stop: null },
                                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 },
                                        subgroup: {
                                            RX_ORDER: {
                                                sequence: { start: '16', stop: '20' },
                                                restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                                                subgroup: { TIMING_QTY: { sequence: { start: '18', stop: '19' }, restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 }, subgroup: {} } },
                                            },
                                            RX_ADMINISTRATION: { sequence: { start: '21', stop: '23' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                                            OBSERVATION: { sequence: { start: '25', stop: '26' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                                            ASSOCIATED_PERSON: {
                                                sequence: { start: '28', stop: null },
                                                restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                                                subgroup: {
                                                    ASSOCIATED_RX_ORDER: {
                                                        sequence: { start: '29', stop: '33' },
                                                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                                                        subgroup: {
                                                            NK1_TIMING_QTY: { sequence: { start: '31', stop: '32' }, restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 }, subgroup: {} },
                                                        },
                                                    },
                                                    ASSOCIATED_RX_ADMIN: { sequence: { start: '34', stop: '36' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                                                    ASSOCIATED_OBSERVATION: { sequence: { start: '38', stop: '39' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                                                },
                                            },
                                            STUDY: { sequence: { start: '40', stop: '41' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                                        },
                                    },
                                },
                            },
                        },
                    },
                },
            },
            2.3: {
                sequences: [
                    {},
                    { identifier: 'MSH', sequence: '1', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: false },
                    { identifier: 'EVN', sequence: '2', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: false },
                    { identifier: 'PID', sequence: '3', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: false },
                    { identifier: 'PD1', sequence: '4', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: false },
                    { identifier: 'NTE', sequence: '5', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: false },
                    { identifier: 'PV1', sequence: '6', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['VISIT'] },
                    { identifier: 'PV2', sequence: '7', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['VISIT'] },
                    { identifier: 'PES', sequence: '8', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['EXPERIENCE'] },
                    { identifier: 'PEO', sequence: '9', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['EXPERIENCE', 'PEX_OBSERVATION'] },
                    { identifier: 'PCR', sequence: '10', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['EXPERIENCE', 'PEX_OBSERVATION', 'PEX_CAUSE'] },
                    {
                        identifier: 'RXE',
                        sequence: '11',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['EXPERIENCE', 'PEX_OBSERVATION', 'PEX_CAUSE', 'RX_ORDER'],
                    },
                    {
                        identifier: 'RXR',
                        sequence: '12',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['EXPERIENCE', 'PEX_OBSERVATION', 'PEX_CAUSE', 'RX_ORDER'],
                    },
                    {
                        identifier: 'RXA',
                        sequence: '13',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['EXPERIENCE', 'PEX_OBSERVATION', 'PEX_CAUSE', 'RX_ADMINISTRATION'],
                    },
                    {
                        identifier: 'RXR',
                        sequence: '14',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['EXPERIENCE', 'PEX_OBSERVATION', 'PEX_CAUSE', 'RX_ADMINISTRATION'],
                    },
                    { identifier: 'PRB', sequence: '15', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['EXPERIENCE', 'PEX_OBSERVATION', 'PEX_CAUSE'] },
                    { identifier: 'OBX', sequence: '16', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['EXPERIENCE', 'PEX_OBSERVATION', 'PEX_CAUSE'] },
                    { identifier: 'NTE', sequence: '17', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['EXPERIENCE', 'PEX_OBSERVATION', 'PEX_CAUSE'] },
                    {
                        identifier: 'NK1',
                        sequence: '18',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['EXPERIENCE', 'PEX_OBSERVATION', 'PEX_CAUSE', 'ASSOCIATED_PERSON'],
                    },
                    {
                        identifier: 'RXE',
                        sequence: '19',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['EXPERIENCE', 'PEX_OBSERVATION', 'PEX_CAUSE', 'ASSOCIATED_PERSON', 'ASSOCIATED_RX_ORDER'],
                    },
                    {
                        identifier: 'RXR',
                        sequence: '20',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['EXPERIENCE', 'PEX_OBSERVATION', 'PEX_CAUSE', 'ASSOCIATED_PERSON', 'ASSOCIATED_RX_ORDER'],
                    },
                    {
                        identifier: 'RXA',
                        sequence: '21',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['EXPERIENCE', 'PEX_OBSERVATION', 'PEX_CAUSE', 'ASSOCIATED_PERSON', 'ASSOCIATED_RX_ADMIN'],
                    },
                    {
                        identifier: 'RXR',
                        sequence: '22',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['EXPERIENCE', 'PEX_OBSERVATION', 'PEX_CAUSE', 'ASSOCIATED_PERSON', 'ASSOCIATED_RX_ADMIN'],
                    },
                    {
                        identifier: 'PRB',
                        sequence: '23',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['EXPERIENCE', 'PEX_OBSERVATION', 'PEX_CAUSE', 'ASSOCIATED_PERSON'],
                    },
                    {
                        identifier: 'OBX',
                        sequence: '24',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['EXPERIENCE', 'PEX_OBSERVATION', 'PEX_CAUSE', 'ASSOCIATED_PERSON'],
                    },
                    {
                        identifier: 'CSR',
                        sequence: '25',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['EXPERIENCE', 'PEX_OBSERVATION', 'PEX_CAUSE', 'STUDY'],
                    },
                    {
                        identifier: 'CSP',
                        sequence: '26',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['EXPERIENCE', 'PEX_OBSERVATION', 'PEX_CAUSE', 'STUDY'],
                    },
                ],
                groups: {
                    VISIT: { sequence: { start: '6', stop: '7' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, subgroup: {} },
                    EXPERIENCE: {
                        sequence: { start: '8', stop: null },
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 },
                        subgroup: {
                            PEX_OBSERVATION: {
                                sequence: { start: '9', stop: null },
                                restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 },
                                subgroup: {
                                    PEX_CAUSE: {
                                        sequence: { start: '10', stop: null },
                                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 },
                                        subgroup: {
                                            RX_ORDER: { sequence: { start: '11', stop: '12' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, subgroup: {} },
                                            RX_ADMINISTRATION: { sequence: { start: '13', stop: '14' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                                            ASSOCIATED_PERSON: {
                                                sequence: { start: '18', stop: '24' },
                                                restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                                                subgroup: {
                                                    ASSOCIATED_RX_ORDER: { sequence: { start: '19', stop: '20' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, subgroup: {} },
                                                    ASSOCIATED_RX_ADMIN: { sequence: { start: '21', stop: '22' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                                                },
                                            },
                                            STUDY: { sequence: { start: '25', stop: '26' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                                        },
                                    },
                                },
                            },
                        },
                    },
                },
            },
            '2.3.1': {
                sequences: { ref: '2.3' },
                groups: { ref: '2.3' },
            },
            2.4: {
                sequences: { ref: '2.3' },
                groups: { ref: '2.3' },
            },
            2.5: {
                sequences: [
                    {},
                    { identifier: 'MSH', sequence: '1', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: false },
                    { identifier: 'SFT', sequence: '2', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: false },
                    { identifier: 'EVN', sequence: '3', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: false },
                    { identifier: 'PID', sequence: '4', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: false },
                    { identifier: 'PD1', sequence: '5', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: false },
                    { identifier: 'NTE', sequence: '6', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: false },
                    { identifier: 'PV1', sequence: '7', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['VISIT'] },
                    { identifier: 'PV2', sequence: '8', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['VISIT'] },
                    { identifier: 'PES', sequence: '9', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['EXPERIENCE'] },
                    { identifier: 'PEO', sequence: '10', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['EXPERIENCE', 'PEX_OBSERVATION'] },
                    { identifier: 'PCR', sequence: '11', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['EXPERIENCE', 'PEX_OBSERVATION', 'PEX_CAUSE'] },
                    {
                        identifier: 'RXE',
                        sequence: '12',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['EXPERIENCE', 'PEX_OBSERVATION', 'PEX_CAUSE', 'RX_ORDER'],
                    },
                    {
                        identifier: 'TQ1',
                        sequence: '13',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['EXPERIENCE', 'PEX_OBSERVATION', 'PEX_CAUSE', 'RX_ORDER', 'TIMING_QTY'],
                    },
                    {
                        identifier: 'TQ2',
                        sequence: '14',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['EXPERIENCE', 'PEX_OBSERVATION', 'PEX_CAUSE', 'RX_ORDER', 'TIMING_QTY'],
                    },
                    {
                        identifier: 'RXR',
                        sequence: '15',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['EXPERIENCE', 'PEX_OBSERVATION', 'PEX_CAUSE', 'RX_ORDER'],
                    },
                    {
                        identifier: 'RXA',
                        sequence: '16',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['EXPERIENCE', 'PEX_OBSERVATION', 'PEX_CAUSE', 'RX_ADMINISTRATION'],
                    },
                    {
                        identifier: 'RXR',
                        sequence: '17',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['EXPERIENCE', 'PEX_OBSERVATION', 'PEX_CAUSE', 'RX_ADMINISTRATION'],
                    },
                    { identifier: 'PRB', sequence: '18', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['EXPERIENCE', 'PEX_OBSERVATION', 'PEX_CAUSE'] },
                    { identifier: 'OBX', sequence: '19', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['EXPERIENCE', 'PEX_OBSERVATION', 'PEX_CAUSE'] },
                    { identifier: 'NTE', sequence: '20', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['EXPERIENCE', 'PEX_OBSERVATION', 'PEX_CAUSE'] },
                    {
                        identifier: 'NK1',
                        sequence: '21',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['EXPERIENCE', 'PEX_OBSERVATION', 'PEX_CAUSE', 'ASSOCIATED_PERSON'],
                    },
                    {
                        identifier: 'RXE',
                        sequence: '22',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['EXPERIENCE', 'PEX_OBSERVATION', 'PEX_CAUSE', 'ASSOCIATED_PERSON', 'ASSOCIATED_RX_ORDER'],
                    },
                    {
                        identifier: 'TQ1',
                        sequence: '23',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['EXPERIENCE', 'PEX_OBSERVATION', 'PEX_CAUSE', 'ASSOCIATED_PERSON', 'ASSOCIATED_RX_ORDER', 'NK1_TIMING_QTY'],
                    },
                    {
                        identifier: 'TQ2',
                        sequence: '24',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['EXPERIENCE', 'PEX_OBSERVATION', 'PEX_CAUSE', 'ASSOCIATED_PERSON', 'ASSOCIATED_RX_ORDER', 'NK1_TIMING_QTY'],
                    },
                    {
                        identifier: 'RXR',
                        sequence: '25',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['EXPERIENCE', 'PEX_OBSERVATION', 'PEX_CAUSE', 'ASSOCIATED_PERSON', 'ASSOCIATED_RX_ORDER'],
                    },
                    {
                        identifier: 'RXA',
                        sequence: '26',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['EXPERIENCE', 'PEX_OBSERVATION', 'PEX_CAUSE', 'ASSOCIATED_PERSON', 'ASSOCIATED_RX_ADMIN'],
                    },
                    {
                        identifier: 'RXR',
                        sequence: '27',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['EXPERIENCE', 'PEX_OBSERVATION', 'PEX_CAUSE', 'ASSOCIATED_PERSON', 'ASSOCIATED_RX_ADMIN'],
                    },
                    {
                        identifier: 'PRB',
                        sequence: '28',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['EXPERIENCE', 'PEX_OBSERVATION', 'PEX_CAUSE', 'ASSOCIATED_PERSON'],
                    },
                    {
                        identifier: 'OBX',
                        sequence: '29',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['EXPERIENCE', 'PEX_OBSERVATION', 'PEX_CAUSE', 'ASSOCIATED_PERSON'],
                    },
                    {
                        identifier: 'CSR',
                        sequence: '30',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['EXPERIENCE', 'PEX_OBSERVATION', 'PEX_CAUSE', 'STUDY'],
                    },
                    {
                        identifier: 'CSP',
                        sequence: '31',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['EXPERIENCE', 'PEX_OBSERVATION', 'PEX_CAUSE', 'STUDY'],
                    },
                ],
                groups: {
                    VISIT: { sequence: { start: '7', stop: '8' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, subgroup: {} },
                    EXPERIENCE: {
                        sequence: { start: '9', stop: null },
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 },
                        subgroup: {
                            PEX_OBSERVATION: {
                                sequence: { start: '10', stop: null },
                                restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 },
                                subgroup: {
                                    PEX_CAUSE: {
                                        sequence: { start: '11', stop: null },
                                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 },
                                        subgroup: {
                                            RX_ORDER: {
                                                sequence: { start: '12', stop: '15' },
                                                restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                                                subgroup: { TIMING_QTY: { sequence: { start: '13', stop: '14' }, restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 }, subgroup: {} } },
                                            },
                                            RX_ADMINISTRATION: { sequence: { start: '16', stop: '17' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                                            ASSOCIATED_PERSON: {
                                                sequence: { start: '21', stop: '29' },
                                                restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                                                subgroup: {
                                                    ASSOCIATED_RX_ORDER: {
                                                        sequence: { start: '22', stop: '25' },
                                                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                                                        subgroup: {
                                                            NK1_TIMING_QTY: { sequence: { start: '23', stop: '24' }, restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 }, subgroup: {} },
                                                        },
                                                    },
                                                    ASSOCIATED_RX_ADMIN: { sequence: { start: '26', stop: '27' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                                                },
                                            },
                                            STUDY: { sequence: { start: '30', stop: '31' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                                        },
                                    },
                                },
                            },
                        },
                    },
                },
            },
            '2.5.1': {
                sequences: { ref: '2.5' },
                groups: { ref: '2.5' },
            },
            2.6: {
                sequences: [
                    {},
                    { identifier: 'MSH', sequence: '1', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: false },
                    { identifier: 'SFT', sequence: '2', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: false },
                    { identifier: 'UAC', sequence: '3', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: false },
                    { identifier: 'EVN', sequence: '4', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: false },
                    { identifier: 'PID', sequence: '5', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: false },
                    { identifier: 'PD1', sequence: '6', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: false },
                    { identifier: 'NTE', sequence: '7', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: false },
                    { identifier: 'PV1', sequence: '8', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['VISIT'] },
                    { identifier: 'PV2', sequence: '9', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['VISIT'] },
                    { identifier: 'PES', sequence: '10', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['EXPERIENCE'] },
                    { identifier: 'PEO', sequence: '11', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['EXPERIENCE', 'PEX_OBSERVATION'] },
                    { identifier: 'PCR', sequence: '12', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['EXPERIENCE', 'PEX_OBSERVATION', 'PEX_CAUSE'] },
                    {
                        identifier: 'RXE',
                        sequence: '13',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['EXPERIENCE', 'PEX_OBSERVATION', 'PEX_CAUSE', 'RX_ORDER'],
                    },
                    {
                        identifier: 'TQ1',
                        sequence: '14',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['EXPERIENCE', 'PEX_OBSERVATION', 'PEX_CAUSE', 'RX_ORDER', 'TIMING_QTY'],
                    },
                    {
                        identifier: 'TQ2',
                        sequence: '15',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['EXPERIENCE', 'PEX_OBSERVATION', 'PEX_CAUSE', 'RX_ORDER', 'TIMING_QTY'],
                    },
                    {
                        identifier: 'RXR',
                        sequence: '16',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['EXPERIENCE', 'PEX_OBSERVATION', 'PEX_CAUSE', 'RX_ORDER'],
                    },
                    {
                        identifier: 'RXA',
                        sequence: '17',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['EXPERIENCE', 'PEX_OBSERVATION', 'PEX_CAUSE', 'RX_ADMINISTRATION'],
                    },
                    {
                        identifier: 'RXR',
                        sequence: '18',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['EXPERIENCE', 'PEX_OBSERVATION', 'PEX_CAUSE', 'RX_ADMINISTRATION'],
                    },
                    { identifier: 'PRB', sequence: '19', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['EXPERIENCE', 'PEX_OBSERVATION', 'PEX_CAUSE'] },
                    { identifier: 'OBX', sequence: '20', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['EXPERIENCE', 'PEX_OBSERVATION', 'PEX_CAUSE'] },
                    { identifier: 'NTE', sequence: '21', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['EXPERIENCE', 'PEX_OBSERVATION', 'PEX_CAUSE'] },
                    {
                        identifier: 'NK1',
                        sequence: '22',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['EXPERIENCE', 'PEX_OBSERVATION', 'PEX_CAUSE', 'ASSOCIATED_PERSON'],
                    },
                    {
                        identifier: 'RXE',
                        sequence: '23',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['EXPERIENCE', 'PEX_OBSERVATION', 'PEX_CAUSE', 'ASSOCIATED_PERSON', 'ASSOCIATED_RX_ORDER'],
                    },
                    {
                        identifier: 'TQ1',
                        sequence: '24',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['EXPERIENCE', 'PEX_OBSERVATION', 'PEX_CAUSE', 'ASSOCIATED_PERSON', 'ASSOCIATED_RX_ORDER', 'NK1_TIMING_QTY'],
                    },
                    {
                        identifier: 'TQ2',
                        sequence: '25',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['EXPERIENCE', 'PEX_OBSERVATION', 'PEX_CAUSE', 'ASSOCIATED_PERSON', 'ASSOCIATED_RX_ORDER', 'NK1_TIMING_QTY'],
                    },
                    {
                        identifier: 'RXR',
                        sequence: '26',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['EXPERIENCE', 'PEX_OBSERVATION', 'PEX_CAUSE', 'ASSOCIATED_PERSON', 'ASSOCIATED_RX_ORDER'],
                    },
                    {
                        identifier: 'RXA',
                        sequence: '27',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['EXPERIENCE', 'PEX_OBSERVATION', 'PEX_CAUSE', 'ASSOCIATED_PERSON', 'ASSOCIATED_RX_ADMIN'],
                    },
                    {
                        identifier: 'RXR',
                        sequence: '28',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['EXPERIENCE', 'PEX_OBSERVATION', 'PEX_CAUSE', 'ASSOCIATED_PERSON', 'ASSOCIATED_RX_ADMIN'],
                    },
                    {
                        identifier: 'PRB',
                        sequence: '29',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['EXPERIENCE', 'PEX_OBSERVATION', 'PEX_CAUSE', 'ASSOCIATED_PERSON'],
                    },
                    {
                        identifier: 'OBX',
                        sequence: '30',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['EXPERIENCE', 'PEX_OBSERVATION', 'PEX_CAUSE', 'ASSOCIATED_PERSON'],
                    },
                    {
                        identifier: 'CSR',
                        sequence: '31',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['EXPERIENCE', 'PEX_OBSERVATION', 'PEX_CAUSE', 'STUDY'],
                    },
                    {
                        identifier: 'CSP',
                        sequence: '32',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['EXPERIENCE', 'PEX_OBSERVATION', 'PEX_CAUSE', 'STUDY'],
                    },
                ],
                groups: {
                    VISIT: { sequence: { start: '8', stop: '9' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, subgroup: {} },
                    EXPERIENCE: {
                        sequence: { start: '10', stop: null },
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 },
                        subgroup: {
                            PEX_OBSERVATION: {
                                sequence: { start: '11', stop: null },
                                restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 },
                                subgroup: {
                                    PEX_CAUSE: {
                                        sequence: { start: '12', stop: null },
                                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 },
                                        subgroup: {
                                            RX_ORDER: {
                                                sequence: { start: '13', stop: '16' },
                                                restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                                                subgroup: { TIMING_QTY: { sequence: { start: '14', stop: '15' }, restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 }, subgroup: {} } },
                                            },
                                            RX_ADMINISTRATION: { sequence: { start: '17', stop: '18' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                                            ASSOCIATED_PERSON: {
                                                sequence: { start: '22', stop: '30' },
                                                restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                                                subgroup: {
                                                    ASSOCIATED_RX_ORDER: {
                                                        sequence: { start: '23', stop: '26' },
                                                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                                                        subgroup: {
                                                            NK1_TIMING_QTY: { sequence: { start: '24', stop: '25' }, restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 }, subgroup: {} },
                                                        },
                                                    },
                                                    ASSOCIATED_RX_ADMIN: { sequence: { start: '27', stop: '28' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                                                },
                                            },
                                            STUDY: { sequence: { start: '31', stop: '32' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                                        },
                                    },
                                },
                            },
                        },
                    },
                },
            },
            2.7: {
                sequences: [
                    {},
                    { identifier: 'MSH', sequence: '1', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: false },
                    { identifier: 'SFT', sequence: '2', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: false },
                    { identifier: 'UAC', sequence: '3', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: false },
                    { identifier: 'EVN', sequence: '4', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: false },
                    { identifier: 'PID', sequence: '5', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: false },
                    { identifier: 'PD1', sequence: '6', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: false },
                    { identifier: 'PRT', sequence: '7', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: false },
                    { identifier: 'NTE', sequence: '8', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: false },
                    { identifier: 'PV1', sequence: '9', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['VISIT'] },
                    { identifier: 'PV2', sequence: '10', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['VISIT'] },
                    { identifier: 'PRT', sequence: '11', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['VISIT'] },
                    { identifier: 'PES', sequence: '12', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['EXPERIENCE'] },
                    { identifier: 'PEO', sequence: '13', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['EXPERIENCE', 'PEX_OBSERVATION'] },
                    { identifier: 'PCR', sequence: '14', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['EXPERIENCE', 'PEX_OBSERVATION', 'PEX_CAUSE'] },
                    {
                        identifier: 'RXE',
                        sequence: '15',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['EXPERIENCE', 'PEX_OBSERVATION', 'PEX_CAUSE', 'RX_ORDER'],
                    },
                    {
                        identifier: 'PRT',
                        sequence: '16',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['EXPERIENCE', 'PEX_OBSERVATION', 'PEX_CAUSE', 'RX_ORDER'],
                    },
                    {
                        identifier: 'TQ1',
                        sequence: '17',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['EXPERIENCE', 'PEX_OBSERVATION', 'PEX_CAUSE', 'RX_ORDER', 'TIMING_QTY'],
                    },
                    {
                        identifier: 'TQ2',
                        sequence: '18',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['EXPERIENCE', 'PEX_OBSERVATION', 'PEX_CAUSE', 'RX_ORDER', 'TIMING_QTY'],
                    },
                    {
                        identifier: 'RXR',
                        sequence: '19',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['EXPERIENCE', 'PEX_OBSERVATION', 'PEX_CAUSE', 'RX_ORDER'],
                    },
                    {
                        identifier: 'RXA',
                        sequence: '20',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['EXPERIENCE', 'PEX_OBSERVATION', 'PEX_CAUSE', 'RX_ADMINISTRATION'],
                    },
                    {
                        identifier: 'RXR',
                        sequence: '21',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['EXPERIENCE', 'PEX_OBSERVATION', 'PEX_CAUSE', 'RX_ADMINISTRATION'],
                    },
                    {
                        identifier: 'PRT',
                        sequence: '22',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['EXPERIENCE', 'PEX_OBSERVATION', 'PEX_CAUSE', 'RX_ADMINISTRATION'],
                    },
                    { identifier: 'PRB', sequence: '23', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['EXPERIENCE', 'PEX_OBSERVATION', 'PEX_CAUSE'] },
                    {
                        identifier: 'OBX',
                        sequence: '24',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['EXPERIENCE', 'PEX_OBSERVATION', 'PEX_CAUSE', 'OBSERVATION'],
                    },
                    {
                        identifier: 'PRT',
                        sequence: '25',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['EXPERIENCE', 'PEX_OBSERVATION', 'PEX_CAUSE', 'OBSERVATION'],
                    },
                    { identifier: 'NTE', sequence: '26', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['EXPERIENCE', 'PEX_OBSERVATION', 'PEX_CAUSE'] },
                    {
                        identifier: 'NK1',
                        sequence: '27',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['EXPERIENCE', 'PEX_OBSERVATION', 'PEX_CAUSE', 'ASSOCIATED_PERSON'],
                    },
                    {
                        identifier: 'RXE',
                        sequence: '28',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['EXPERIENCE', 'PEX_OBSERVATION', 'PEX_CAUSE', 'ASSOCIATED_PERSON', 'ASSOCIATED_RX_ORDER'],
                    },
                    {
                        identifier: 'PRT',
                        sequence: '29',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['EXPERIENCE', 'PEX_OBSERVATION', 'PEX_CAUSE', 'ASSOCIATED_PERSON', 'ASSOCIATED_RX_ORDER'],
                    },
                    {
                        identifier: 'TQ1',
                        sequence: '30',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['EXPERIENCE', 'PEX_OBSERVATION', 'PEX_CAUSE', 'ASSOCIATED_PERSON', 'ASSOCIATED_RX_ORDER', 'NK1_TIMING_QTY'],
                    },
                    {
                        identifier: 'TQ2',
                        sequence: '31',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['EXPERIENCE', 'PEX_OBSERVATION', 'PEX_CAUSE', 'ASSOCIATED_PERSON', 'ASSOCIATED_RX_ORDER', 'NK1_TIMING_QTY'],
                    },
                    {
                        identifier: 'RXR',
                        sequence: '32',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['EXPERIENCE', 'PEX_OBSERVATION', 'PEX_CAUSE', 'ASSOCIATED_PERSON', 'ASSOCIATED_RX_ORDER'],
                    },
                    {
                        identifier: 'RXA',
                        sequence: '33',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['EXPERIENCE', 'PEX_OBSERVATION', 'PEX_CAUSE', 'ASSOCIATED_PERSON', 'ASSOCIATED_RX_ADMIN'],
                    },
                    {
                        identifier: 'RXR',
                        sequence: '34',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['EXPERIENCE', 'PEX_OBSERVATION', 'PEX_CAUSE', 'ASSOCIATED_PERSON', 'ASSOCIATED_RX_ADMIN'],
                    },
                    {
                        identifier: 'PRT',
                        sequence: '35',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['EXPERIENCE', 'PEX_OBSERVATION', 'PEX_CAUSE', 'ASSOCIATED_PERSON', 'ASSOCIATED_RX_ADMIN'],
                    },
                    {
                        identifier: 'PRB',
                        sequence: '36',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['EXPERIENCE', 'PEX_OBSERVATION', 'PEX_CAUSE', 'ASSOCIATED_PERSON'],
                    },
                    {
                        identifier: 'OBX',
                        sequence: '37',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['EXPERIENCE', 'PEX_OBSERVATION', 'PEX_CAUSE', 'ASSOCIATED_PERSON', 'ASSOCIATED_OBSERVATION'],
                    },
                    {
                        identifier: 'PRT',
                        sequence: '38',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['EXPERIENCE', 'PEX_OBSERVATION', 'PEX_CAUSE', 'ASSOCIATED_PERSON', 'ASSOCIATED_OBSERVATION'],
                    },
                    {
                        identifier: 'CSR',
                        sequence: '39',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['EXPERIENCE', 'PEX_OBSERVATION', 'PEX_CAUSE', 'STUDY'],
                    },
                    {
                        identifier: 'CSP',
                        sequence: '40',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['EXPERIENCE', 'PEX_OBSERVATION', 'PEX_CAUSE', 'STUDY'],
                    },
                ],
                groups: {
                    VISIT: { sequence: { start: '9', stop: '11' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, subgroup: {} },
                    EXPERIENCE: {
                        sequence: { start: '12', stop: null },
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 },
                        subgroup: {
                            PEX_OBSERVATION: {
                                sequence: { start: '13', stop: null },
                                restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 },
                                subgroup: {
                                    PEX_CAUSE: {
                                        sequence: { start: '14', stop: null },
                                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 },
                                        subgroup: {
                                            RX_ORDER: {
                                                sequence: { start: '15', stop: '19' },
                                                restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                                                subgroup: { TIMING_QTY: { sequence: { start: '17', stop: '18' }, restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 }, subgroup: {} } },
                                            },
                                            RX_ADMINISTRATION: { sequence: { start: '20', stop: '22' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                                            OBSERVATION: { sequence: { start: '24', stop: '25' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                                            ASSOCIATED_PERSON: {
                                                sequence: { start: '27', stop: null },
                                                restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                                                subgroup: {
                                                    ASSOCIATED_RX_ORDER: {
                                                        sequence: { start: '28', stop: '32' },
                                                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                                                        subgroup: {
                                                            NK1_TIMING_QTY: { sequence: { start: '30', stop: '31' }, restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 }, subgroup: {} },
                                                        },
                                                    },
                                                    ASSOCIATED_RX_ADMIN: { sequence: { start: '33', stop: '35' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                                                    ASSOCIATED_OBSERVATION: { sequence: { start: '37', stop: '38' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                                                },
                                            },
                                            STUDY: { sequence: { start: '39', stop: '40' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                                        },
                                    },
                                },
                            },
                        },
                    },
                },
            },
            '2.7.1': {
                sequences: { ref: '2.7' },
                groups: { ref: '2.7' },
            },
        },
        segments: {
            MSH: MSH,
            SFT: SFT,
            UAC: UAC,
            EVN: EVN,
            PID: PID,
            PD1: PD1,
            PRT: PRT,
            ARV: ARV,
            NTE: NTE,
            PV1: PV1,
            PV2: PV2,
            PES: PES,
            PEO: PEO,
            PCR: PCR,
            RXE: RXE,
            TQ1: TQ1,
            TQ2: TQ2,
            RXR: RXR,
            RXA: RXA,
            PRB: PRB,
            OBX: OBX,
            NK1: NK1,
            CSR: CSR,
            CSP: CSP,
        },
    };

    constructor(message, version = null) {
        super(message, version);
    }
}
