import { MSH, SFT, UAC, PID, PV1, PV2, PTH, NTE, VAR, ROL, GOL, OBX, PRT, PRB, ORC, OBR, Hxx, RQD, RQ1, RXO, ODS, ODT } from '@healthcare-interoperability/hl7v2-segments';
import { TriggerEvent } from '@healthcare-interoperability/hl7v2-core';

export class PPG_PCH extends TriggerEvent {
    static TriggerEvent = 'PPG_PCH';
    static Structure = {
        versions: {
            2.8: {
                sequences: [
                    {},
                    { identifier: 'MSH', sequence: '1', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: false },
                    { identifier: 'SFT', sequence: '2', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: false },
                    { identifier: 'UAC', sequence: '3', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: false },
                    { identifier: 'PID', sequence: '4', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: false },
                    { identifier: 'PV1', sequence: '5', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT_VISIT'] },
                    { identifier: 'PV2', sequence: '6', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT_VISIT'] },
                    { identifier: 'PTH', sequence: '7', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PATHWAY'] },
                    { identifier: 'NTE', sequence: '8', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATHWAY'] },
                    { identifier: 'VAR', sequence: '9', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATHWAY'] },
                    { identifier: 'ROL', sequence: '10', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PATHWAY', 'PATHWAY_ROLE'] },
                    { identifier: 'VAR', sequence: '11', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATHWAY', 'PATHWAY_ROLE'] },
                    { identifier: 'GOL', sequence: '12', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PATHWAY', 'GOAL'] },
                    { identifier: 'NTE', sequence: '13', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATHWAY', 'GOAL'] },
                    { identifier: 'VAR', sequence: '14', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATHWAY', 'GOAL'] },
                    { identifier: 'ROL', sequence: '15', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PATHWAY', 'GOAL', 'GOAL_ROLE'] },
                    { identifier: 'VAR', sequence: '16', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATHWAY', 'GOAL', 'GOAL_ROLE'] },
                    { identifier: 'OBX', sequence: '17', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PATHWAY', 'GOAL', 'GOAL_OBSERVATION'] },
                    { identifier: 'PRT', sequence: '18', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATHWAY', 'GOAL', 'GOAL_OBSERVATION'] },
                    { identifier: 'NTE', sequence: '19', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATHWAY', 'GOAL', 'GOAL_OBSERVATION'] },
                    { identifier: 'PRB', sequence: '20', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PATHWAY', 'GOAL', 'PROBLEM'] },
                    { identifier: 'NTE', sequence: '21', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATHWAY', 'GOAL', 'PROBLEM'] },
                    { identifier: 'VAR', sequence: '22', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATHWAY', 'GOAL', 'PROBLEM'] },
                    { identifier: 'ROL', sequence: '23', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PATHWAY', 'GOAL', 'PROBLEM', 'PROBLEM_ROLE'] },
                    { identifier: 'VAR', sequence: '24', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATHWAY', 'GOAL', 'PROBLEM', 'PROBLEM_ROLE'] },
                    {
                        identifier: 'OBX',
                        sequence: '25',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['PATHWAY', 'GOAL', 'PROBLEM', 'PROBLEM_OBSERVATION'],
                    },
                    {
                        identifier: 'PRT',
                        sequence: '26',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['PATHWAY', 'GOAL', 'PROBLEM', 'PROBLEM_OBSERVATION'],
                    },
                    {
                        identifier: 'NTE',
                        sequence: '27',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['PATHWAY', 'GOAL', 'PROBLEM', 'PROBLEM_OBSERVATION'],
                    },
                    { identifier: 'ORC', sequence: '28', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PATHWAY', 'GOAL', 'ORDER'] },
                    {
                        identifier: 'OBR',
                        sequence: '29',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['PATHWAY', 'GOAL', 'ORDER', 'ORDER_DETAIL', 'CHOICE'],
                    },
                    {
                        identifier: 'Hxx',
                        sequence: '30',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['PATHWAY', 'GOAL', 'ORDER', 'ORDER_DETAIL', 'CHOICE'],
                    },
                    { identifier: 'NTE', sequence: '31', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATHWAY', 'GOAL', 'ORDER', 'ORDER_DETAIL'] },
                    { identifier: 'VAR', sequence: '32', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATHWAY', 'GOAL', 'ORDER', 'ORDER_DETAIL'] },
                    {
                        identifier: 'OBX',
                        sequence: '33',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['PATHWAY', 'GOAL', 'ORDER', 'ORDER_DETAIL', 'ORDER_OBSERVATION'],
                    },
                    {
                        identifier: 'PRT',
                        sequence: '34',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['PATHWAY', 'GOAL', 'ORDER', 'ORDER_DETAIL', 'ORDER_OBSERVATION'],
                    },
                    {
                        identifier: 'NTE',
                        sequence: '35',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['PATHWAY', 'GOAL', 'ORDER', 'ORDER_DETAIL', 'ORDER_OBSERVATION'],
                    },
                    {
                        identifier: 'VAR',
                        sequence: '36',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['PATHWAY', 'GOAL', 'ORDER', 'ORDER_DETAIL', 'ORDER_OBSERVATION'],
                    },
                ],
                groups: {
                    PATIENT_VISIT: { sequence: { start: '5', stop: '6' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, subgroup: {} },
                    PATHWAY: {
                        sequence: { start: '7', stop: null },
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 },
                        subgroup: {
                            PATHWAY_ROLE: { sequence: { start: '10', stop: '11' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                            GOAL: {
                                sequence: { start: '12', stop: null },
                                restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                                subgroup: {
                                    GOAL_ROLE: { sequence: { start: '15', stop: '16' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                                    GOAL_OBSERVATION: { sequence: { start: '17', stop: '19' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                                    PROBLEM: {
                                        sequence: { start: '20', stop: null },
                                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                                        subgroup: {
                                            PROBLEM_ROLE: { sequence: { start: '23', stop: '24' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                                            PROBLEM_OBSERVATION: { sequence: { start: '25', stop: '27' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                                        },
                                    },
                                    ORDER: {
                                        sequence: { start: '28', stop: null },
                                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                                        subgroup: {
                                            ORDER_DETAIL: {
                                                sequence: { start: null, stop: null },
                                                restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                                                subgroup: {
                                                    CHOICE: { sequence: { start: '29', stop: '30' }, restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, subgroup: {} },
                                                    ORDER_OBSERVATION: { sequence: { start: '33', stop: '36' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                                                },
                                            },
                                        },
                                    },
                                },
                            },
                        },
                    },
                },
            },
            2.3: {
                sequences: [
                    {},
                    { identifier: 'MSH', sequence: '1', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: false },
                    { identifier: 'PID', sequence: '2', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: false },
                    { identifier: 'PV1', sequence: '3', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT_VISIT'] },
                    { identifier: 'PV2', sequence: '4', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT_VISIT'] },
                    { identifier: 'PTH', sequence: '5', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PATHWAY'] },
                    { identifier: 'NTE', sequence: '6', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATHWAY'] },
                    { identifier: 'VAR', sequence: '7', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATHWAY'] },
                    { identifier: 'ROL', sequence: '8', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PATHWAY', 'PATHWAY_ROLE'] },
                    { identifier: 'VAR', sequence: '9', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATHWAY', 'PATHWAY_ROLE'] },
                    { identifier: 'GOL', sequence: '10', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PATHWAY', 'GOAL'] },
                    { identifier: 'NTE', sequence: '11', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATHWAY', 'GOAL'] },
                    { identifier: 'VAR', sequence: '12', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATHWAY', 'GOAL'] },
                    { identifier: 'ROL', sequence: '13', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PATHWAY', 'GOAL', 'GOAL_ROLE'] },
                    { identifier: 'VAR', sequence: '14', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATHWAY', 'GOAL', 'GOAL_ROLE'] },
                    { identifier: 'OBX', sequence: '15', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PATHWAY', 'GOAL', 'GOAL_OBSERVATION'] },
                    { identifier: 'NTE', sequence: '16', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATHWAY', 'GOAL', 'GOAL_OBSERVATION'] },
                    { identifier: 'PRB', sequence: '17', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PATHWAY', 'GOAL', 'PROBLEM'] },
                    { identifier: 'NTE', sequence: '18', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATHWAY', 'GOAL', 'PROBLEM'] },
                    { identifier: 'VAR', sequence: '19', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATHWAY', 'GOAL', 'PROBLEM'] },
                    { identifier: 'ROL', sequence: '20', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PATHWAY', 'GOAL', 'PROBLEM', 'PROBLEM_ROLE'] },
                    { identifier: 'VAR', sequence: '21', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATHWAY', 'GOAL', 'PROBLEM', 'PROBLEM_ROLE'] },
                    {
                        identifier: 'OBX',
                        sequence: '22',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['PATHWAY', 'GOAL', 'PROBLEM', 'PROBLEM_OBSERVATION'],
                    },
                    {
                        identifier: 'NTE',
                        sequence: '23',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['PATHWAY', 'GOAL', 'PROBLEM', 'PROBLEM_OBSERVATION'],
                    },
                    { identifier: 'ORC', sequence: '24', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PATHWAY', 'GOAL', 'ORDER'] },
                    {
                        identifier: 'OBR',
                        sequence: '25',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['PATHWAY', 'GOAL', 'ORDER', 'ORDER_DETAIL', 'ORDER_DETAIL_SEGMENT'],
                    },
                    {
                        identifier: 'RQD',
                        sequence: '26',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['PATHWAY', 'GOAL', 'ORDER', 'ORDER_DETAIL', 'ORDER_DETAIL_SEGMENT'],
                    },
                    {
                        identifier: 'RQ1',
                        sequence: '27',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['PATHWAY', 'GOAL', 'ORDER', 'ORDER_DETAIL', 'ORDER_DETAIL_SEGMENT'],
                    },
                    {
                        identifier: 'RXO',
                        sequence: '28',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['PATHWAY', 'GOAL', 'ORDER', 'ORDER_DETAIL', 'ORDER_DETAIL_SEGMENT'],
                    },
                    {
                        identifier: 'ODS',
                        sequence: '29',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['PATHWAY', 'GOAL', 'ORDER', 'ORDER_DETAIL', 'ORDER_DETAIL_SEGMENT'],
                    },
                    {
                        identifier: 'ODT',
                        sequence: '30',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['PATHWAY', 'GOAL', 'ORDER', 'ORDER_DETAIL', 'ORDER_DETAIL_SEGMENT'],
                    },
                    { identifier: 'NTE', sequence: '31', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATHWAY', 'GOAL', 'ORDER', 'ORDER_DETAIL'] },
                    { identifier: 'VAR', sequence: '32', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATHWAY', 'GOAL', 'ORDER', 'ORDER_DETAIL'] },
                    {
                        identifier: 'OBX',
                        sequence: '33',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['PATHWAY', 'GOAL', 'ORDER', 'ORDER_DETAIL', 'ORDER_OBSERVATION'],
                    },
                    {
                        identifier: 'NTE',
                        sequence: '34',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['PATHWAY', 'GOAL', 'ORDER', 'ORDER_DETAIL', 'ORDER_OBSERVATION'],
                    },
                    {
                        identifier: 'VAR',
                        sequence: '35',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['PATHWAY', 'GOAL', 'ORDER', 'ORDER_DETAIL', 'ORDER_OBSERVATION'],
                    },
                ],
                groups: {
                    PATIENT_VISIT: { sequence: { start: '3', stop: '4' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, subgroup: {} },
                    PATHWAY: {
                        sequence: { start: '5', stop: null },
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 },
                        subgroup: {
                            PATHWAY_ROLE: { sequence: { start: '8', stop: '9' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                            GOAL: {
                                sequence: { start: '10', stop: null },
                                restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                                subgroup: {
                                    GOAL_ROLE: { sequence: { start: '13', stop: '14' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                                    GOAL_OBSERVATION: { sequence: { start: '15', stop: '16' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                                    PROBLEM: {
                                        sequence: { start: '17', stop: null },
                                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                                        subgroup: {
                                            PROBLEM_ROLE: { sequence: { start: '20', stop: '21' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                                            PROBLEM_OBSERVATION: { sequence: { start: '22', stop: '23' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                                        },
                                    },
                                    ORDER: {
                                        sequence: { start: '24', stop: null },
                                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                                        subgroup: {
                                            ORDER_DETAIL: {
                                                sequence: { start: null, stop: null },
                                                restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                                                subgroup: {
                                                    ORDER_DETAIL_SEGMENT: { sequence: { start: '25', stop: '30' }, restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, subgroup: {} },
                                                    ORDER_OBSERVATION: { sequence: { start: '33', stop: '35' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                                                },
                                            },
                                        },
                                    },
                                },
                            },
                        },
                    },
                },
            },
            '2.3.1': {
                sequences: { ref: '2.3' },
                groups: { ref: '2.3' },
            },
            2.4: {
                sequences: { ref: '2.3' },
                groups: { ref: '2.3' },
            },
            2.5: {
                sequences: [
                    {},
                    { identifier: 'MSH', sequence: '1', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: false },
                    { identifier: 'SFT', sequence: '2', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: false },
                    { identifier: 'PID', sequence: '3', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: false },
                    { identifier: 'PV1', sequence: '4', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT_VISIT'] },
                    { identifier: 'PV2', sequence: '5', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT_VISIT'] },
                    { identifier: 'PTH', sequence: '6', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PATHWAY'] },
                    { identifier: 'NTE', sequence: '7', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATHWAY'] },
                    { identifier: 'VAR', sequence: '8', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATHWAY'] },
                    { identifier: 'ROL', sequence: '9', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PATHWAY', 'PATHWAY_ROLE'] },
                    { identifier: 'VAR', sequence: '10', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATHWAY', 'PATHWAY_ROLE'] },
                    { identifier: 'GOL', sequence: '11', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PATHWAY', 'GOAL'] },
                    { identifier: 'NTE', sequence: '12', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATHWAY', 'GOAL'] },
                    { identifier: 'VAR', sequence: '13', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATHWAY', 'GOAL'] },
                    { identifier: 'ROL', sequence: '14', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PATHWAY', 'GOAL', 'GOAL_ROLE'] },
                    { identifier: 'VAR', sequence: '15', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATHWAY', 'GOAL', 'GOAL_ROLE'] },
                    { identifier: 'OBX', sequence: '16', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PATHWAY', 'GOAL', 'GOAL_OBSERVATION'] },
                    { identifier: 'NTE', sequence: '17', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATHWAY', 'GOAL', 'GOAL_OBSERVATION'] },
                    { identifier: 'PRB', sequence: '18', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PATHWAY', 'GOAL', 'PROBLEM'] },
                    { identifier: 'NTE', sequence: '19', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATHWAY', 'GOAL', 'PROBLEM'] },
                    { identifier: 'VAR', sequence: '20', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATHWAY', 'GOAL', 'PROBLEM'] },
                    { identifier: 'ROL', sequence: '21', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PATHWAY', 'GOAL', 'PROBLEM', 'PROBLEM_ROLE'] },
                    { identifier: 'VAR', sequence: '22', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATHWAY', 'GOAL', 'PROBLEM', 'PROBLEM_ROLE'] },
                    {
                        identifier: 'OBX',
                        sequence: '23',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['PATHWAY', 'GOAL', 'PROBLEM', 'PROBLEM_OBSERVATION'],
                    },
                    {
                        identifier: 'NTE',
                        sequence: '24',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['PATHWAY', 'GOAL', 'PROBLEM', 'PROBLEM_OBSERVATION'],
                    },
                    { identifier: 'ORC', sequence: '25', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PATHWAY', 'GOAL', 'ORDER'] },
                    {
                        identifier: 'OBR',
                        sequence: '26',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['PATHWAY', 'GOAL', 'ORDER', 'ORDER_DETAIL', 'ORDER_DETAIL_SEGMENT'],
                    },
                    {
                        identifier: 'RQD',
                        sequence: '27',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['PATHWAY', 'GOAL', 'ORDER', 'ORDER_DETAIL', 'ORDER_DETAIL_SEGMENT'],
                    },
                    {
                        identifier: 'RQ1',
                        sequence: '28',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['PATHWAY', 'GOAL', 'ORDER', 'ORDER_DETAIL', 'ORDER_DETAIL_SEGMENT'],
                    },
                    {
                        identifier: 'RXO',
                        sequence: '29',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['PATHWAY', 'GOAL', 'ORDER', 'ORDER_DETAIL', 'ORDER_DETAIL_SEGMENT'],
                    },
                    {
                        identifier: 'ODS',
                        sequence: '30',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['PATHWAY', 'GOAL', 'ORDER', 'ORDER_DETAIL', 'ORDER_DETAIL_SEGMENT'],
                    },
                    {
                        identifier: 'ODT',
                        sequence: '31',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['PATHWAY', 'GOAL', 'ORDER', 'ORDER_DETAIL', 'ORDER_DETAIL_SEGMENT'],
                    },
                    { identifier: 'NTE', sequence: '32', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATHWAY', 'GOAL', 'ORDER', 'ORDER_DETAIL'] },
                    { identifier: 'VAR', sequence: '33', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATHWAY', 'GOAL', 'ORDER', 'ORDER_DETAIL'] },
                    {
                        identifier: 'OBX',
                        sequence: '34',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['PATHWAY', 'GOAL', 'ORDER', 'ORDER_DETAIL', 'ORDER_OBSERVATION'],
                    },
                    {
                        identifier: 'NTE',
                        sequence: '35',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['PATHWAY', 'GOAL', 'ORDER', 'ORDER_DETAIL', 'ORDER_OBSERVATION'],
                    },
                    {
                        identifier: 'VAR',
                        sequence: '36',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['PATHWAY', 'GOAL', 'ORDER', 'ORDER_DETAIL', 'ORDER_OBSERVATION'],
                    },
                ],
                groups: {
                    PATIENT_VISIT: { sequence: { start: '4', stop: '5' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, subgroup: {} },
                    PATHWAY: {
                        sequence: { start: '6', stop: null },
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 },
                        subgroup: {
                            PATHWAY_ROLE: { sequence: { start: '9', stop: '10' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                            GOAL: {
                                sequence: { start: '11', stop: null },
                                restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                                subgroup: {
                                    GOAL_ROLE: { sequence: { start: '14', stop: '15' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                                    GOAL_OBSERVATION: { sequence: { start: '16', stop: '17' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                                    PROBLEM: {
                                        sequence: { start: '18', stop: null },
                                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                                        subgroup: {
                                            PROBLEM_ROLE: { sequence: { start: '21', stop: '22' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                                            PROBLEM_OBSERVATION: { sequence: { start: '23', stop: '24' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                                        },
                                    },
                                    ORDER: {
                                        sequence: { start: '25', stop: null },
                                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                                        subgroup: {
                                            ORDER_DETAIL: {
                                                sequence: { start: null, stop: null },
                                                restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                                                subgroup: {
                                                    ORDER_DETAIL_SEGMENT: { sequence: { start: '26', stop: '31' }, restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, subgroup: {} },
                                                    ORDER_OBSERVATION: { sequence: { start: '34', stop: '36' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                                                },
                                            },
                                        },
                                    },
                                },
                            },
                        },
                    },
                },
            },
            '2.5.1': {
                sequences: { ref: '2.5' },
                groups: { ref: '2.5' },
            },
            2.6: {
                sequences: [
                    {},
                    { identifier: 'MSH', sequence: '1', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: false },
                    { identifier: 'SFT', sequence: '2', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: false },
                    { identifier: 'UAC', sequence: '3', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: false },
                    { identifier: 'PID', sequence: '4', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: false },
                    { identifier: 'PV1', sequence: '5', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT_VISIT'] },
                    { identifier: 'PV2', sequence: '6', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT_VISIT'] },
                    { identifier: 'PTH', sequence: '7', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PATHWAY'] },
                    { identifier: 'NTE', sequence: '8', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATHWAY'] },
                    { identifier: 'VAR', sequence: '9', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATHWAY'] },
                    { identifier: 'ROL', sequence: '10', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PATHWAY', 'PATHWAY_ROLE'] },
                    { identifier: 'VAR', sequence: '11', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATHWAY', 'PATHWAY_ROLE'] },
                    { identifier: 'GOL', sequence: '12', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PATHWAY', 'GOAL'] },
                    { identifier: 'NTE', sequence: '13', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATHWAY', 'GOAL'] },
                    { identifier: 'VAR', sequence: '14', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATHWAY', 'GOAL'] },
                    { identifier: 'ROL', sequence: '15', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PATHWAY', 'GOAL', 'GOAL_ROLE'] },
                    { identifier: 'VAR', sequence: '16', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATHWAY', 'GOAL', 'GOAL_ROLE'] },
                    { identifier: 'OBX', sequence: '17', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PATHWAY', 'GOAL', 'GOAL_OBSERVATION'] },
                    { identifier: 'NTE', sequence: '18', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATHWAY', 'GOAL', 'GOAL_OBSERVATION'] },
                    { identifier: 'PRB', sequence: '19', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PATHWAY', 'GOAL', 'PROBLEM'] },
                    { identifier: 'NTE', sequence: '20', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATHWAY', 'GOAL', 'PROBLEM'] },
                    { identifier: 'VAR', sequence: '21', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATHWAY', 'GOAL', 'PROBLEM'] },
                    { identifier: 'ROL', sequence: '22', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PATHWAY', 'GOAL', 'PROBLEM', 'PROBLEM_ROLE'] },
                    { identifier: 'VAR', sequence: '23', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATHWAY', 'GOAL', 'PROBLEM', 'PROBLEM_ROLE'] },
                    {
                        identifier: 'OBX',
                        sequence: '24',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['PATHWAY', 'GOAL', 'PROBLEM', 'PROBLEM_OBSERVATION'],
                    },
                    {
                        identifier: 'NTE',
                        sequence: '25',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['PATHWAY', 'GOAL', 'PROBLEM', 'PROBLEM_OBSERVATION'],
                    },
                    { identifier: 'ORC', sequence: '26', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PATHWAY', 'GOAL', 'ORDER'] },
                    {
                        identifier: 'OBR',
                        sequence: '27',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['PATHWAY', 'GOAL', 'ORDER', 'ORDER_DETAIL', 'ORDER_DETAIL_SEGMENT'],
                    },
                    {
                        identifier: 'RQD',
                        sequence: '28',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['PATHWAY', 'GOAL', 'ORDER', 'ORDER_DETAIL', 'ORDER_DETAIL_SEGMENT'],
                    },
                    {
                        identifier: 'RQ1',
                        sequence: '29',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['PATHWAY', 'GOAL', 'ORDER', 'ORDER_DETAIL', 'ORDER_DETAIL_SEGMENT'],
                    },
                    {
                        identifier: 'RXO',
                        sequence: '30',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['PATHWAY', 'GOAL', 'ORDER', 'ORDER_DETAIL', 'ORDER_DETAIL_SEGMENT'],
                    },
                    {
                        identifier: 'ODS',
                        sequence: '31',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['PATHWAY', 'GOAL', 'ORDER', 'ORDER_DETAIL', 'ORDER_DETAIL_SEGMENT'],
                    },
                    {
                        identifier: 'ODT',
                        sequence: '32',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['PATHWAY', 'GOAL', 'ORDER', 'ORDER_DETAIL', 'ORDER_DETAIL_SEGMENT'],
                    },
                    { identifier: 'NTE', sequence: '33', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATHWAY', 'GOAL', 'ORDER', 'ORDER_DETAIL'] },
                    { identifier: 'VAR', sequence: '34', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATHWAY', 'GOAL', 'ORDER', 'ORDER_DETAIL'] },
                    {
                        identifier: 'OBX',
                        sequence: '35',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['PATHWAY', 'GOAL', 'ORDER', 'ORDER_DETAIL', 'ORDER_OBSERVATION'],
                    },
                    {
                        identifier: 'NTE',
                        sequence: '36',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['PATHWAY', 'GOAL', 'ORDER', 'ORDER_DETAIL', 'ORDER_OBSERVATION'],
                    },
                    {
                        identifier: 'VAR',
                        sequence: '37',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['PATHWAY', 'GOAL', 'ORDER', 'ORDER_DETAIL', 'ORDER_OBSERVATION'],
                    },
                ],
                groups: {
                    PATIENT_VISIT: { sequence: { start: '5', stop: '6' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, subgroup: {} },
                    PATHWAY: {
                        sequence: { start: '7', stop: null },
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 },
                        subgroup: {
                            PATHWAY_ROLE: { sequence: { start: '10', stop: '11' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                            GOAL: {
                                sequence: { start: '12', stop: null },
                                restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                                subgroup: {
                                    GOAL_ROLE: { sequence: { start: '15', stop: '16' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                                    GOAL_OBSERVATION: { sequence: { start: '17', stop: '18' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                                    PROBLEM: {
                                        sequence: { start: '19', stop: null },
                                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                                        subgroup: {
                                            PROBLEM_ROLE: { sequence: { start: '22', stop: '23' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                                            PROBLEM_OBSERVATION: { sequence: { start: '24', stop: '25' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                                        },
                                    },
                                    ORDER: {
                                        sequence: { start: '26', stop: null },
                                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                                        subgroup: {
                                            ORDER_DETAIL: {
                                                sequence: { start: null, stop: null },
                                                restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                                                subgroup: {
                                                    ORDER_DETAIL_SEGMENT: { sequence: { start: '27', stop: '32' }, restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, subgroup: {} },
                                                    ORDER_OBSERVATION: { sequence: { start: '35', stop: '37' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                                                },
                                            },
                                        },
                                    },
                                },
                            },
                        },
                    },
                },
            },
            2.7: {
                sequences: [
                    {},
                    { identifier: 'MSH', sequence: '1', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: false },
                    { identifier: 'SFT', sequence: '2', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: false },
                    { identifier: 'UAC', sequence: '3', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: false },
                    { identifier: 'PID', sequence: '4', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: false },
                    { identifier: 'PV1', sequence: '5', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT_VISIT'] },
                    { identifier: 'PV2', sequence: '6', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT_VISIT'] },
                    { identifier: 'PTH', sequence: '7', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PATHWAY'] },
                    { identifier: 'NTE', sequence: '8', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATHWAY'] },
                    { identifier: 'VAR', sequence: '9', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATHWAY'] },
                    { identifier: 'ROL', sequence: '10', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PATHWAY', 'PATHWAY_ROLE'] },
                    { identifier: 'VAR', sequence: '11', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATHWAY', 'PATHWAY_ROLE'] },
                    { identifier: 'GOL', sequence: '12', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PATHWAY', 'GOAL'] },
                    { identifier: 'NTE', sequence: '13', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATHWAY', 'GOAL'] },
                    { identifier: 'VAR', sequence: '14', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATHWAY', 'GOAL'] },
                    { identifier: 'ROL', sequence: '15', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PATHWAY', 'GOAL', 'GOAL_ROLE'] },
                    { identifier: 'VAR', sequence: '16', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATHWAY', 'GOAL', 'GOAL_ROLE'] },
                    { identifier: 'OBX', sequence: '17', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PATHWAY', 'GOAL', 'GOAL_OBSERVATION'] },
                    { identifier: 'NTE', sequence: '18', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATHWAY', 'GOAL', 'GOAL_OBSERVATION'] },
                    { identifier: 'PRB', sequence: '19', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PATHWAY', 'GOAL', 'PROBLEM'] },
                    { identifier: 'NTE', sequence: '20', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATHWAY', 'GOAL', 'PROBLEM'] },
                    { identifier: 'VAR', sequence: '21', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATHWAY', 'GOAL', 'PROBLEM'] },
                    { identifier: 'ROL', sequence: '22', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PATHWAY', 'GOAL', 'PROBLEM', 'PROBLEM_ROLE'] },
                    { identifier: 'VAR', sequence: '23', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATHWAY', 'GOAL', 'PROBLEM', 'PROBLEM_ROLE'] },
                    {
                        identifier: 'OBX',
                        sequence: '24',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['PATHWAY', 'GOAL', 'PROBLEM', 'PROBLEM_OBSERVATION'],
                    },
                    {
                        identifier: 'NTE',
                        sequence: '25',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['PATHWAY', 'GOAL', 'PROBLEM', 'PROBLEM_OBSERVATION'],
                    },
                    { identifier: 'ORC', sequence: '26', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PATHWAY', 'GOAL', 'ORDER'] },
                    { identifier: 'OBR', sequence: '27', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PATHWAY', 'GOAL', 'ORDER', 'ORDER_DETAIL'] },
                    { identifier: 'NTE', sequence: '28', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATHWAY', 'GOAL', 'ORDER', 'ORDER_DETAIL'] },
                    { identifier: 'VAR', sequence: '29', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATHWAY', 'GOAL', 'ORDER', 'ORDER_DETAIL'] },
                    {
                        identifier: 'OBX',
                        sequence: '30',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['PATHWAY', 'GOAL', 'ORDER', 'ORDER_DETAIL', 'ORDER_OBSERVATION'],
                    },
                    {
                        identifier: 'NTE',
                        sequence: '31',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['PATHWAY', 'GOAL', 'ORDER', 'ORDER_DETAIL', 'ORDER_OBSERVATION'],
                    },
                    {
                        identifier: 'VAR',
                        sequence: '32',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['PATHWAY', 'GOAL', 'ORDER', 'ORDER_DETAIL', 'ORDER_OBSERVATION'],
                    },
                ],
                groups: {
                    PATIENT_VISIT: { sequence: { start: '5', stop: '6' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, subgroup: {} },
                    PATHWAY: {
                        sequence: { start: '7', stop: null },
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 },
                        subgroup: {
                            PATHWAY_ROLE: { sequence: { start: '10', stop: '11' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                            GOAL: {
                                sequence: { start: '12', stop: null },
                                restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                                subgroup: {
                                    GOAL_ROLE: { sequence: { start: '15', stop: '16' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                                    GOAL_OBSERVATION: { sequence: { start: '17', stop: '18' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                                    PROBLEM: {
                                        sequence: { start: '19', stop: null },
                                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                                        subgroup: {
                                            PROBLEM_ROLE: { sequence: { start: '22', stop: '23' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                                            PROBLEM_OBSERVATION: { sequence: { start: '24', stop: '25' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                                        },
                                    },
                                    ORDER: {
                                        sequence: { start: '26', stop: null },
                                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                                        subgroup: {
                                            ORDER_DETAIL: {
                                                sequence: { start: '27', stop: null },
                                                restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                                                subgroup: {
                                                    ORDER_OBSERVATION: { sequence: { start: '30', stop: '32' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                                                },
                                            },
                                        },
                                    },
                                },
                            },
                        },
                    },
                },
            },
            '2.7.1': {
                sequences: { ref: '2.7' },
                groups: { ref: '2.7' },
            },
        },
        segments: {
            MSH: MSH,
            SFT: SFT,
            UAC: UAC,
            PID: PID,
            PV1: PV1,
            PV2: PV2,
            PTH: PTH,
            NTE: NTE,
            VAR: VAR,
            ROL: ROL,
            GOL: GOL,
            OBX: OBX,
            PRT: PRT,
            PRB: PRB,
            ORC: ORC,
            OBR: OBR,
            Hxx: Hxx,
            RQD: RQD,
            RQ1: RQ1,
            RXO: RXO,
            ODS: ODS,
            ODT: ODT,
        },
    };

    constructor(message, version = null) {
        super(message, version);
    }
}
