import { MSH, MSA, ERR, QRD, PID, PV1, PV2, PTH, NTE, VAR, ROL, PRB, OBX, GOL, ORC, OBR, RQD, RQ1, RXO, ODS, ODT, QAK, SFT, UAC } from '@healthcare-interoperability/hl7v2-segments';
import { TriggerEvent } from '@healthcare-interoperability/hl7v2-core';

export class PTR_PCF extends TriggerEvent {
    static TriggerEvent = 'PTR_PCF';
    static Structure = {
        versions: {
            2.3: {
                sequences: [
                    {},
                    { identifier: 'MSH', sequence: '1', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: false },
                    { identifier: 'MSA', sequence: '2', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: false },
                    { identifier: 'ERR', sequence: '3', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: false },
                    { identifier: 'QRD', sequence: '4', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: false },
                    { identifier: 'PID', sequence: '5', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT'] },
                    { identifier: 'PV1', sequence: '6', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT', 'PATIENT_VISIT'] },
                    { identifier: 'PV2', sequence: '7', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT', 'PATIENT_VISIT'] },
                    { identifier: 'PTH', sequence: '8', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT', 'PATHWAY'] },
                    { identifier: 'NTE', sequence: '9', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATIENT', 'PATHWAY'] },
                    { identifier: 'VAR', sequence: '10', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATIENT', 'PATHWAY'] },
                    { identifier: 'ROL', sequence: '11', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT', 'PATHWAY', 'PATHWAY_ROLE'] },
                    { identifier: 'VAR', sequence: '12', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATIENT', 'PATHWAY', 'PATHWAY_ROLE'] },
                    { identifier: 'PRB', sequence: '13', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT', 'PATHWAY', 'PROBLEM'] },
                    { identifier: 'NTE', sequence: '14', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATIENT', 'PATHWAY', 'PROBLEM'] },
                    { identifier: 'VAR', sequence: '15', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATIENT', 'PATHWAY', 'PROBLEM'] },
                    { identifier: 'ROL', sequence: '16', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT', 'PATHWAY', 'PROBLEM', 'PROBLEM_ROLE'] },
                    { identifier: 'VAR', sequence: '17', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATIENT', 'PATHWAY', 'PROBLEM', 'PROBLEM_ROLE'] },
                    {
                        identifier: 'OBX',
                        sequence: '18',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['PATIENT', 'PATHWAY', 'PROBLEM', 'PROBLEM_OBSERVATION'],
                    },
                    {
                        identifier: 'NTE',
                        sequence: '19',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['PATIENT', 'PATHWAY', 'PROBLEM', 'PROBLEM_OBSERVATION'],
                    },
                    { identifier: 'GOL', sequence: '20', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT', 'PATHWAY', 'PROBLEM', 'GOAL'] },
                    { identifier: 'NTE', sequence: '21', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATIENT', 'PATHWAY', 'PROBLEM', 'GOAL'] },
                    { identifier: 'VAR', sequence: '22', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATIENT', 'PATHWAY', 'PROBLEM', 'GOAL'] },
                    {
                        identifier: 'ROL',
                        sequence: '23',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['PATIENT', 'PATHWAY', 'PROBLEM', 'GOAL', 'GOAL_ROLE'],
                    },
                    {
                        identifier: 'VAR',
                        sequence: '24',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['PATIENT', 'PATHWAY', 'PROBLEM', 'GOAL', 'GOAL_ROLE'],
                    },
                    {
                        identifier: 'OBX',
                        sequence: '25',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['PATIENT', 'PATHWAY', 'PROBLEM', 'GOAL', 'GOAL_OBSERVATION'],
                    },
                    {
                        identifier: 'NTE',
                        sequence: '26',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['PATIENT', 'PATHWAY', 'PROBLEM', 'GOAL', 'GOAL_OBSERVATION'],
                    },
                    { identifier: 'ORC', sequence: '27', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT', 'PATHWAY', 'PROBLEM', 'ORDER'] },
                    {
                        identifier: 'OBR',
                        sequence: '28',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['PATIENT', 'PATHWAY', 'PROBLEM', 'ORDER', 'ORDER_DETAIL', 'ORDER_DETAIL_SEGMENT'],
                    },
                    {
                        identifier: 'RQD',
                        sequence: '29',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['PATIENT', 'PATHWAY', 'PROBLEM', 'ORDER', 'ORDER_DETAIL', 'ORDER_DETAIL_SEGMENT'],
                    },
                    {
                        identifier: 'RQ1',
                        sequence: '30',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['PATIENT', 'PATHWAY', 'PROBLEM', 'ORDER', 'ORDER_DETAIL', 'ORDER_DETAIL_SEGMENT'],
                    },
                    {
                        identifier: 'RXO',
                        sequence: '31',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['PATIENT', 'PATHWAY', 'PROBLEM', 'ORDER', 'ORDER_DETAIL', 'ORDER_DETAIL_SEGMENT'],
                    },
                    {
                        identifier: 'ODS',
                        sequence: '32',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['PATIENT', 'PATHWAY', 'PROBLEM', 'ORDER', 'ORDER_DETAIL', 'ORDER_DETAIL_SEGMENT'],
                    },
                    {
                        identifier: 'ODT',
                        sequence: '33',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['PATIENT', 'PATHWAY', 'PROBLEM', 'ORDER', 'ORDER_DETAIL', 'ORDER_DETAIL_SEGMENT'],
                    },
                    {
                        identifier: 'NTE',
                        sequence: '34',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['PATIENT', 'PATHWAY', 'PROBLEM', 'ORDER', 'ORDER_DETAIL'],
                    },
                    {
                        identifier: 'VAR',
                        sequence: '35',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['PATIENT', 'PATHWAY', 'PROBLEM', 'ORDER', 'ORDER_DETAIL'],
                    },
                    {
                        identifier: 'OBX',
                        sequence: '36',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['PATIENT', 'PATHWAY', 'PROBLEM', 'ORDER', 'ORDER_DETAIL', 'ORDER_OBSERVATION'],
                    },
                    {
                        identifier: 'NTE',
                        sequence: '37',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['PATIENT', 'PATHWAY', 'PROBLEM', 'ORDER', 'ORDER_DETAIL', 'ORDER_OBSERVATION'],
                    },
                    {
                        identifier: 'VAR',
                        sequence: '38',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['PATIENT', 'PATHWAY', 'PROBLEM', 'ORDER', 'ORDER_DETAIL', 'ORDER_OBSERVATION'],
                    },
                ],
                groups: {
                    PATIENT: {
                        sequence: { start: '5', stop: null },
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 },
                        subgroup: {
                            PATIENT_VISIT: { sequence: { start: '6', stop: '7' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, subgroup: {} },
                            PATHWAY: {
                                sequence: { start: '8', stop: null },
                                restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 },
                                subgroup: {
                                    PATHWAY_ROLE: { sequence: { start: '11', stop: '12' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                                    PROBLEM: {
                                        sequence: { start: '13', stop: null },
                                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                                        subgroup: {
                                            PROBLEM_ROLE: { sequence: { start: '16', stop: '17' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                                            PROBLEM_OBSERVATION: { sequence: { start: '18', stop: '19' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                                            GOAL: {
                                                sequence: { start: '20', stop: null },
                                                restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                                                subgroup: {
                                                    GOAL_ROLE: { sequence: { start: '23', stop: '24' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                                                    GOAL_OBSERVATION: { sequence: { start: '25', stop: '26' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                                                },
                                            },
                                            ORDER: {
                                                sequence: { start: '27', stop: null },
                                                restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                                                subgroup: {
                                                    ORDER_DETAIL: {
                                                        sequence: { start: null, stop: null },
                                                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                                                        subgroup: {
                                                            ORDER_DETAIL_SEGMENT: {
                                                                sequence: { start: '28', stop: '33' },
                                                                restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                                                                subgroup: {},
                                                            },
                                                            ORDER_OBSERVATION: { sequence: { start: '36', stop: '38' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                                                        },
                                                    },
                                                },
                                            },
                                        },
                                    },
                                },
                            },
                        },
                    },
                },
            },
            '2.3.1': {
                sequences: [
                    {},
                    { identifier: 'MSH', sequence: '1', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: false },
                    { identifier: 'MSA', sequence: '2', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: false },
                    { identifier: 'ERR', sequence: '3', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: false },
                    { identifier: 'QAK', sequence: '4', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: false },
                    { identifier: 'QRD', sequence: '5', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: false },
                    { identifier: 'PID', sequence: '6', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT'] },
                    { identifier: 'PV1', sequence: '7', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT', 'PATIENT_VISIT'] },
                    { identifier: 'PV2', sequence: '8', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT', 'PATIENT_VISIT'] },
                    { identifier: 'PTH', sequence: '9', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT', 'PATHWAY'] },
                    { identifier: 'NTE', sequence: '10', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATIENT', 'PATHWAY'] },
                    { identifier: 'VAR', sequence: '11', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATIENT', 'PATHWAY'] },
                    { identifier: 'ROL', sequence: '12', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT', 'PATHWAY', 'PATHWAY_ROLE'] },
                    { identifier: 'VAR', sequence: '13', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATIENT', 'PATHWAY', 'PATHWAY_ROLE'] },
                    { identifier: 'PRB', sequence: '14', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT', 'PATHWAY', 'PROBLEM'] },
                    { identifier: 'NTE', sequence: '15', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATIENT', 'PATHWAY', 'PROBLEM'] },
                    { identifier: 'VAR', sequence: '16', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATIENT', 'PATHWAY', 'PROBLEM'] },
                    { identifier: 'ROL', sequence: '17', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT', 'PATHWAY', 'PROBLEM', 'PROBLEM_ROLE'] },
                    { identifier: 'VAR', sequence: '18', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATIENT', 'PATHWAY', 'PROBLEM', 'PROBLEM_ROLE'] },
                    {
                        identifier: 'OBX',
                        sequence: '19',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['PATIENT', 'PATHWAY', 'PROBLEM', 'PROBLEM_OBSERVATION'],
                    },
                    {
                        identifier: 'NTE',
                        sequence: '20',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['PATIENT', 'PATHWAY', 'PROBLEM', 'PROBLEM_OBSERVATION'],
                    },
                    { identifier: 'GOL', sequence: '21', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT', 'PATHWAY', 'PROBLEM', 'GOAL'] },
                    { identifier: 'NTE', sequence: '22', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATIENT', 'PATHWAY', 'PROBLEM', 'GOAL'] },
                    { identifier: 'VAR', sequence: '23', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATIENT', 'PATHWAY', 'PROBLEM', 'GOAL'] },
                    {
                        identifier: 'ROL',
                        sequence: '24',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['PATIENT', 'PATHWAY', 'PROBLEM', 'GOAL', 'GOAL_ROLE'],
                    },
                    {
                        identifier: 'VAR',
                        sequence: '25',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['PATIENT', 'PATHWAY', 'PROBLEM', 'GOAL', 'GOAL_ROLE'],
                    },
                    {
                        identifier: 'OBX',
                        sequence: '26',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['PATIENT', 'PATHWAY', 'PROBLEM', 'GOAL', 'GOAL_OBSERVATION'],
                    },
                    {
                        identifier: 'NTE',
                        sequence: '27',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['PATIENT', 'PATHWAY', 'PROBLEM', 'GOAL', 'GOAL_OBSERVATION'],
                    },
                    { identifier: 'ORC', sequence: '28', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT', 'PATHWAY', 'PROBLEM', 'ORDER'] },
                    {
                        identifier: 'OBR',
                        sequence: '29',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['PATIENT', 'PATHWAY', 'PROBLEM', 'ORDER', 'ORDER_DETAIL', 'ORDER_DETAIL_SEGMENT'],
                    },
                    {
                        identifier: 'RQD',
                        sequence: '30',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['PATIENT', 'PATHWAY', 'PROBLEM', 'ORDER', 'ORDER_DETAIL', 'ORDER_DETAIL_SEGMENT'],
                    },
                    {
                        identifier: 'RQ1',
                        sequence: '31',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['PATIENT', 'PATHWAY', 'PROBLEM', 'ORDER', 'ORDER_DETAIL', 'ORDER_DETAIL_SEGMENT'],
                    },
                    {
                        identifier: 'RXO',
                        sequence: '32',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['PATIENT', 'PATHWAY', 'PROBLEM', 'ORDER', 'ORDER_DETAIL', 'ORDER_DETAIL_SEGMENT'],
                    },
                    {
                        identifier: 'ODS',
                        sequence: '33',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['PATIENT', 'PATHWAY', 'PROBLEM', 'ORDER', 'ORDER_DETAIL', 'ORDER_DETAIL_SEGMENT'],
                    },
                    {
                        identifier: 'ODT',
                        sequence: '34',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['PATIENT', 'PATHWAY', 'PROBLEM', 'ORDER', 'ORDER_DETAIL', 'ORDER_DETAIL_SEGMENT'],
                    },
                    {
                        identifier: 'NTE',
                        sequence: '35',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['PATIENT', 'PATHWAY', 'PROBLEM', 'ORDER', 'ORDER_DETAIL'],
                    },
                    {
                        identifier: 'VAR',
                        sequence: '36',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['PATIENT', 'PATHWAY', 'PROBLEM', 'ORDER', 'ORDER_DETAIL'],
                    },
                    {
                        identifier: 'OBX',
                        sequence: '37',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['PATIENT', 'PATHWAY', 'PROBLEM', 'ORDER', 'ORDER_DETAIL', 'ORDER_OBSERVATION'],
                    },
                    {
                        identifier: 'NTE',
                        sequence: '38',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['PATIENT', 'PATHWAY', 'PROBLEM', 'ORDER', 'ORDER_DETAIL', 'ORDER_OBSERVATION'],
                    },
                    {
                        identifier: 'VAR',
                        sequence: '39',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['PATIENT', 'PATHWAY', 'PROBLEM', 'ORDER', 'ORDER_DETAIL', 'ORDER_OBSERVATION'],
                    },
                ],
                groups: {
                    PATIENT: {
                        sequence: { start: '6', stop: null },
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 },
                        subgroup: {
                            PATIENT_VISIT: { sequence: { start: '7', stop: '8' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, subgroup: {} },
                            PATHWAY: {
                                sequence: { start: '9', stop: null },
                                restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 },
                                subgroup: {
                                    PATHWAY_ROLE: { sequence: { start: '12', stop: '13' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                                    PROBLEM: {
                                        sequence: { start: '14', stop: null },
                                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                                        subgroup: {
                                            PROBLEM_ROLE: { sequence: { start: '17', stop: '18' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                                            PROBLEM_OBSERVATION: { sequence: { start: '19', stop: '20' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                                            GOAL: {
                                                sequence: { start: '21', stop: null },
                                                restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                                                subgroup: {
                                                    GOAL_ROLE: { sequence: { start: '24', stop: '25' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                                                    GOAL_OBSERVATION: { sequence: { start: '26', stop: '27' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                                                },
                                            },
                                            ORDER: {
                                                sequence: { start: '28', stop: null },
                                                restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                                                subgroup: {
                                                    ORDER_DETAIL: {
                                                        sequence: { start: null, stop: null },
                                                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                                                        subgroup: {
                                                            ORDER_DETAIL_SEGMENT: {
                                                                sequence: { start: '29', stop: '34' },
                                                                restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                                                                subgroup: {},
                                                            },
                                                            ORDER_OBSERVATION: { sequence: { start: '37', stop: '39' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                                                        },
                                                    },
                                                },
                                            },
                                        },
                                    },
                                },
                            },
                        },
                    },
                },
            },
            2.4: {
                sequences: { ref: '2.3.1' },
                groups: { ref: '2.3.1' },
            },
            2.5: {
                sequences: [
                    {},
                    { identifier: 'MSH', sequence: '1', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: false },
                    { identifier: 'SFT', sequence: '2', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: false },
                    { identifier: 'MSA', sequence: '3', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: false },
                    { identifier: 'ERR', sequence: '4', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: false },
                    { identifier: 'QAK', sequence: '5', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: false },
                    { identifier: 'QRD', sequence: '6', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: false },
                    { identifier: 'PID', sequence: '7', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT'] },
                    { identifier: 'PV1', sequence: '8', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT', 'PATIENT_VISIT'] },
                    { identifier: 'PV2', sequence: '9', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT', 'PATIENT_VISIT'] },
                    { identifier: 'PTH', sequence: '10', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT', 'PATHWAY'] },
                    { identifier: 'NTE', sequence: '11', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATIENT', 'PATHWAY'] },
                    { identifier: 'VAR', sequence: '12', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATIENT', 'PATHWAY'] },
                    { identifier: 'ROL', sequence: '13', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT', 'PATHWAY', 'PATHWAY_ROLE'] },
                    { identifier: 'VAR', sequence: '14', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATIENT', 'PATHWAY', 'PATHWAY_ROLE'] },
                    { identifier: 'PRB', sequence: '15', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT', 'PATHWAY', 'PROBLEM'] },
                    { identifier: 'NTE', sequence: '16', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATIENT', 'PATHWAY', 'PROBLEM'] },
                    { identifier: 'VAR', sequence: '17', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATIENT', 'PATHWAY', 'PROBLEM'] },
                    { identifier: 'ROL', sequence: '18', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT', 'PATHWAY', 'PROBLEM', 'PROBLEM_ROLE'] },
                    { identifier: 'VAR', sequence: '19', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATIENT', 'PATHWAY', 'PROBLEM', 'PROBLEM_ROLE'] },
                    {
                        identifier: 'OBX',
                        sequence: '20',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['PATIENT', 'PATHWAY', 'PROBLEM', 'PROBLEM_OBSERVATION'],
                    },
                    {
                        identifier: 'NTE',
                        sequence: '21',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['PATIENT', 'PATHWAY', 'PROBLEM', 'PROBLEM_OBSERVATION'],
                    },
                    { identifier: 'GOL', sequence: '22', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT', 'PATHWAY', 'PROBLEM', 'GOAL'] },
                    { identifier: 'NTE', sequence: '23', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATIENT', 'PATHWAY', 'PROBLEM', 'GOAL'] },
                    { identifier: 'VAR', sequence: '24', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATIENT', 'PATHWAY', 'PROBLEM', 'GOAL'] },
                    {
                        identifier: 'ROL',
                        sequence: '25',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['PATIENT', 'PATHWAY', 'PROBLEM', 'GOAL', 'GOAL_ROLE'],
                    },
                    {
                        identifier: 'VAR',
                        sequence: '26',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['PATIENT', 'PATHWAY', 'PROBLEM', 'GOAL', 'GOAL_ROLE'],
                    },
                    {
                        identifier: 'OBX',
                        sequence: '27',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['PATIENT', 'PATHWAY', 'PROBLEM', 'GOAL', 'GOAL_OBSERVATION'],
                    },
                    {
                        identifier: 'NTE',
                        sequence: '28',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['PATIENT', 'PATHWAY', 'PROBLEM', 'GOAL', 'GOAL_OBSERVATION'],
                    },
                    { identifier: 'ORC', sequence: '29', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT', 'PATHWAY', 'PROBLEM', 'ORDER'] },
                    {
                        identifier: 'OBR',
                        sequence: '30',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['PATIENT', 'PATHWAY', 'PROBLEM', 'ORDER', 'ORDER_DETAIL', 'ORDER_DETAIL_SEGMENT'],
                    },
                    {
                        identifier: 'RQD',
                        sequence: '31',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['PATIENT', 'PATHWAY', 'PROBLEM', 'ORDER', 'ORDER_DETAIL', 'ORDER_DETAIL_SEGMENT'],
                    },
                    {
                        identifier: 'RQ1',
                        sequence: '32',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['PATIENT', 'PATHWAY', 'PROBLEM', 'ORDER', 'ORDER_DETAIL', 'ORDER_DETAIL_SEGMENT'],
                    },
                    {
                        identifier: 'RXO',
                        sequence: '33',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['PATIENT', 'PATHWAY', 'PROBLEM', 'ORDER', 'ORDER_DETAIL', 'ORDER_DETAIL_SEGMENT'],
                    },
                    {
                        identifier: 'ODS',
                        sequence: '34',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['PATIENT', 'PATHWAY', 'PROBLEM', 'ORDER', 'ORDER_DETAIL', 'ORDER_DETAIL_SEGMENT'],
                    },
                    {
                        identifier: 'ODT',
                        sequence: '35',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['PATIENT', 'PATHWAY', 'PROBLEM', 'ORDER', 'ORDER_DETAIL', 'ORDER_DETAIL_SEGMENT'],
                    },
                    {
                        identifier: 'NTE',
                        sequence: '36',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['PATIENT', 'PATHWAY', 'PROBLEM', 'ORDER', 'ORDER_DETAIL'],
                    },
                    {
                        identifier: 'VAR',
                        sequence: '37',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['PATIENT', 'PATHWAY', 'PROBLEM', 'ORDER', 'ORDER_DETAIL'],
                    },
                    {
                        identifier: 'OBX',
                        sequence: '38',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['PATIENT', 'PATHWAY', 'PROBLEM', 'ORDER', 'ORDER_DETAIL', 'ORDER_OBSERVATION'],
                    },
                    {
                        identifier: 'NTE',
                        sequence: '39',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['PATIENT', 'PATHWAY', 'PROBLEM', 'ORDER', 'ORDER_DETAIL', 'ORDER_OBSERVATION'],
                    },
                    {
                        identifier: 'VAR',
                        sequence: '40',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['PATIENT', 'PATHWAY', 'PROBLEM', 'ORDER', 'ORDER_DETAIL', 'ORDER_OBSERVATION'],
                    },
                ],
                groups: {
                    PATIENT: {
                        sequence: { start: '7', stop: null },
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 },
                        subgroup: {
                            PATIENT_VISIT: { sequence: { start: '8', stop: '9' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, subgroup: {} },
                            PATHWAY: {
                                sequence: { start: '10', stop: null },
                                restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 },
                                subgroup: {
                                    PATHWAY_ROLE: { sequence: { start: '13', stop: '14' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                                    PROBLEM: {
                                        sequence: { start: '15', stop: null },
                                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                                        subgroup: {
                                            PROBLEM_ROLE: { sequence: { start: '18', stop: '19' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                                            PROBLEM_OBSERVATION: { sequence: { start: '20', stop: '21' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                                            GOAL: {
                                                sequence: { start: '22', stop: null },
                                                restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                                                subgroup: {
                                                    GOAL_ROLE: { sequence: { start: '25', stop: '26' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                                                    GOAL_OBSERVATION: { sequence: { start: '27', stop: '28' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                                                },
                                            },
                                            ORDER: {
                                                sequence: { start: '29', stop: null },
                                                restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                                                subgroup: {
                                                    ORDER_DETAIL: {
                                                        sequence: { start: null, stop: null },
                                                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                                                        subgroup: {
                                                            ORDER_DETAIL_SEGMENT: {
                                                                sequence: { start: '30', stop: '35' },
                                                                restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                                                                subgroup: {},
                                                            },
                                                            ORDER_OBSERVATION: { sequence: { start: '38', stop: '40' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                                                        },
                                                    },
                                                },
                                            },
                                        },
                                    },
                                },
                            },
                        },
                    },
                },
            },
            '2.5.1': {
                sequences: { ref: '2.5' },
                groups: { ref: '2.5' },
            },
            2.6: {
                sequences: [
                    {},
                    { identifier: 'MSH', sequence: '1', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: false },
                    { identifier: 'SFT', sequence: '2', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: false },
                    { identifier: 'UAC', sequence: '3', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: false },
                    { identifier: 'MSA', sequence: '4', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: false },
                    { identifier: 'ERR', sequence: '5', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: false },
                    { identifier: 'QAK', sequence: '6', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: false },
                    { identifier: 'QRD', sequence: '7', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: false },
                    { identifier: 'PID', sequence: '8', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT'] },
                    { identifier: 'PV1', sequence: '9', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT', 'PATIENT_VISIT'] },
                    { identifier: 'PV2', sequence: '10', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT', 'PATIENT_VISIT'] },
                    { identifier: 'PTH', sequence: '11', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT', 'PATHWAY'] },
                    { identifier: 'NTE', sequence: '12', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATIENT', 'PATHWAY'] },
                    { identifier: 'VAR', sequence: '13', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATIENT', 'PATHWAY'] },
                    { identifier: 'ROL', sequence: '14', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT', 'PATHWAY', 'PATHWAY_ROLE'] },
                    { identifier: 'VAR', sequence: '15', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATIENT', 'PATHWAY', 'PATHWAY_ROLE'] },
                    { identifier: 'PRB', sequence: '16', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT', 'PATHWAY', 'PROBLEM'] },
                    { identifier: 'NTE', sequence: '17', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATIENT', 'PATHWAY', 'PROBLEM'] },
                    { identifier: 'VAR', sequence: '18', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATIENT', 'PATHWAY', 'PROBLEM'] },
                    { identifier: 'ROL', sequence: '19', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT', 'PATHWAY', 'PROBLEM', 'PROBLEM_ROLE'] },
                    { identifier: 'VAR', sequence: '20', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATIENT', 'PATHWAY', 'PROBLEM', 'PROBLEM_ROLE'] },
                    {
                        identifier: 'OBX',
                        sequence: '21',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['PATIENT', 'PATHWAY', 'PROBLEM', 'PROBLEM_OBSERVATION'],
                    },
                    {
                        identifier: 'NTE',
                        sequence: '22',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['PATIENT', 'PATHWAY', 'PROBLEM', 'PROBLEM_OBSERVATION'],
                    },
                    { identifier: 'GOL', sequence: '23', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT', 'PATHWAY', 'PROBLEM', 'GOAL'] },
                    { identifier: 'NTE', sequence: '24', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATIENT', 'PATHWAY', 'PROBLEM', 'GOAL'] },
                    { identifier: 'VAR', sequence: '25', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATIENT', 'PATHWAY', 'PROBLEM', 'GOAL'] },
                    {
                        identifier: 'ROL',
                        sequence: '26',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['PATIENT', 'PATHWAY', 'PROBLEM', 'GOAL', 'GOAL_ROLE'],
                    },
                    {
                        identifier: 'VAR',
                        sequence: '27',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['PATIENT', 'PATHWAY', 'PROBLEM', 'GOAL', 'GOAL_ROLE'],
                    },
                    {
                        identifier: 'OBX',
                        sequence: '28',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['PATIENT', 'PATHWAY', 'PROBLEM', 'GOAL', 'GOAL_OBSERVATION'],
                    },
                    {
                        identifier: 'NTE',
                        sequence: '29',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['PATIENT', 'PATHWAY', 'PROBLEM', 'GOAL', 'GOAL_OBSERVATION'],
                    },
                    { identifier: 'ORC', sequence: '30', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT', 'PATHWAY', 'PROBLEM', 'ORDER'] },
                    {
                        identifier: 'OBR',
                        sequence: '31',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['PATIENT', 'PATHWAY', 'PROBLEM', 'ORDER', 'ORDER_DETAIL', 'ORDER_DETAIL_SEGMENT'],
                    },
                    {
                        identifier: 'RQD',
                        sequence: '32',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['PATIENT', 'PATHWAY', 'PROBLEM', 'ORDER', 'ORDER_DETAIL', 'ORDER_DETAIL_SEGMENT'],
                    },
                    {
                        identifier: 'RQ1',
                        sequence: '33',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['PATIENT', 'PATHWAY', 'PROBLEM', 'ORDER', 'ORDER_DETAIL', 'ORDER_DETAIL_SEGMENT'],
                    },
                    {
                        identifier: 'RXO',
                        sequence: '34',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['PATIENT', 'PATHWAY', 'PROBLEM', 'ORDER', 'ORDER_DETAIL', 'ORDER_DETAIL_SEGMENT'],
                    },
                    {
                        identifier: 'ODS',
                        sequence: '35',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['PATIENT', 'PATHWAY', 'PROBLEM', 'ORDER', 'ORDER_DETAIL', 'ORDER_DETAIL_SEGMENT'],
                    },
                    {
                        identifier: 'ODT',
                        sequence: '36',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['PATIENT', 'PATHWAY', 'PROBLEM', 'ORDER', 'ORDER_DETAIL', 'ORDER_DETAIL_SEGMENT'],
                    },
                    {
                        identifier: 'NTE',
                        sequence: '37',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['PATIENT', 'PATHWAY', 'PROBLEM', 'ORDER', 'ORDER_DETAIL'],
                    },
                    {
                        identifier: 'VAR',
                        sequence: '38',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['PATIENT', 'PATHWAY', 'PROBLEM', 'ORDER', 'ORDER_DETAIL'],
                    },
                    {
                        identifier: 'OBX',
                        sequence: '39',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['PATIENT', 'PATHWAY', 'PROBLEM', 'ORDER', 'ORDER_DETAIL', 'ORDER_OBSERVATION'],
                    },
                    {
                        identifier: 'NTE',
                        sequence: '40',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['PATIENT', 'PATHWAY', 'PROBLEM', 'ORDER', 'ORDER_DETAIL', 'ORDER_OBSERVATION'],
                    },
                    {
                        identifier: 'VAR',
                        sequence: '41',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['PATIENT', 'PATHWAY', 'PROBLEM', 'ORDER', 'ORDER_DETAIL', 'ORDER_OBSERVATION'],
                    },
                ],
                groups: {
                    PATIENT: {
                        sequence: { start: '8', stop: null },
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 },
                        subgroup: {
                            PATIENT_VISIT: { sequence: { start: '9', stop: '10' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, subgroup: {} },
                            PATHWAY: {
                                sequence: { start: '11', stop: null },
                                restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 },
                                subgroup: {
                                    PATHWAY_ROLE: { sequence: { start: '14', stop: '15' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                                    PROBLEM: {
                                        sequence: { start: '16', stop: null },
                                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                                        subgroup: {
                                            PROBLEM_ROLE: { sequence: { start: '19', stop: '20' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                                            PROBLEM_OBSERVATION: { sequence: { start: '21', stop: '22' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                                            GOAL: {
                                                sequence: { start: '23', stop: null },
                                                restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                                                subgroup: {
                                                    GOAL_ROLE: { sequence: { start: '26', stop: '27' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                                                    GOAL_OBSERVATION: { sequence: { start: '28', stop: '29' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                                                },
                                            },
                                            ORDER: {
                                                sequence: { start: '30', stop: null },
                                                restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                                                subgroup: {
                                                    ORDER_DETAIL: {
                                                        sequence: { start: null, stop: null },
                                                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                                                        subgroup: {
                                                            ORDER_DETAIL_SEGMENT: {
                                                                sequence: { start: '31', stop: '36' },
                                                                restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                                                                subgroup: {},
                                                            },
                                                            ORDER_OBSERVATION: { sequence: { start: '39', stop: '41' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                                                        },
                                                    },
                                                },
                                            },
                                        },
                                    },
                                },
                            },
                        },
                    },
                },
            },
            2.7: {
                sequences: [
                    {},
                    { identifier: 'MSH', sequence: '1', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: false },
                    { identifier: 'SFT', sequence: '2', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: false },
                    { identifier: 'UAC', sequence: '3', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: false },
                    { identifier: 'MSA', sequence: '4', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: false },
                    { identifier: 'ERR', sequence: '5', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: false },
                    { identifier: 'QAK', sequence: '6', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: false },
                    { identifier: 'QRD', sequence: '7', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: false },
                    { identifier: 'PID', sequence: '8', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT'] },
                    { identifier: 'PV1', sequence: '9', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT', 'PATIENT_VISIT'] },
                    { identifier: 'PV2', sequence: '10', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT', 'PATIENT_VISIT'] },
                    { identifier: 'PTH', sequence: '11', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT', 'PATHWAY'] },
                    { identifier: 'NTE', sequence: '12', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATIENT', 'PATHWAY'] },
                    { identifier: 'VAR', sequence: '13', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATIENT', 'PATHWAY'] },
                    { identifier: 'ROL', sequence: '14', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT', 'PATHWAY', 'PATHWAY_ROLE'] },
                    { identifier: 'VAR', sequence: '15', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATIENT', 'PATHWAY', 'PATHWAY_ROLE'] },
                    { identifier: 'PRB', sequence: '16', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT', 'PATHWAY', 'PROBLEM'] },
                    { identifier: 'NTE', sequence: '17', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATIENT', 'PATHWAY', 'PROBLEM'] },
                    { identifier: 'VAR', sequence: '18', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATIENT', 'PATHWAY', 'PROBLEM'] },
                    { identifier: 'ROL', sequence: '19', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT', 'PATHWAY', 'PROBLEM', 'PROBLEM_ROLE'] },
                    { identifier: 'VAR', sequence: '20', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATIENT', 'PATHWAY', 'PROBLEM', 'PROBLEM_ROLE'] },
                    {
                        identifier: 'OBX',
                        sequence: '21',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['PATIENT', 'PATHWAY', 'PROBLEM', 'PROBLEM_OBSERVATION'],
                    },
                    {
                        identifier: 'NTE',
                        sequence: '22',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['PATIENT', 'PATHWAY', 'PROBLEM', 'PROBLEM_OBSERVATION'],
                    },
                    { identifier: 'GOL', sequence: '23', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT', 'PATHWAY', 'PROBLEM', 'GOAL'] },
                    { identifier: 'NTE', sequence: '24', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATIENT', 'PATHWAY', 'PROBLEM', 'GOAL'] },
                    { identifier: 'VAR', sequence: '25', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['PATIENT', 'PATHWAY', 'PROBLEM', 'GOAL'] },
                    {
                        identifier: 'ROL',
                        sequence: '26',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['PATIENT', 'PATHWAY', 'PROBLEM', 'GOAL', 'GOAL_ROLE'],
                    },
                    {
                        identifier: 'VAR',
                        sequence: '27',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['PATIENT', 'PATHWAY', 'PROBLEM', 'GOAL', 'GOAL_ROLE'],
                    },
                    {
                        identifier: 'OBX',
                        sequence: '28',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['PATIENT', 'PATHWAY', 'PROBLEM', 'GOAL', 'GOAL_OBSERVATION'],
                    },
                    {
                        identifier: 'NTE',
                        sequence: '29',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['PATIENT', 'PATHWAY', 'PROBLEM', 'GOAL', 'GOAL_OBSERVATION'],
                    },
                    { identifier: 'ORC', sequence: '30', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['PATIENT', 'PATHWAY', 'PROBLEM', 'ORDER'] },
                    {
                        identifier: 'OBR',
                        sequence: '31',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['PATIENT', 'PATHWAY', 'PROBLEM', 'ORDER', 'ORDER_DETAIL'],
                    },
                    {
                        identifier: 'NTE',
                        sequence: '32',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['PATIENT', 'PATHWAY', 'PROBLEM', 'ORDER', 'ORDER_DETAIL'],
                    },
                    {
                        identifier: 'VAR',
                        sequence: '33',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['PATIENT', 'PATHWAY', 'PROBLEM', 'ORDER', 'ORDER_DETAIL'],
                    },
                    {
                        identifier: 'OBX',
                        sequence: '34',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['PATIENT', 'PATHWAY', 'PROBLEM', 'ORDER', 'ORDER_DETAIL', 'ORDER_OBSERVATION'],
                    },
                    {
                        identifier: 'NTE',
                        sequence: '35',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['PATIENT', 'PATHWAY', 'PROBLEM', 'ORDER', 'ORDER_DETAIL', 'ORDER_OBSERVATION'],
                    },
                    {
                        identifier: 'VAR',
                        sequence: '36',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['PATIENT', 'PATHWAY', 'PROBLEM', 'ORDER', 'ORDER_DETAIL', 'ORDER_OBSERVATION'],
                    },
                ],
                groups: {
                    PATIENT: {
                        sequence: { start: '8', stop: null },
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 },
                        subgroup: {
                            PATIENT_VISIT: { sequence: { start: '9', stop: '10' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, subgroup: {} },
                            PATHWAY: {
                                sequence: { start: '11', stop: null },
                                restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 },
                                subgroup: {
                                    PATHWAY_ROLE: { sequence: { start: '14', stop: '15' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                                    PROBLEM: {
                                        sequence: { start: '16', stop: null },
                                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                                        subgroup: {
                                            PROBLEM_ROLE: { sequence: { start: '19', stop: '20' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                                            PROBLEM_OBSERVATION: { sequence: { start: '21', stop: '22' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                                            GOAL: {
                                                sequence: { start: '23', stop: null },
                                                restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                                                subgroup: {
                                                    GOAL_ROLE: { sequence: { start: '26', stop: '27' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                                                    GOAL_OBSERVATION: { sequence: { start: '28', stop: '29' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                                                },
                                            },
                                            ORDER: {
                                                sequence: { start: '30', stop: null },
                                                restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                                                subgroup: {
                                                    ORDER_DETAIL: {
                                                        sequence: { start: '31', stop: null },
                                                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                                                        subgroup: {
                                                            ORDER_OBSERVATION: { sequence: { start: '34', stop: '36' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                                                        },
                                                    },
                                                },
                                            },
                                        },
                                    },
                                },
                            },
                        },
                    },
                },
            },
            '2.7.1': {
                sequences: { ref: '2.7' },
                groups: { ref: '2.7' },
            },
        },
        segments: {
            MSH: MSH,
            MSA: MSA,
            ERR: ERR,
            QRD: QRD,
            PID: PID,
            PV1: PV1,
            PV2: PV2,
            PTH: PTH,
            NTE: NTE,
            VAR: VAR,
            ROL: ROL,
            PRB: PRB,
            OBX: OBX,
            GOL: GOL,
            ORC: ORC,
            OBR: OBR,
            RQD: RQD,
            RQ1: RQ1,
            RXO: RXO,
            ODS: ODS,
            ODT: ODT,
            QAK: QAK,
            SFT: SFT,
            UAC: UAC,
        },
    };

    constructor(message, version = null) {
        super(message, version);
    }
}
