import { MSH, SFT, UAC, MSA, ERR, QAK, QPD, PID, PD1, NTE, AL1, ORC, TQ1, TQ2, RXO, RXR, RXC, RXE, RXD, RXG, RXA, OBX, DSC } from '@healthcare-interoperability/hl7v2-segments';
import { TriggerEvent } from '@healthcare-interoperability/hl7v2-core';

export class RSP_Z86 extends TriggerEvent {
    static TriggerEvent = 'RSP_Z86';
    static Structure = {
        versions: {
            2.8: {
                sequences: [
                    {},
                    { identifier: 'MSH', sequence: '1', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: false },
                    { identifier: 'SFT', sequence: '2', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: false },
                    { identifier: 'UAC', sequence: '3', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: false },
                    { identifier: 'MSA', sequence: '4', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: false },
                    { identifier: 'ERR', sequence: '5', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: false },
                    { identifier: 'QAK', sequence: '6', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: false },
                    { identifier: 'QPD', sequence: '7', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: false },
                    { identifier: 'PID', sequence: '8', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['QUERY_RESPONSE', 'PATIENT'] },
                    { identifier: 'PD1', sequence: '9', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['QUERY_RESPONSE', 'PATIENT'] },
                    { identifier: 'NTE', sequence: '10', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['QUERY_RESPONSE', 'PATIENT'] },
                    { identifier: 'AL1', sequence: '11', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['QUERY_RESPONSE', 'PATIENT'] },
                    { identifier: 'ORC', sequence: '12', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['QUERY_RESPONSE', 'COMMON_ORDER'] },
                    { identifier: 'TQ1', sequence: '13', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['QUERY_RESPONSE', 'COMMON_ORDER', 'TIMING'] },
                    { identifier: 'TQ2', sequence: '14', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['QUERY_RESPONSE', 'COMMON_ORDER', 'TIMING'] },
                    { identifier: 'RXO', sequence: '15', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['QUERY_RESPONSE', 'COMMON_ORDER', 'ORDER_DETAIL'] },
                    {
                        identifier: 'RXR',
                        sequence: '16',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['QUERY_RESPONSE', 'COMMON_ORDER', 'ORDER_DETAIL'],
                    },
                    {
                        identifier: 'RXC',
                        sequence: '17',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['QUERY_RESPONSE', 'COMMON_ORDER', 'ORDER_DETAIL'],
                    },
                    { identifier: 'RXE', sequence: '18', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['QUERY_RESPONSE', 'COMMON_ORDER', 'ENCODED_ORDER'] },
                    {
                        identifier: 'TQ1',
                        sequence: '19',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['QUERY_RESPONSE', 'COMMON_ORDER', 'ENCODED_ORDER', 'TIMING_ENCODED'],
                    },
                    {
                        identifier: 'TQ2',
                        sequence: '20',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['QUERY_RESPONSE', 'COMMON_ORDER', 'ENCODED_ORDER', 'TIMING_ENCODED'],
                    },
                    {
                        identifier: 'RXR',
                        sequence: '21',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['QUERY_RESPONSE', 'COMMON_ORDER', 'ENCODED_ORDER'],
                    },
                    {
                        identifier: 'RXC',
                        sequence: '22',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['QUERY_RESPONSE', 'COMMON_ORDER', 'ENCODED_ORDER'],
                    },
                    { identifier: 'RXD', sequence: '23', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['QUERY_RESPONSE', 'COMMON_ORDER', 'DISPENSE'] },
                    { identifier: 'RXR', sequence: '24', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 }, isGroup: true, groupPath: ['QUERY_RESPONSE', 'COMMON_ORDER', 'DISPENSE'] },
                    { identifier: 'RXC', sequence: '25', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['QUERY_RESPONSE', 'COMMON_ORDER', 'DISPENSE'] },
                    { identifier: 'RXG', sequence: '26', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['QUERY_RESPONSE', 'COMMON_ORDER', 'GIVE'] },
                    { identifier: 'RXR', sequence: '27', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 }, isGroup: true, groupPath: ['QUERY_RESPONSE', 'COMMON_ORDER', 'GIVE'] },
                    { identifier: 'RXC', sequence: '28', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['QUERY_RESPONSE', 'COMMON_ORDER', 'GIVE'] },
                    {
                        identifier: 'RXA',
                        sequence: '29',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['QUERY_RESPONSE', 'COMMON_ORDER', 'ADMINISTRATION'],
                    },
                    {
                        identifier: 'RXR',
                        sequence: '30',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['QUERY_RESPONSE', 'COMMON_ORDER', 'ADMINISTRATION'],
                    },
                    {
                        identifier: 'RXC',
                        sequence: '31',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['QUERY_RESPONSE', 'COMMON_ORDER', 'ADMINISTRATION'],
                    },
                    { identifier: 'OBX', sequence: '32', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['QUERY_RESPONSE', 'COMMON_ORDER', 'OBSERVATION'] },
                    { identifier: 'NTE', sequence: '33', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['QUERY_RESPONSE', 'COMMON_ORDER', 'OBSERVATION'] },
                    { identifier: 'DSC', sequence: '34', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: false },
                ],
                groups: {
                    QUERY_RESPONSE: {
                        sequence: { start: null, stop: null },
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 },
                        subgroup: {
                            PATIENT: { sequence: { start: '8', stop: '11' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, subgroup: {} },
                            COMMON_ORDER: {
                                sequence: { start: '12', stop: null },
                                restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 },
                                subgroup: {
                                    TIMING: { sequence: { start: '13', stop: '14' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                                    ORDER_DETAIL: { sequence: { start: '15', stop: '17' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, subgroup: {} },
                                    ENCODED_ORDER: {
                                        sequence: { start: '18', stop: '22' },
                                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                                        subgroup: { TIMING_ENCODED: { sequence: { start: '19', stop: '20' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} } },
                                    },
                                    DISPENSE: { sequence: { start: '23', stop: '25' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, subgroup: {} },
                                    GIVE: { sequence: { start: '26', stop: '28' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, subgroup: {} },
                                    ADMINISTRATION: { sequence: { start: '29', stop: '31' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, subgroup: {} },
                                    OBSERVATION: { sequence: { start: '32', stop: '33' }, restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 }, subgroup: {} },
                                },
                            },
                        },
                    },
                },
            },
            2.6: {
                sequences: { ref: '2.8' },
                groups: { ref: '2.8' },
            },
            2.7: {
                sequences: { ref: '2.8' },
                groups: { ref: '2.8' },
            },
            '2.7.1': {
                sequences: { ref: '2.8' },
                groups: { ref: '2.8' },
            },
            2.5: {
                sequences: [
                    {},
                    { identifier: 'MSH', sequence: '1', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: false },
                    { identifier: 'SFT', sequence: '2', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: false },
                    { identifier: 'MSA', sequence: '3', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: false },
                    { identifier: 'ERR', sequence: '4', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: false },
                    { identifier: 'QAK', sequence: '5', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: false },
                    { identifier: 'QPD', sequence: '6', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: false },
                    { identifier: 'PID', sequence: '7', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['QUERY_RESPONSE', 'PATIENT'] },
                    { identifier: 'PD1', sequence: '8', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['QUERY_RESPONSE', 'PATIENT'] },
                    { identifier: 'NTE', sequence: '9', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['QUERY_RESPONSE', 'PATIENT'] },
                    { identifier: 'AL1', sequence: '10', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['QUERY_RESPONSE', 'PATIENT'] },
                    { identifier: 'ORC', sequence: '11', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['QUERY_RESPONSE', 'COMMON_ORDER'] },
                    { identifier: 'TQ1', sequence: '12', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['QUERY_RESPONSE', 'COMMON_ORDER', 'TIMING'] },
                    { identifier: 'TQ2', sequence: '13', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['QUERY_RESPONSE', 'COMMON_ORDER', 'TIMING'] },
                    { identifier: 'RXO', sequence: '14', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['QUERY_RESPONSE', 'COMMON_ORDER', 'ORDER_DETAIL'] },
                    {
                        identifier: 'RXR',
                        sequence: '15',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['QUERY_RESPONSE', 'COMMON_ORDER', 'ORDER_DETAIL'],
                    },
                    {
                        identifier: 'RXC',
                        sequence: '16',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['QUERY_RESPONSE', 'COMMON_ORDER', 'ORDER_DETAIL'],
                    },
                    { identifier: 'RXE', sequence: '17', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['QUERY_RESPONSE', 'COMMON_ORDER', 'ENCODED_ORDER'] },
                    {
                        identifier: 'TQ1',
                        sequence: '18',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['QUERY_RESPONSE', 'COMMON_ORDER', 'ENCODED_ORDER', 'TIMING_ENCODED'],
                    },
                    {
                        identifier: 'TQ2',
                        sequence: '19',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['QUERY_RESPONSE', 'COMMON_ORDER', 'ENCODED_ORDER', 'TIMING_ENCODED'],
                    },
                    {
                        identifier: 'RXR',
                        sequence: '20',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['QUERY_RESPONSE', 'COMMON_ORDER', 'ENCODED_ORDER'],
                    },
                    {
                        identifier: 'RXC',
                        sequence: '21',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['QUERY_RESPONSE', 'COMMON_ORDER', 'ENCODED_ORDER'],
                    },
                    { identifier: 'RXD', sequence: '22', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['QUERY_RESPONSE', 'COMMON_ORDER', 'DISPENSE'] },
                    { identifier: 'RXR', sequence: '23', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 }, isGroup: true, groupPath: ['QUERY_RESPONSE', 'COMMON_ORDER', 'DISPENSE'] },
                    { identifier: 'RXC', sequence: '24', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['QUERY_RESPONSE', 'COMMON_ORDER', 'DISPENSE'] },
                    { identifier: 'RXG', sequence: '25', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 }, isGroup: true, groupPath: ['QUERY_RESPONSE', 'COMMON_ORDER', 'GIVE'] },
                    { identifier: 'RXR', sequence: '26', restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 }, isGroup: true, groupPath: ['QUERY_RESPONSE', 'COMMON_ORDER', 'GIVE'] },
                    { identifier: 'RXC', sequence: '27', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['QUERY_RESPONSE', 'COMMON_ORDER', 'GIVE'] },
                    {
                        identifier: 'RXA',
                        sequence: '28',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 1 },
                        isGroup: true,
                        groupPath: ['QUERY_RESPONSE', 'COMMON_ORDER', 'ADMINISTRATION'],
                    },
                    {
                        identifier: 'RXR',
                        sequence: '29',
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['QUERY_RESPONSE', 'COMMON_ORDER', 'ADMINISTRATION'],
                    },
                    {
                        identifier: 'RXC',
                        sequence: '30',
                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 },
                        isGroup: true,
                        groupPath: ['QUERY_RESPONSE', 'COMMON_ORDER', 'ADMINISTRATION'],
                    },
                    { identifier: 'OBX', sequence: '31', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: true, groupPath: ['QUERY_RESPONSE', 'COMMON_ORDER', 'OBSERVATION'] },
                    { identifier: 'NTE', sequence: '32', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, isGroup: true, groupPath: ['QUERY_RESPONSE', 'COMMON_ORDER', 'OBSERVATION'] },
                    { identifier: 'DSC', sequence: '33', restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, isGroup: false },
                ],
                groups: {
                    QUERY_RESPONSE: {
                        sequence: { start: null, stop: null },
                        restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 },
                        subgroup: {
                            PATIENT: { sequence: { start: '7', stop: '10' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, subgroup: {} },
                            COMMON_ORDER: {
                                sequence: { start: '11', stop: null },
                                restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 },
                                subgroup: {
                                    TIMING: { sequence: { start: '12', stop: '13' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} },
                                    ORDER_DETAIL: { sequence: { start: '14', stop: '16' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, subgroup: {} },
                                    ENCODED_ORDER: {
                                        sequence: { start: '17', stop: '21' },
                                        restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 },
                                        subgroup: { TIMING_ENCODED: { sequence: { start: '18', stop: '19' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 9999 }, subgroup: {} } },
                                    },
                                    DISPENSE: { sequence: { start: '22', stop: '24' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, subgroup: {} },
                                    GIVE: { sequence: { start: '25', stop: '27' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, subgroup: {} },
                                    ADMINISTRATION: { sequence: { start: '28', stop: '30' }, restrictions: { nillable: true, minOccurs: 0, maxOccurs: 1 }, subgroup: {} },
                                    OBSERVATION: { sequence: { start: '31', stop: '32' }, restrictions: { nillable: false, minOccurs: 1, maxOccurs: 9999 }, subgroup: {} },
                                },
                            },
                        },
                    },
                },
            },
            '2.5.1': {
                sequences: { ref: '2.5' },
                groups: { ref: '2.5' },
            },
        },
        segments: {
            MSH: MSH,
            SFT: SFT,
            UAC: UAC,
            MSA: MSA,
            ERR: ERR,
            QAK: QAK,
            QPD: QPD,
            PID: PID,
            PD1: PD1,
            NTE: NTE,
            AL1: AL1,
            ORC: ORC,
            TQ1: TQ1,
            TQ2: TQ2,
            RXO: RXO,
            RXR: RXR,
            RXC: RXC,
            RXE: RXE,
            RXD: RXD,
            RXG: RXG,
            RXA: RXA,
            OBX: OBX,
            DSC: DSC,
        },
    };

    constructor(message, version = null) {
        super(message, version);
    }
}
